// __tests__/api/karte-pdf.test.ts — カルテPDF生成テスト
import { describe, it, expect, vi, beforeEach } from "vitest";

// vi.hoistedでモック関数を先に定義
const { mockText, mockSetFontSize, mockOutput, mockAddPage } = vi.hoisted(() => {
  const mockText = vi.fn();
  const mockSetFontSize = vi.fn();
  const mockOutput = vi.fn().mockReturnValue(new ArrayBuffer(200));
  const mockAddPage = vi.fn();
  return { mockText, mockSetFontSize, mockOutput, mockAddPage };
});

vi.mock("jspdf", () => {
  return {
    jsPDF: class {
      text = mockText;
      setFontSize = mockSetFontSize;
      output = mockOutput;
      addPage = mockAddPage;
      lastAutoTable = { finalY: 150 };
    },
  };
});

vi.mock("jspdf-autotable", () => ({
  default: vi.fn(),
}));

import { generateKartePDF, type KartePdfData } from "@/lib/karte-pdf";

describe("karte-pdf", () => {
  const baseSoap = { s: "Headache for 3 days", o: "BP 120/80", a: "Tension headache", p: "Acetaminophen 500mg" };

  const sampleData: KartePdfData = {
    clinicName: "Test Clinic",
    patientName: "Yamada Taro",
    patientId: "P-001",
    date: "2026-03-07",
    soap: baseSoap,
    prescriptionMenu: "GLP-1 2mg",
    vitals: {
      measuredAt: "2026-03-07",
      height: 170,
      weight: 65,
      bmi: 22.5,
      systolic: 120,
      diastolic: 80,
      pulse: 72,
      temperature: 36.5,
    },
    templateName: "Initial Assessment",
    imageUrls: ["https://example.com/img1.jpg", "https://example.com/img2.jpg"],
    reservedDate: "2026-03-07",
    reservedTime: "14:00",
    status: "OK",
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("Bufferを返す", () => {
    const result = generateKartePDF(sampleData);
    expect(result).toBeInstanceOf(Buffer);
  });

  it("KARTEタイトルが設定される", () => {
    generateKartePDF(sampleData);
    expect(mockText).toHaveBeenCalledWith("KARTE", 105, 15, { align: "center" });
  });

  it("クリニック名が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).toContain("Test Clinic");
  });

  it("患者名が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Yamada Taro"))).toBe(true);
  });

  it("患者IDが含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("P-001"))).toBe(true);
  });

  it("日付が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("2026-03-07"))).toBe(true);
  });

  it("ステータスが含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Status: OK"))).toBe(true);
  });

  it("予約情報が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Reservation:"))).toBe(true);
  });

  it("テンプレート名が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Template: Initial Assessment"))).toBe(true);
  });

  it("SOAPセクションのautoTableが呼ばれる", async () => {
    const autoTable = (await import("jspdf-autotable")).default;
    generateKartePDF(sampleData);
    expect(autoTable).toHaveBeenCalled();
  });

  it("処方内容が含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).toContain("Prescription");
    expect(textCalls).toContain("GLP-1 2mg");
  });

  it("画像URLが含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).toContain("https://example.com/img1.jpg");
    expect(textCalls).toContain("https://example.com/img2.jpg");
  });

  it("フッターが含まれる", () => {
    generateKartePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).toContain("Generated by L-ope for CLINIC");
  });

  it("処方なしの場合はPrescriptionセクションが表示されない", () => {
    generateKartePDF({ ...sampleData, prescriptionMenu: null });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).not.toContain("Prescription");
  });

  it("バイタルなしの場合はVitalsセクションが表示されない", () => {
    generateKartePDF({ ...sampleData, vitals: null });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).not.toContain("Vitals");
  });

  it("画像なしの場合はImagesセクションが表示されない", () => {
    generateKartePDF({ ...sampleData, imageUrls: [] });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls).not.toContain("Images");
  });

  it("予約なしの場合はReservation行が表示されない", () => {
    generateKartePDF({ ...sampleData, reservedDate: null, reservedTime: null });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Reservation:"))).toBe(false);
  });

  it("テンプレートなしの場合はTemplate行が表示されない", () => {
    generateKartePDF({ ...sampleData, templateName: null });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Template:"))).toBe(false);
  });

  it("ステータスなしの場合はStatus行が表示されない", () => {
    generateKartePDF({ ...sampleData, status: null });
    const textCalls = mockText.mock.calls.map((c: unknown[]) => c[0]);
    expect(textCalls.some((t) => typeof t === "string" && t.includes("Status:"))).toBe(false);
  });

  it("SOAP内容が空でもエラーにならない", () => {
    const emptyData: KartePdfData = {
      clinicName: "",
      patientName: "",
      patientId: "",
      date: "",
      soap: { s: "", o: "", a: "", p: "" },
      prescriptionMenu: null,
      vitals: null,
      templateName: null,
      imageUrls: [],
      reservedDate: null,
      reservedTime: null,
      status: null,
    };
    expect(() => generateKartePDF(emptyData)).not.toThrow();
  });
});
