// lib/voice/default-vocabulary.ts — 診療科別デフォルト医療辞書
// テナント初期セットアップ時に medical_vocabulary テーブルに一括 INSERT する

export type VocabEntry = {
  term: string;
  reading?: string;
  category: "drug" | "symptom" | "procedure" | "anatomy" | "lab" | "general";
  boost_weight: number;
};

/** 診療科カテゴリ */
export type Specialty =
  | "common"
  | "beauty"
  | "internal"
  | "surgery"
  | "orthopedics"
  | "dermatology";

export const SPECIALTY_LABELS: Record<Specialty, string> = {
  common: "共通（全科）",
  beauty: "美容（自由診療）",
  internal: "内科",
  surgery: "外科",
  orthopedics: "整形外科",
  dermatology: "皮膚科",
};

/** カテゴリラベル */
export const CATEGORY_LABELS: Record<VocabEntry["category"], string> = {
  drug: "薬剤",
  symptom: "症状",
  procedure: "処置・検査",
  anatomy: "解剖",
  lab: "検査値",
  general: "その他",
};

// ================================================================
// 共通（全科）— 全テナントに必ず適用
// ================================================================
const COMMON: VocabEntry[] = [
  // バイタル・基本
  { term: "バイタルサイン", category: "general", boost_weight: 1.5 },
  { term: "血圧", reading: "けつあつ", category: "lab", boost_weight: 1.5 },
  { term: "収縮期血圧", reading: "しゅうしゅくきけつあつ", category: "lab", boost_weight: 1.5 },
  { term: "拡張期血圧", reading: "かくちょうきけつあつ", category: "lab", boost_weight: 1.5 },
  { term: "脈拍", reading: "みゃくはく", category: "lab", boost_weight: 1.5 },
  { term: "心拍数", reading: "しんぱくすう", category: "lab", boost_weight: 1.5 },
  { term: "体温", reading: "たいおん", category: "lab", boost_weight: 1.5 },
  { term: "呼吸数", reading: "こきゅうすう", category: "lab", boost_weight: 1.5 },
  { term: "SpO2", category: "lab", boost_weight: 2.0 },
  { term: "BMI", category: "lab", boost_weight: 1.5 },
  { term: "体重", reading: "たいじゅう", category: "lab", boost_weight: 1.5 },
  { term: "身長", reading: "しんちょう", category: "lab", boost_weight: 1.0 },
  { term: "意識レベル", reading: "いしきれべる", category: "general", boost_weight: 1.5 },
  { term: "JCS", category: "general", boost_weight: 1.5 },
  { term: "GCS", category: "general", boost_weight: 1.5 },
  // 問診基本
  { term: "既往歴", reading: "きおうれき", category: "general", boost_weight: 1.5 },
  { term: "現病歴", reading: "げんびょうれき", category: "general", boost_weight: 1.5 },
  { term: "家族歴", reading: "かぞくれき", category: "general", boost_weight: 1.5 },
  { term: "社会歴", reading: "しゃかいれき", category: "general", boost_weight: 1.5 },
  { term: "服薬歴", reading: "ふくやくれき", category: "general", boost_weight: 1.5 },
  { term: "手術歴", reading: "しゅじゅつれき", category: "general", boost_weight: 1.5 },
  { term: "アレルギー", category: "general", boost_weight: 1.5 },
  { term: "薬物アレルギー", reading: "やくぶつあれるぎー", category: "general", boost_weight: 1.5 },
  { term: "食物アレルギー", reading: "しょくもつあれるぎー", category: "general", boost_weight: 1.5 },
  { term: "副作用", reading: "ふくさよう", category: "general", boost_weight: 1.5 },
  { term: "有害事象", reading: "ゆうがいじしょう", category: "general", boost_weight: 1.5 },
  { term: "禁忌", reading: "きんき", category: "general", boost_weight: 1.5 },
  { term: "併用禁忌", reading: "へいようきんき", category: "general", boost_weight: 1.5 },
  { term: "アナフィラキシー", category: "symptom", boost_weight: 2.0 },
  // 処方関連
  { term: "処方", reading: "しょほう", category: "general", boost_weight: 1.5 },
  { term: "処方箋", reading: "しょほうせん", category: "general", boost_weight: 1.5 },
  { term: "用量", reading: "ようりょう", category: "general", boost_weight: 1.5 },
  { term: "用法", reading: "ようほう", category: "general", boost_weight: 1.5 },
  { term: "増量", reading: "ぞうりょう", category: "general", boost_weight: 1.5 },
  { term: "減量", reading: "げんりょう", category: "general", boost_weight: 1.5 },
  { term: "投与", reading: "とうよ", category: "general", boost_weight: 1.5 },
  { term: "経口投与", reading: "けいこうとうよ", category: "general", boost_weight: 1.5 },
  { term: "皮下注射", reading: "ひかちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "筋肉注射", reading: "きんにくちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "静脈注射", reading: "じょうみゃくちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "点滴", reading: "てんてき", category: "general", boost_weight: 1.5 },
  { term: "外用", reading: "がいよう", category: "general", boost_weight: 1.5 },
  { term: "頓服", reading: "とんぷく", category: "general", boost_weight: 1.5 },
  { term: "内服", reading: "ないふく", category: "general", boost_weight: 1.5 },
  { term: "服用", reading: "ふくよう", category: "general", boost_weight: 1.5 },
  { term: "後発品", reading: "こうはつひん", category: "general", boost_weight: 1.0 },
  { term: "ジェネリック", category: "general", boost_weight: 1.0 },
  { term: "先発品", reading: "せんぱつひん", category: "general", boost_weight: 1.0 },
  { term: "添付文書", reading: "てんぷぶんしょ", category: "general", boost_weight: 1.0 },
  { term: "適応", reading: "てきおう", category: "general", boost_weight: 1.0 },
  { term: "適応外", reading: "てきおうがい", category: "general", boost_weight: 1.5 },
  // 単位
  { term: "mg", category: "general", boost_weight: 1.0 },
  { term: "mL", category: "general", boost_weight: 1.0 },
  { term: "μg", category: "general", boost_weight: 1.0 },
  { term: "IU", category: "general", boost_weight: 1.0 },
  { term: "錠", reading: "じょう", category: "general", boost_weight: 1.0 },
  { term: "カプセル", category: "general", boost_weight: 1.0 },
  { term: "包", reading: "ほう", category: "general", boost_weight: 1.0 },
  { term: "アンプル", category: "general", boost_weight: 1.0 },
  { term: "バイアル", category: "general", boost_weight: 1.0 },
  // カルテ用語
  { term: "主訴", reading: "しゅそ", category: "general", boost_weight: 1.5 },
  { term: "所見", reading: "しょけん", category: "general", boost_weight: 1.5 },
  { term: "理学所見", reading: "りがくしょけん", category: "general", boost_weight: 1.5 },
  { term: "視診", reading: "ししん", category: "general", boost_weight: 1.5 },
  { term: "触診", reading: "しょくしん", category: "general", boost_weight: 1.5 },
  { term: "聴診", reading: "ちょうしん", category: "general", boost_weight: 1.5 },
  { term: "打診", reading: "だしん", category: "general", boost_weight: 1.5 },
  { term: "経過観察", reading: "けいかかんさつ", category: "general", boost_weight: 1.5 },
  { term: "再診", reading: "さいしん", category: "general", boost_weight: 1.5 },
  { term: "初診", reading: "しょしん", category: "general", boost_weight: 1.5 },
  { term: "紹介状", reading: "しょうかいじょう", category: "general", boost_weight: 1.5 },
  { term: "同意書", reading: "どういしょ", category: "general", boost_weight: 1.0 },
  { term: "インフォームドコンセント", category: "general", boost_weight: 1.5 },
  { term: "SOAP", category: "general", boost_weight: 1.5 },
  { term: "問診", reading: "もんしん", category: "general", boost_weight: 1.5 },
  { term: "診察", reading: "しんさつ", category: "general", boost_weight: 1.5 },
  { term: "診断", reading: "しんだん", category: "general", boost_weight: 1.5 },
  { term: "鑑別診断", reading: "かんべつしんだん", category: "general", boost_weight: 1.5 },
  { term: "予後", reading: "よご", category: "general", boost_weight: 1.5 },
  { term: "寛解", reading: "かんかい", category: "general", boost_weight: 1.5 },
  { term: "増悪", reading: "ぞうあく", category: "general", boost_weight: 1.5 },
  { term: "改善", reading: "かいぜん", category: "general", boost_weight: 1.0 },
  { term: "悪化", reading: "あっか", category: "general", boost_weight: 1.0 },
  { term: "安静", reading: "あんせい", category: "general", boost_weight: 1.0 },
  // 共通症状
  { term: "発熱", reading: "はつねつ", category: "symptom", boost_weight: 1.5 },
  { term: "倦怠感", reading: "けんたいかん", category: "symptom", boost_weight: 1.5 },
  { term: "頭痛", reading: "ずつう", category: "symptom", boost_weight: 1.5 },
  { term: "めまい", category: "symptom", boost_weight: 1.5 },
  { term: "浮腫", reading: "ふしゅ", category: "symptom", boost_weight: 1.5 },
  { term: "むくみ", category: "symptom", boost_weight: 1.5 },
  { term: "疼痛", reading: "とうつう", category: "symptom", boost_weight: 1.5 },
  { term: "痛み", reading: "いたみ", category: "symptom", boost_weight: 1.0 },
  { term: "しびれ", category: "symptom", boost_weight: 1.5 },
  { term: "かゆみ", category: "symptom", boost_weight: 1.5 },
  { term: "発疹", reading: "ほっしん", category: "symptom", boost_weight: 1.5 },
  { term: "出血", reading: "しゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "脱水", reading: "だっすい", category: "symptom", boost_weight: 1.5 },
  { term: "黄疸", reading: "おうだん", category: "symptom", boost_weight: 2.0 },
  { term: "チアノーゼ", category: "symptom", boost_weight: 2.0 },
  // オンライン診療
  { term: "オンライン診療", reading: "おんらいんしんりょう", category: "general", boost_weight: 1.5 },
  { term: "遠隔診療", reading: "えんかくしんりょう", category: "general", boost_weight: 1.5 },
  { term: "対面診療", reading: "たいめんしんりょう", category: "general", boost_weight: 1.0 },
  { term: "自費診療", reading: "じひしんりょう", category: "general", boost_weight: 1.5 },
  { term: "自由診療", reading: "じゆうしんりょう", category: "general", boost_weight: 1.5 },
  { term: "保険診療", reading: "ほけんしんりょう", category: "general", boost_weight: 1.0 },
  { term: "配送", reading: "はいそう", category: "general", boost_weight: 1.0 },
  { term: "服薬指導", reading: "ふくやくしどう", category: "general", boost_weight: 1.5 },
  // 共通薬剤
  { term: "アセトアミノフェン", category: "drug", boost_weight: 1.5 },
  { term: "カロナール", category: "drug", boost_weight: 1.5 },
  { term: "イブプロフェン", category: "drug", boost_weight: 1.5 },
  { term: "抗生物質", reading: "こうせいぶっしつ", category: "drug", boost_weight: 1.5 },
  { term: "抗菌薬", reading: "こうきんやく", category: "drug", boost_weight: 1.5 },
];

// ================================================================
// 美容（自由診療）
// ================================================================
const BEAUTY: VocabEntry[] = [
  // GLP-1 / ダイエット
  { term: "マンジャロ", category: "drug", boost_weight: 2.0 },
  { term: "チルゼパチド", category: "drug", boost_weight: 2.0 },
  { term: "オゼンピック", category: "drug", boost_weight: 2.0 },
  { term: "セマグルチド", category: "drug", boost_weight: 2.0 },
  { term: "リベルサス", category: "drug", boost_weight: 2.0 },
  { term: "サクセンダ", category: "drug", boost_weight: 2.0 },
  { term: "ウゴービ", category: "drug", boost_weight: 2.0 },
  { term: "ビクトーザ", category: "drug", boost_weight: 2.0 },
  { term: "リラグルチド", category: "drug", boost_weight: 2.0 },
  { term: "トルリシティ", category: "drug", boost_weight: 2.0 },
  { term: "デュラグルチド", category: "drug", boost_weight: 2.0 },
  { term: "GLP-1", category: "drug", boost_weight: 2.0 },
  { term: "GLP-1受容体作動薬", reading: "じーえるぴーわんじゅようたいさどうやく", category: "drug", boost_weight: 2.0 },
  { term: "GIP/GLP-1", category: "drug", boost_weight: 2.0 },
  { term: "インクレチン", category: "drug", boost_weight: 1.5 },
  // ダイエット関連
  { term: "メディカルダイエット", category: "procedure", boost_weight: 1.5 },
  { term: "食欲抑制", reading: "しょくよくよくせい", category: "general", boost_weight: 1.5 },
  { term: "基礎代謝", reading: "きそたいしゃ", category: "general", boost_weight: 1.0 },
  { term: "内臓脂肪", reading: "ないぞうしぼう", category: "general", boost_weight: 1.5 },
  { term: "肥満", reading: "ひまん", category: "symptom", boost_weight: 1.5 },
  { term: "肥満症", reading: "ひまんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "体脂肪率", reading: "たいしぼうりつ", category: "lab", boost_weight: 1.0 },
  { term: "ダイエット注射", reading: "だいえっとちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "痩身", reading: "そうしん", category: "procedure", boost_weight: 1.5 },
  { term: "脂肪溶解注射", reading: "しぼうようかいちゅうしゃ", category: "procedure", boost_weight: 2.0 },
  { term: "BNLS", category: "drug", boost_weight: 2.0 },
  { term: "カベリン", category: "drug", boost_weight: 2.0 },
  { term: "脂肪吸引", reading: "しぼうきゅういん", category: "procedure", boost_weight: 2.0 },
  { term: "クールスカルプティング", category: "procedure", boost_weight: 2.0 },
  { term: "エムスカルプト", category: "procedure", boost_weight: 2.0 },
  { term: "防風通聖散", reading: "ぼうふうつうしょうさん", category: "drug", boost_weight: 2.0 },
  { term: "ゼニカル", category: "drug", boost_weight: 2.0 },
  { term: "オルリスタット", category: "drug", boost_weight: 2.0 },
  { term: "リパーゼ阻害薬", reading: "りぱーぜそがいやく", category: "drug", boost_weight: 1.5 },
  { term: "サノレックス", category: "drug", boost_weight: 2.0 },
  { term: "マジンドール", category: "drug", boost_weight: 2.0 },
  // AGA / 薄毛
  { term: "フィナステリド", category: "drug", boost_weight: 2.0 },
  { term: "デュタステリド", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル", category: "drug", boost_weight: 2.0 },
  { term: "プロペシア", category: "drug", boost_weight: 2.0 },
  { term: "ザガーロ", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル内服", reading: "みのきしじるないふく", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル外用", reading: "みのきしじるがいよう", category: "drug", boost_weight: 2.0 },
  { term: "ミノタブ", category: "drug", boost_weight: 1.5 },
  { term: "5α還元酵素阻害薬", reading: "ごあるふぁかんげんこうそそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "AGA", category: "symptom", boost_weight: 2.0 },
  { term: "FAGA", category: "symptom", boost_weight: 2.0 },
  { term: "男性型脱毛症", reading: "だんせいがただつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "女性型脱毛症", reading: "じょせいがただつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "薄毛", reading: "うすげ", category: "symptom", boost_weight: 1.5 },
  { term: "脱毛", reading: "だつもう", category: "symptom", boost_weight: 1.5 },
  { term: "抜け毛", reading: "ぬけげ", category: "symptom", boost_weight: 1.5 },
  { term: "頭頂部", reading: "とうちょうぶ", category: "anatomy", boost_weight: 1.0 },
  { term: "前頭部", reading: "ぜんとうぶ", category: "anatomy", boost_weight: 1.0 },
  { term: "M字", reading: "えむじ", category: "symptom", boost_weight: 1.5 },
  { term: "HARG療法", reading: "はーぐりょうほう", category: "procedure", boost_weight: 2.0 },
  { term: "メソセラピー", category: "procedure", boost_weight: 1.5 },
  { term: "育毛", reading: "いくもう", category: "general", boost_weight: 1.0 },
  { term: "発毛", reading: "はつもう", category: "general", boost_weight: 1.0 },
  { term: "スピロノラクトン", category: "drug", boost_weight: 2.0 },
  { term: "パントガール", category: "drug", boost_weight: 2.0 },
  // 美容注射・フィラー
  { term: "ボトックス", category: "drug", boost_weight: 2.0 },
  { term: "ボツリヌストキシン", category: "drug", boost_weight: 2.0 },
  { term: "ボツラックス", category: "drug", boost_weight: 2.0 },
  { term: "ゼオミン", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロン酸", reading: "ひあるろんさん", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロン酸注入", reading: "ひあるろんさんちゅうにゅう", category: "procedure", boost_weight: 2.0 },
  { term: "フィラー", category: "drug", boost_weight: 2.0 },
  { term: "ジュビダーム", category: "drug", boost_weight: 2.0 },
  { term: "ジュビダームビスタ", category: "drug", boost_weight: 2.0 },
  { term: "ボリューマ", category: "drug", boost_weight: 2.0 },
  { term: "ボルベラ", category: "drug", boost_weight: 2.0 },
  { term: "レスチレン", category: "drug", boost_weight: 2.0 },
  { term: "レスチレンリド", category: "drug", boost_weight: 2.0 },
  { term: "ベビーコラーゲン", category: "drug", boost_weight: 1.5 },
  { term: "レディエッセ", category: "drug", boost_weight: 2.0 },
  { term: "エランセ", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロニダーゼ", category: "drug", boost_weight: 2.0 },
  { term: "溶解注射", reading: "ようかいちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  // 美容注射・点滴
  { term: "白玉点滴", reading: "しらたまてんてき", category: "procedure", boost_weight: 1.5 },
  { term: "グルタチオン", category: "drug", boost_weight: 2.0 },
  { term: "高濃度ビタミンC点滴", reading: "こうのうどびたみんしーてんてき", category: "procedure", boost_weight: 2.0 },
  { term: "マイヤーズカクテル", category: "procedure", boost_weight: 1.5 },
  { term: "にんにく注射", reading: "にんにくちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "プラセンタ注射", reading: "ぷらせんたちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ラエンネック", category: "drug", boost_weight: 2.0 },
  { term: "メルスモン", category: "drug", boost_weight: 2.0 },
  { term: "NMN点滴", reading: "えぬえむえぬてんてき", category: "procedure", boost_weight: 2.0 },
  { term: "エクソソーム", category: "drug", boost_weight: 2.0 },
  { term: "PRP", category: "procedure", boost_weight: 2.0 },
  { term: "多血小板血漿", reading: "たけっしょうばんけっしょう", category: "procedure", boost_weight: 2.0 },
  { term: "幹細胞", reading: "かんさいぼう", category: "general", boost_weight: 1.5 },
  // レーザー・光治療
  { term: "水光注射", reading: "すいこうちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ダーマペン", category: "procedure", boost_weight: 1.5 },
  { term: "ダーマペン4", category: "procedure", boost_weight: 2.0 },
  { term: "ヴェルベットスキン", category: "procedure", boost_weight: 1.5 },
  { term: "ピーリング", category: "procedure", boost_weight: 1.5 },
  { term: "ケミカルピーリング", category: "procedure", boost_weight: 1.5 },
  { term: "サリチル酸ピーリング", reading: "さりちるさんぴーりんぐ", category: "procedure", boost_weight: 1.5 },
  { term: "マッサージピール", category: "procedure", boost_weight: 1.5 },
  { term: "コラーゲンピール", category: "procedure", boost_weight: 1.5 },
  { term: "ハイフ", category: "procedure", boost_weight: 2.0 },
  { term: "HIFU", category: "procedure", boost_weight: 2.0 },
  { term: "ウルセラ", category: "procedure", boost_weight: 2.0 },
  { term: "ソノクイーン", category: "procedure", boost_weight: 2.0 },
  { term: "ウルトラフォーマー", category: "procedure", boost_weight: 2.0 },
  { term: "フォトフェイシャル", category: "procedure", boost_weight: 1.5 },
  { term: "IPL", category: "procedure", boost_weight: 1.5 },
  { term: "レーザートーニング", category: "procedure", boost_weight: 1.5 },
  { term: "ピコレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "ピコトーニング", category: "procedure", boost_weight: 2.0 },
  { term: "ピコスポット", category: "procedure", boost_weight: 2.0 },
  { term: "ピコフラクショナル", category: "procedure", boost_weight: 2.0 },
  { term: "Qスイッチレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "YAGレーザー", reading: "やぐれーざー", category: "procedure", boost_weight: 2.0 },
  { term: "アレキサンドライトレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "CO2レーザー", category: "procedure", boost_weight: 2.0 },
  { term: "炭酸ガスレーザー", reading: "たんさんがすれーざー", category: "procedure", boost_weight: 2.0 },
  { term: "フラクショナルレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "ジェネシス", category: "procedure", boost_weight: 1.5 },
  { term: "ポテンツァ", category: "procedure", boost_weight: 2.0 },
  { term: "RF", category: "procedure", boost_weight: 1.5 },
  { term: "ラジオ波", reading: "らじおは", category: "procedure", boost_weight: 1.5 },
  { term: "サーマクール", category: "procedure", boost_weight: 2.0 },
  { term: "医療脱毛", reading: "いりょうだつもう", category: "procedure", boost_weight: 1.5 },
  { term: "蓄熱式脱毛", reading: "ちくねつしきだつもう", category: "procedure", boost_weight: 1.5 },
  { term: "ダイオードレーザー", category: "procedure", boost_weight: 2.0 },
  // 糸リフト・美容外科
  { term: "スレッドリフト", category: "procedure", boost_weight: 2.0 },
  { term: "糸リフト", reading: "いとりふと", category: "procedure", boost_weight: 2.0 },
  { term: "フェイスリフト", category: "procedure", boost_weight: 1.5 },
  { term: "ミントリフト", category: "procedure", boost_weight: 2.0 },
  { term: "テスリフト", category: "procedure", boost_weight: 2.0 },
  { term: "二重整形", reading: "ふたえせいけい", category: "procedure", boost_weight: 1.5 },
  { term: "埋没法", reading: "まいぼつほう", category: "procedure", boost_weight: 2.0 },
  { term: "切開法", reading: "せっかいほう", category: "procedure", boost_weight: 1.5 },
  { term: "目頭切開", reading: "めがしらせっかい", category: "procedure", boost_weight: 1.5 },
  { term: "目尻切開", reading: "めじりせっかい", category: "procedure", boost_weight: 1.5 },
  { term: "鼻整形", reading: "はなせいけい", category: "procedure", boost_weight: 1.5 },
  { term: "隆鼻術", reading: "りゅうびじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "鼻尖形成", reading: "びせんけいせい", category: "procedure", boost_weight: 2.0 },
  { term: "小鼻縮小", reading: "こばなしゅくしょう", category: "procedure", boost_weight: 1.5 },
  { term: "豊胸術", reading: "ほうきょうじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "脂肪注入", reading: "しぼうちゅうにゅう", category: "procedure", boost_weight: 1.5 },
  { term: "エラ削り", reading: "えらけずり", category: "procedure", boost_weight: 1.5 },
  { term: "顎形成", reading: "あごけいせい", category: "procedure", boost_weight: 1.5 },
  { term: "リップアートメイク", category: "procedure", boost_weight: 1.5 },
  { term: "アートメイク", category: "procedure", boost_weight: 1.5 },
  // 肌・症状
  { term: "シミ", category: "symptom", boost_weight: 1.5 },
  { term: "しわ", category: "symptom", boost_weight: 1.5 },
  { term: "たるみ", category: "symptom", boost_weight: 1.5 },
  { term: "ニキビ", category: "symptom", boost_weight: 1.5 },
  { term: "ニキビ跡", reading: "にきびあと", category: "symptom", boost_weight: 1.5 },
  { term: "毛穴", reading: "けあな", category: "symptom", boost_weight: 1.5 },
  { term: "肝斑", reading: "かんぱん", category: "symptom", boost_weight: 2.0 },
  { term: "色素沈着", reading: "しきそちんちゃく", category: "symptom", boost_weight: 1.5 },
  { term: "くすみ", category: "symptom", boost_weight: 1.5 },
  { term: "赤ら顔", reading: "あからがお", category: "symptom", boost_weight: 1.5 },
  { term: "毛細血管拡張", reading: "もうさいけっかんかくちょう", category: "symptom", boost_weight: 1.5 },
  { term: "クレーター", category: "symptom", boost_weight: 1.5 },
  { term: "肌荒れ", reading: "はだあれ", category: "symptom", boost_weight: 1.0 },
  { term: "乾燥肌", reading: "かんそうはだ", category: "symptom", boost_weight: 1.0 },
  { term: "敏感肌", reading: "びんかんはだ", category: "symptom", boost_weight: 1.0 },
  { term: "そばかす", category: "symptom", boost_weight: 1.5 },
  { term: "老人性色素斑", reading: "ろうじんせいしきそはん", category: "symptom", boost_weight: 2.0 },
  { term: "日光黒子", reading: "にっこうこくし", category: "symptom", boost_weight: 2.0 },
  { term: "ほうれい線", reading: "ほうれいせん", category: "anatomy", boost_weight: 1.5 },
  { term: "マリオネットライン", category: "anatomy", boost_weight: 1.5 },
  { term: "ゴルゴライン", category: "anatomy", boost_weight: 1.5 },
  { term: "法令線", reading: "ほうれいせん", category: "anatomy", boost_weight: 1.5 },
  { term: "目の下のたるみ", reading: "めのしたのたるみ", category: "symptom", boost_weight: 1.5 },
  { term: "クマ", category: "symptom", boost_weight: 1.5 },
  { term: "眼瞼下垂", reading: "がんけんかすい", category: "symptom", boost_weight: 2.0 },
  { term: "多汗症", reading: "たかんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "ワキガ", category: "symptom", boost_weight: 1.5 },
  { term: "腋臭症", reading: "えきしゅうしょう", category: "symptom", boost_weight: 2.0 },
  // GLP-1 副作用
  { term: "嘔気", reading: "おうき", category: "symptom", boost_weight: 1.5 },
  { term: "悪心", reading: "おしん", category: "symptom", boost_weight: 1.5 },
  { term: "嘔吐", reading: "おうと", category: "symptom", boost_weight: 1.5 },
  { term: "低血糖", reading: "ていけっとう", category: "symptom", boost_weight: 1.5 },
  { term: "下痢", reading: "げり", category: "symptom", boost_weight: 1.5 },
  { term: "便秘", reading: "べんぴ", category: "symptom", boost_weight: 1.5 },
  { term: "腹痛", reading: "ふくつう", category: "symptom", boost_weight: 1.5 },
  { term: "食欲不振", reading: "しょくよくふしん", category: "symptom", boost_weight: 1.5 },
  { term: "膵炎リスク", reading: "すいえんりすく", category: "symptom", boost_weight: 1.5 },
  { term: "注射部位反応", reading: "ちゅうしゃぶいはんのう", category: "symptom", boost_weight: 1.5 },
  { term: "胃腸障害", reading: "いちょうしょうがい", category: "symptom", boost_weight: 1.5 },
  // 美容皮膚科・スキンケア
  { term: "トレチノイン", category: "drug", boost_weight: 2.0 },
  { term: "レチノール", category: "drug", boost_weight: 1.5 },
  { term: "レチノイド", category: "drug", boost_weight: 1.5 },
  { term: "ハイドロキノン", category: "drug", boost_weight: 2.0 },
  { term: "ビタミンC誘導体", reading: "びたみんしーゆうどうたい", category: "drug", boost_weight: 1.5 },
  { term: "アスコルビン酸", reading: "あすこるびんさん", category: "drug", boost_weight: 1.5 },
  { term: "ナイアシンアミド", category: "drug", boost_weight: 1.5 },
  { term: "トラネキサム酸", reading: "とらねきさむさん", category: "drug", boost_weight: 2.0 },
  { term: "グリコール酸", reading: "ぐりこーるさん", category: "drug", boost_weight: 1.5 },
  { term: "アゼライン酸", reading: "あぜらいんさん", category: "drug", boost_weight: 1.5 },
  { term: "セラミド", category: "general", boost_weight: 1.0 },
  { term: "ペプチド", category: "general", boost_weight: 1.0 },
  { term: "成長因子", reading: "せいちょういんし", category: "general", boost_weight: 1.5 },
  { term: "EGF", category: "general", boost_weight: 1.5 },
  { term: "FGF", category: "general", boost_weight: 1.5 },
  { term: "エラスチン", category: "general", boost_weight: 1.5 },
  { term: "コラーゲン", category: "general", boost_weight: 1.5 },
  { term: "プラセンタ", category: "drug", boost_weight: 1.5 },
  { term: "ボトックスビスタ", category: "drug", boost_weight: 2.0 },
  { term: "アラガン", category: "general", boost_weight: 1.5 },
  // ED治療
  { term: "シルデナフィル", category: "drug", boost_weight: 2.0 },
  { term: "バイアグラ", category: "drug", boost_weight: 2.0 },
  { term: "タダラフィル", category: "drug", boost_weight: 2.0 },
  { term: "シアリス", category: "drug", boost_weight: 2.0 },
  { term: "バルデナフィル", category: "drug", boost_weight: 2.0 },
  { term: "レビトラ", category: "drug", boost_weight: 2.0 },
  { term: "ED", category: "symptom", boost_weight: 1.5 },
  { term: "勃起不全", reading: "ぼっきふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "PDE5阻害薬", reading: "ぴーでぃーいーふぁいぶそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "早漏", reading: "そうろう", category: "symptom", boost_weight: 1.5 },
  // ピル・婦人科
  { term: "低用量ピル", reading: "ていようりょうぴる", category: "drug", boost_weight: 2.0 },
  { term: "OC", category: "drug", boost_weight: 1.5 },
  { term: "LEP", category: "drug", boost_weight: 1.5 },
  { term: "マーベロン", category: "drug", boost_weight: 2.0 },
  { term: "トリキュラー", category: "drug", boost_weight: 2.0 },
  { term: "ファボワール", category: "drug", boost_weight: 2.0 },
  { term: "ラベルフィーユ", category: "drug", boost_weight: 2.0 },
  { term: "アンジュ", category: "drug", boost_weight: 2.0 },
  { term: "ヤーズ", category: "drug", boost_weight: 2.0 },
  { term: "ヤーズフレックス", category: "drug", boost_weight: 2.0 },
  { term: "フリウェル", category: "drug", boost_weight: 2.0 },
  { term: "ドロスピレノン", category: "drug", boost_weight: 2.0 },
  { term: "ルナベル", category: "drug", boost_weight: 2.0 },
  { term: "ジェミーナ", category: "drug", boost_weight: 2.0 },
  { term: "アフターピル", category: "drug", boost_weight: 2.0 },
  { term: "緊急避妊薬", reading: "きんきゅうひにんやく", category: "drug", boost_weight: 2.0 },
  { term: "ノルレボ", category: "drug", boost_weight: 2.0 },
  { term: "エラワン", category: "drug", boost_weight: 2.0 },
  { term: "月経困難症", reading: "げっけいこんなんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "PMS", category: "symptom", boost_weight: 2.0 },
  { term: "月経前症候群", reading: "げっけいぜんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "不正出血", reading: "ふせいしゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "生理痛", reading: "せいりつう", category: "symptom", boost_weight: 1.5 },
  { term: "子宮内膜症", reading: "しきゅうないまくしょう", category: "symptom", boost_weight: 2.0 },
  // 性感染症（オンライン診療で多い）
  { term: "性感染症", reading: "せいかんせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "STI", category: "symptom", boost_weight: 2.0 },
  { term: "STD", category: "symptom", boost_weight: 2.0 },
  { term: "クラミジア", category: "symptom", boost_weight: 2.0 },
  { term: "淋病", reading: "りんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "梅毒", reading: "ばいどく", category: "symptom", boost_weight: 2.0 },
  { term: "ヘルペス", category: "symptom", boost_weight: 2.0 },
  { term: "性器ヘルペス", reading: "せいきへるぺす", category: "symptom", boost_weight: 2.0 },
  { term: "尖圭コンジローマ", reading: "せんけいこんじろーま", category: "symptom", boost_weight: 2.0 },
  { term: "カンジダ", category: "symptom", boost_weight: 2.0 },
  { term: "バラシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "バルトレックス", category: "drug", boost_weight: 2.0 },
  // 美白・アンチエイジング
  { term: "美白", reading: "びはく", category: "general", boost_weight: 1.5 },
  { term: "アンチエイジング", category: "general", boost_weight: 1.5 },
  { term: "エイジングケア", category: "general", boost_weight: 1.0 },
  { term: "シナール", category: "drug", boost_weight: 1.5 },
  { term: "ユベラ", category: "drug", boost_weight: 1.5 },
  { term: "ハイチオール", category: "drug", boost_weight: 1.5 },
  { term: "Lシステイン", category: "drug", boost_weight: 1.5 },
  { term: "ビオチン", category: "drug", boost_weight: 1.5 },
  // まつげ
  { term: "まつ毛貧毛症", reading: "まつげひんもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "ビマトプロスト", category: "drug", boost_weight: 2.0 },
  { term: "グラッシュビスタ", category: "drug", boost_weight: 2.0 },
  { term: "ルミガン", category: "drug", boost_weight: 2.0 },
];

// ================================================================
// 内科
// ================================================================
const INTERNAL: VocabEntry[] = [
  // 糖尿病
  { term: "糖尿病", reading: "とうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "1型糖尿病", reading: "いちがたとうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "2型糖尿病", reading: "にがたとうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "HbA1c", category: "lab", boost_weight: 2.0 },
  { term: "血糖値", reading: "けっとうち", category: "lab", boost_weight: 1.5 },
  { term: "空腹時血糖", reading: "くうふくじけっとう", category: "lab", boost_weight: 1.5 },
  { term: "食後血糖", reading: "しょくごけっとう", category: "lab", boost_weight: 1.5 },
  { term: "インスリン", category: "drug", boost_weight: 2.0 },
  { term: "インスリン抵抗性", reading: "いんすりんていこうせい", category: "symptom", boost_weight: 1.5 },
  { term: "メトホルミン", category: "drug", boost_weight: 2.0 },
  { term: "メトグルコ", category: "drug", boost_weight: 2.0 },
  { term: "SGLT2阻害薬", reading: "えすじーえるてぃーつーそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "フォシーガ", category: "drug", boost_weight: 2.0 },
  { term: "ジャディアンス", category: "drug", boost_weight: 2.0 },
  { term: "DPP-4阻害薬", reading: "でぃーぴーぴーよんそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "ジャヌビア", category: "drug", boost_weight: 2.0 },
  { term: "エクア", category: "drug", boost_weight: 2.0 },
  { term: "トラゼンタ", category: "drug", boost_weight: 2.0 },
  { term: "SU剤", reading: "えすゆーざい", category: "drug", boost_weight: 1.5 },
  { term: "グリメピリド", category: "drug", boost_weight: 2.0 },
  { term: "α-グルコシダーゼ阻害薬", category: "drug", boost_weight: 1.5 },
  { term: "ボグリボース", category: "drug", boost_weight: 2.0 },
  { term: "糖尿病性腎症", reading: "とうにょうびょうせいじんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "糖尿病性網膜症", reading: "とうにょうびょうせいもうまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "糖尿病性神経障害", reading: "とうにょうびょうせいしんけいしょうがい", category: "symptom", boost_weight: 2.0 },
  // 高血圧
  { term: "高血圧", reading: "こうけつあつ", category: "symptom", boost_weight: 2.0 },
  { term: "本態性高血圧", reading: "ほんたいせいこうけつあつ", category: "symptom", boost_weight: 2.0 },
  { term: "降圧薬", reading: "こうあつやく", category: "drug", boost_weight: 1.5 },
  { term: "ARB", category: "drug", boost_weight: 2.0 },
  { term: "ACE阻害薬", reading: "えーすそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "Ca拮抗薬", reading: "かるしうむきっこうやく", category: "drug", boost_weight: 2.0 },
  { term: "アムロジピン", category: "drug", boost_weight: 2.0 },
  { term: "ノルバスク", category: "drug", boost_weight: 2.0 },
  { term: "オルメサルタン", category: "drug", boost_weight: 2.0 },
  { term: "オルメテック", category: "drug", boost_weight: 2.0 },
  { term: "テルミサルタン", category: "drug", boost_weight: 2.0 },
  { term: "ミカルディス", category: "drug", boost_weight: 2.0 },
  { term: "バルサルタン", category: "drug", boost_weight: 2.0 },
  { term: "ニフェジピン", category: "drug", boost_weight: 2.0 },
  { term: "利尿薬", reading: "りにょうやく", category: "drug", boost_weight: 1.5 },
  { term: "β遮断薬", reading: "べーたしゃだんやく", category: "drug", boost_weight: 2.0 },
  { term: "ビソプロロール", category: "drug", boost_weight: 2.0 },
  // 脂質異常
  { term: "脂質異常症", reading: "ししついじょうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "高脂血症", reading: "こうしけっしょう", category: "symptom", boost_weight: 2.0 },
  { term: "LDLコレステロール", category: "lab", boost_weight: 2.0 },
  { term: "HDLコレステロール", category: "lab", boost_weight: 2.0 },
  { term: "中性脂肪", reading: "ちゅうせいしぼう", category: "lab", boost_weight: 1.5 },
  { term: "トリグリセリド", category: "lab", boost_weight: 1.5 },
  { term: "スタチン", category: "drug", boost_weight: 2.0 },
  { term: "ロスバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "クレストール", category: "drug", boost_weight: 2.0 },
  { term: "アトルバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "リピトール", category: "drug", boost_weight: 2.0 },
  { term: "プラバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "フィブラート", category: "drug", boost_weight: 1.5 },
  { term: "エゼチミブ", category: "drug", boost_weight: 2.0 },
  { term: "ゼチーア", category: "drug", boost_weight: 2.0 },
  { term: "動脈硬化", reading: "どうみゃくこうか", category: "symptom", boost_weight: 1.5 },
  // 消化器
  { term: "逆流性食道炎", reading: "ぎゃくりゅうせいしょくどうえん", category: "symptom", boost_weight: 2.0 },
  { term: "胃潰瘍", reading: "いかいよう", category: "symptom", boost_weight: 2.0 },
  { term: "十二指腸潰瘍", reading: "じゅうにしちょうかいよう", category: "symptom", boost_weight: 2.0 },
  { term: "機能性ディスペプシア", category: "symptom", boost_weight: 2.0 },
  { term: "過敏性腸症候群", reading: "かびんせいちょうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "IBS", category: "symptom", boost_weight: 2.0 },
  { term: "潰瘍性大腸炎", reading: "かいようせいだいちょうえん", category: "symptom", boost_weight: 2.0 },
  { term: "クローン病", reading: "くろーんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "脂肪肝", reading: "しぼうかん", category: "symptom", boost_weight: 1.5 },
  { term: "肝硬変", reading: "かんこうへん", category: "symptom", boost_weight: 2.0 },
  { term: "肝炎", reading: "かんえん", category: "symptom", boost_weight: 1.5 },
  { term: "B型肝炎", reading: "びーがたかんえん", category: "symptom", boost_weight: 2.0 },
  { term: "C型肝炎", reading: "しーがたかんえん", category: "symptom", boost_weight: 2.0 },
  { term: "膵炎", reading: "すいえん", category: "symptom", boost_weight: 2.0 },
  { term: "胆石", reading: "たんせき", category: "symptom", boost_weight: 1.5 },
  { term: "PPI", category: "drug", boost_weight: 2.0 },
  { term: "ランソプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "タケプロン", category: "drug", boost_weight: 2.0 },
  { term: "エソメプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "ネキシウム", category: "drug", boost_weight: 2.0 },
  { term: "ラベプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "パリエット", category: "drug", boost_weight: 2.0 },
  { term: "ボノプラザン", category: "drug", boost_weight: 2.0 },
  { term: "タケキャブ", category: "drug", boost_weight: 2.0 },
  { term: "H2ブロッカー", category: "drug", boost_weight: 1.5 },
  { term: "ファモチジン", category: "drug", boost_weight: 2.0 },
  { term: "ヘリコバクターピロリ", category: "symptom", boost_weight: 2.0 },
  { term: "ピロリ菌", reading: "ぴろりきん", category: "symptom", boost_weight: 1.5 },
  { term: "除菌", reading: "じょきん", category: "procedure", boost_weight: 1.5 },
  { term: "胃カメラ", reading: "いかめら", category: "procedure", boost_weight: 1.5 },
  { term: "上部消化管内視鏡", reading: "じょうぶしょうかかんないしきょう", category: "procedure", boost_weight: 2.0 },
  { term: "大腸カメラ", reading: "だいちょうかめら", category: "procedure", boost_weight: 1.5 },
  { term: "下部消化管内視鏡", reading: "かぶしょうかかんないしきょう", category: "procedure", boost_weight: 2.0 },
  { term: "腹部エコー", reading: "ふくぶえこー", category: "procedure", boost_weight: 1.5 },
  // 呼吸器
  { term: "喘息", reading: "ぜんそく", category: "symptom", boost_weight: 2.0 },
  { term: "気管支喘息", reading: "きかんしぜんそく", category: "symptom", boost_weight: 2.0 },
  { term: "COPD", category: "symptom", boost_weight: 2.0 },
  { term: "慢性閉塞性肺疾患", reading: "まんせいへいそくせいはいしっかん", category: "symptom", boost_weight: 2.0 },
  { term: "肺炎", reading: "はいえん", category: "symptom", boost_weight: 2.0 },
  { term: "間質性肺炎", reading: "かんしつせいはいえん", category: "symptom", boost_weight: 2.0 },
  { term: "気管支炎", reading: "きかんしえん", category: "symptom", boost_weight: 1.5 },
  { term: "肺気腫", reading: "はいきしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "睡眠時無呼吸症候群", reading: "すいみんじむこきゅうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "SAS", category: "symptom", boost_weight: 2.0 },
  { term: "CPAP", category: "procedure", boost_weight: 2.0 },
  { term: "吸入薬", reading: "きゅうにゅうやく", category: "drug", boost_weight: 1.5 },
  { term: "ICS", category: "drug", boost_weight: 1.5 },
  { term: "LABA", category: "drug", boost_weight: 1.5 },
  { term: "LAMA", category: "drug", boost_weight: 1.5 },
  { term: "モンテルカスト", category: "drug", boost_weight: 2.0 },
  { term: "シングレア", category: "drug", boost_weight: 2.0 },
  { term: "テオフィリン", category: "drug", boost_weight: 2.0 },
  // 循環器
  { term: "心電図", reading: "しんでんず", category: "procedure", boost_weight: 1.5 },
  { term: "心エコー", reading: "しんえこー", category: "procedure", boost_weight: 1.5 },
  { term: "ホルター心電図", reading: "ほるたーしんでんず", category: "procedure", boost_weight: 2.0 },
  { term: "心房細動", reading: "しんぼうさいどう", category: "symptom", boost_weight: 2.0 },
  { term: "Af", category: "symptom", boost_weight: 2.0 },
  { term: "不整脈", reading: "ふせいみゃく", category: "symptom", boost_weight: 1.5 },
  { term: "心不全", reading: "しんふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "狭心症", reading: "きょうしんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "心筋梗塞", reading: "しんきんこうそく", category: "symptom", boost_weight: 2.0 },
  { term: "弁膜症", reading: "べんまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "大動脈瘤", reading: "だいどうみゃくりゅう", category: "symptom", boost_weight: 2.0 },
  { term: "深部静脈血栓症", reading: "しんぶじょうみゃくけっせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "DVT", category: "symptom", boost_weight: 2.0 },
  { term: "肺塞栓", reading: "はいそくせん", category: "symptom", boost_weight: 2.0 },
  { term: "ワーファリン", category: "drug", boost_weight: 2.0 },
  { term: "DOAC", category: "drug", boost_weight: 2.0 },
  { term: "エドキサバン", category: "drug", boost_weight: 2.0 },
  { term: "リクシアナ", category: "drug", boost_weight: 2.0 },
  { term: "アピキサバン", category: "drug", boost_weight: 2.0 },
  { term: "エリキュース", category: "drug", boost_weight: 2.0 },
  { term: "リバーロキサバン", category: "drug", boost_weight: 2.0 },
  { term: "イグザレルト", category: "drug", boost_weight: 2.0 },
  { term: "BNP", category: "lab", boost_weight: 2.0 },
  { term: "NT-proBNP", category: "lab", boost_weight: 2.0 },
  { term: "トロポニン", category: "lab", boost_weight: 2.0 },
  { term: "Dダイマー", category: "lab", boost_weight: 2.0 },
  // 腎臓
  { term: "慢性腎臓病", reading: "まんせいじんぞうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "CKD", category: "symptom", boost_weight: 2.0 },
  { term: "腎不全", reading: "じんふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "透析", reading: "とうせき", category: "procedure", boost_weight: 2.0 },
  { term: "ネフローゼ症候群", category: "symptom", boost_weight: 2.0 },
  { term: "蛋白尿", reading: "たんぱくにょう", category: "lab", boost_weight: 1.5 },
  { term: "血尿", reading: "けつにょう", category: "lab", boost_weight: 1.5 },
  // 内分泌
  { term: "甲状腺", reading: "こうじょうせん", category: "anatomy", boost_weight: 1.5 },
  { term: "甲状腺機能亢進症", reading: "こうじょうせんきのうこうしんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "バセドウ病", reading: "ばせどうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "甲状腺機能低下症", reading: "こうじょうせんきのうていかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "橋本病", reading: "はしもとびょう", category: "symptom", boost_weight: 2.0 },
  { term: "チラーヂン", category: "drug", boost_weight: 2.0 },
  { term: "レボチロキシン", category: "drug", boost_weight: 2.0 },
  { term: "痛風", reading: "つうふう", category: "symptom", boost_weight: 2.0 },
  { term: "高尿酸血症", reading: "こうにょうさんけっしょう", category: "symptom", boost_weight: 2.0 },
  { term: "フェブキソスタット", category: "drug", boost_weight: 2.0 },
  { term: "フェブリク", category: "drug", boost_weight: 2.0 },
  { term: "アロプリノール", category: "drug", boost_weight: 2.0 },
  { term: "コルヒチン", category: "drug", boost_weight: 2.0 },
  // 感染症
  { term: "インフルエンザ", category: "symptom", boost_weight: 1.5 },
  { term: "タミフル", category: "drug", boost_weight: 2.0 },
  { term: "オセルタミビル", category: "drug", boost_weight: 2.0 },
  { term: "新型コロナ", reading: "しんがたころな", category: "symptom", boost_weight: 1.5 },
  { term: "COVID-19", category: "symptom", boost_weight: 1.5 },
  { term: "ラゲブリオ", category: "drug", boost_weight: 2.0 },
  { term: "ゾコーバ", category: "drug", boost_weight: 2.0 },
  { term: "ワクチン", category: "drug", boost_weight: 1.0 },
  { term: "尿路感染症", reading: "にょうろかんせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "膀胱炎", reading: "ぼうこうえん", category: "symptom", boost_weight: 1.5 },
  { term: "腎盂腎炎", reading: "じんうじんえん", category: "symptom", boost_weight: 2.0 },
  // 抗菌薬
  { term: "アモキシシリン", category: "drug", boost_weight: 2.0 },
  { term: "サワシリン", category: "drug", boost_weight: 2.0 },
  { term: "クラリスロマイシン", category: "drug", boost_weight: 2.0 },
  { term: "クラリス", category: "drug", boost_weight: 2.0 },
  { term: "アジスロマイシン", category: "drug", boost_weight: 2.0 },
  { term: "ジスロマック", category: "drug", boost_weight: 2.0 },
  { term: "セフカペンピボキシル", category: "drug", boost_weight: 2.0 },
  { term: "フロモックス", category: "drug", boost_weight: 2.0 },
  { term: "レボフロキサシン", category: "drug", boost_weight: 2.0 },
  { term: "クラビット", category: "drug", boost_weight: 2.0 },
  // 神経
  { term: "脳梗塞", reading: "のうこうそく", category: "symptom", boost_weight: 2.0 },
  { term: "脳出血", reading: "のうしゅっけつ", category: "symptom", boost_weight: 2.0 },
  { term: "くも膜下出血", reading: "くもまくかしゅっけつ", category: "symptom", boost_weight: 2.0 },
  { term: "パーキンソン病", category: "symptom", boost_weight: 2.0 },
  { term: "てんかん", category: "symptom", boost_weight: 2.0 },
  { term: "認知症", reading: "にんちしょう", category: "symptom", boost_weight: 2.0 },
  { term: "アルツハイマー", category: "symptom", boost_weight: 2.0 },
  { term: "片頭痛", reading: "へんずつう", category: "symptom", boost_weight: 1.5 },
  { term: "トリプタン", category: "drug", boost_weight: 2.0 },
  // アレルギー
  { term: "花粉症", reading: "かふんしょう", category: "symptom", boost_weight: 1.5 },
  { term: "アレルギー性鼻炎", reading: "あれるぎーせいびえん", category: "symptom", boost_weight: 2.0 },
  { term: "抗アレルギー薬", reading: "こうあれるぎーやく", category: "drug", boost_weight: 1.5 },
  { term: "フェキソフェナジン", category: "drug", boost_weight: 2.0 },
  { term: "ビラノア", category: "drug", boost_weight: 2.0 },
  { term: "デザレックス", category: "drug", boost_weight: 2.0 },
  { term: "ルパフィン", category: "drug", boost_weight: 2.0 },
  { term: "モンテルカスト", category: "drug", boost_weight: 2.0 },
  // 精神科（オンライン診療で多い）
  { term: "不眠症", reading: "ふみんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "不眠", reading: "ふみん", category: "symptom", boost_weight: 1.5 },
  { term: "睡眠障害", reading: "すいみんしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "うつ病", reading: "うつびょう", category: "symptom", boost_weight: 2.0 },
  { term: "適応障害", reading: "てきおうしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "不安障害", reading: "ふあんしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "パニック障害", reading: "ぱにっくしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "SSRI", category: "drug", boost_weight: 2.0 },
  { term: "SNRI", category: "drug", boost_weight: 2.0 },
  { term: "レクサプロ", category: "drug", boost_weight: 2.0 },
  { term: "エスシタロプラム", category: "drug", boost_weight: 2.0 },
  { term: "サインバルタ", category: "drug", boost_weight: 2.0 },
  { term: "デュロキセチン", category: "drug", boost_weight: 2.0 },
  { term: "ベンゾジアゼピン", category: "drug", boost_weight: 2.0 },
  { term: "デパス", category: "drug", boost_weight: 2.0 },
  { term: "エチゾラム", category: "drug", boost_weight: 2.0 },
  { term: "マイスリー", category: "drug", boost_weight: 2.0 },
  { term: "ゾルピデム", category: "drug", boost_weight: 2.0 },
  { term: "ルネスタ", category: "drug", boost_weight: 2.0 },
  { term: "デエビゴ", category: "drug", boost_weight: 2.0 },
  { term: "レンボレキサント", category: "drug", boost_weight: 2.0 },
  { term: "ベルソムラ", category: "drug", boost_weight: 2.0 },
  { term: "スボレキサント", category: "drug", boost_weight: 2.0 },
  // 検査値
  { term: "AST", category: "lab", boost_weight: 1.5 },
  { term: "ALT", category: "lab", boost_weight: 1.5 },
  { term: "γ-GTP", category: "lab", boost_weight: 1.5 },
  { term: "ALP", category: "lab", boost_weight: 1.5 },
  { term: "LDH", category: "lab", boost_weight: 1.5 },
  { term: "総ビリルビン", reading: "そうびりるびん", category: "lab", boost_weight: 1.5 },
  { term: "アルブミン", category: "lab", boost_weight: 1.5 },
  { term: "総蛋白", reading: "そうたんぱく", category: "lab", boost_weight: 1.5 },
  { term: "クレアチニン", category: "lab", boost_weight: 1.5 },
  { term: "eGFR", category: "lab", boost_weight: 2.0 },
  { term: "BUN", category: "lab", boost_weight: 1.5 },
  { term: "CRP", category: "lab", boost_weight: 1.5 },
  { term: "赤沈", reading: "せきちん", category: "lab", boost_weight: 1.5 },
  { term: "白血球", reading: "はっけっきゅう", category: "lab", boost_weight: 1.5 },
  { term: "赤血球", reading: "せっけっきゅう", category: "lab", boost_weight: 1.5 },
  { term: "ヘモグロビン", category: "lab", boost_weight: 1.5 },
  { term: "ヘマトクリット", category: "lab", boost_weight: 1.5 },
  { term: "血小板", reading: "けっしょうばん", category: "lab", boost_weight: 1.5 },
  { term: "MCV", category: "lab", boost_weight: 1.5 },
  { term: "MCH", category: "lab", boost_weight: 1.5 },
  { term: "好中球", reading: "こうちゅうきゅう", category: "lab", boost_weight: 1.5 },
  { term: "リンパ球", reading: "りんぱきゅう", category: "lab", boost_weight: 1.5 },
  { term: "尿酸", reading: "にょうさん", category: "lab", boost_weight: 1.5 },
  { term: "TSH", category: "lab", boost_weight: 2.0 },
  { term: "FT3", category: "lab", boost_weight: 1.5 },
  { term: "FT4", category: "lab", boost_weight: 1.5 },
  { term: "Na", category: "lab", boost_weight: 1.0 },
  { term: "K", category: "lab", boost_weight: 1.0 },
  { term: "Cl", category: "lab", boost_weight: 1.0 },
  { term: "Ca", category: "lab", boost_weight: 1.0 },
  { term: "Fe", category: "lab", boost_weight: 1.0 },
  { term: "フェリチン", category: "lab", boost_weight: 1.5 },
  { term: "TIBC", category: "lab", boost_weight: 1.5 },
  { term: "血清鉄", reading: "けっせいてつ", category: "lab", boost_weight: 1.5 },
  { term: "PT-INR", category: "lab", boost_weight: 2.0 },
  { term: "APTT", category: "lab", boost_weight: 1.5 },
  { term: "フィブリノーゲン", category: "lab", boost_weight: 1.5 },
  { term: "HBs抗原", reading: "えいちびーえすこうげん", category: "lab", boost_weight: 2.0 },
  { term: "HCV抗体", reading: "えいちしーぶいこうたい", category: "lab", boost_weight: 2.0 },
  { term: "CEA", category: "lab", boost_weight: 1.5 },
  { term: "CA19-9", category: "lab", boost_weight: 1.5 },
  { term: "PSA", category: "lab", boost_weight: 2.0 },
  { term: "AFP", category: "lab", boost_weight: 1.5 },
  { term: "尿検査", reading: "にょうけんさ", category: "procedure", boost_weight: 1.0 },
  { term: "血液検査", reading: "けつえきけんさ", category: "procedure", boost_weight: 1.0 },
  { term: "生化学検査", reading: "せいかがくけんさ", category: "procedure", boost_weight: 1.5 },
  { term: "血液ガス", reading: "けつえきがす", category: "procedure", boost_weight: 1.5 },
  // 貧血
  { term: "貧血", reading: "ひんけつ", category: "symptom", boost_weight: 1.5 },
  { term: "鉄欠乏性貧血", reading: "てつけつぼうせいひんけつ", category: "symptom", boost_weight: 2.0 },
  { term: "鉄剤", reading: "てつざい", category: "drug", boost_weight: 1.5 },
  { term: "フェロミア", category: "drug", boost_weight: 2.0 },
];

// ================================================================
// 外科
// ================================================================
const SURGERY: VocabEntry[] = [
  // 基本手技
  { term: "縫合", reading: "ほうごう", category: "procedure", boost_weight: 2.0 },
  { term: "切開", reading: "せっかい", category: "procedure", boost_weight: 1.5 },
  { term: "切除", reading: "せつじょ", category: "procedure", boost_weight: 1.5 },
  { term: "郭清", reading: "かくせい", category: "procedure", boost_weight: 2.0 },
  { term: "吻合", reading: "ふんごう", category: "procedure", boost_weight: 2.0 },
  { term: "ドレーン", category: "procedure", boost_weight: 2.0 },
  { term: "デブリードマン", category: "procedure", boost_weight: 2.0 },
  { term: "ドレナージ", category: "procedure", boost_weight: 2.0 },
  { term: "穿刺", reading: "せんし", category: "procedure", boost_weight: 2.0 },
  { term: "クランプ", category: "procedure", boost_weight: 1.5 },
  { term: "結紮", reading: "けっさつ", category: "procedure", boost_weight: 2.0 },
  // 麻酔
  { term: "局所麻酔", reading: "きょくしょますい", category: "procedure", boost_weight: 1.5 },
  { term: "全身麻酔", reading: "ぜんしんますい", category: "procedure", boost_weight: 1.5 },
  { term: "腰椎麻酔", reading: "ようついますい", category: "procedure", boost_weight: 1.5 },
  { term: "硬膜外麻酔", reading: "こうまくがいますい", category: "procedure", boost_weight: 2.0 },
  { term: "静脈麻酔", reading: "じょうみゃくますい", category: "procedure", boost_weight: 1.5 },
  { term: "伝達麻酔", reading: "でんたつますい", category: "procedure", boost_weight: 1.5 },
  { term: "挿管", reading: "そうかん", category: "procedure", boost_weight: 1.5 },
  { term: "気管挿管", reading: "きかんそうかん", category: "procedure", boost_weight: 2.0 },
  { term: "キシロカイン", category: "drug", boost_weight: 2.0 },
  { term: "リドカイン", category: "drug", boost_weight: 2.0 },
  { term: "プロポフォール", category: "drug", boost_weight: 2.0 },
  { term: "セボフルラン", category: "drug", boost_weight: 2.0 },
  // 創傷
  { term: "創部", reading: "そうぶ", category: "anatomy", boost_weight: 1.5 },
  { term: "創傷", reading: "そうしょう", category: "symptom", boost_weight: 1.5 },
  { term: "瘢痕", reading: "はんこん", category: "symptom", boost_weight: 2.0 },
  { term: "ケロイド", category: "symptom", boost_weight: 2.0 },
  { term: "膿瘍", reading: "のうよう", category: "symptom", boost_weight: 2.0 },
  { term: "蜂窩織炎", reading: "ほうかしきえん", category: "symptom", boost_weight: 2.0 },
  { term: "壊疽", reading: "えそ", category: "symptom", boost_weight: 2.0 },
  { term: "褥瘡", reading: "じょくそう", category: "symptom", boost_weight: 2.0 },
  { term: "肉芽", reading: "にくげ", category: "symptom", boost_weight: 1.5 },
  // 検査
  { term: "CT", category: "procedure", boost_weight: 1.5 },
  { term: "造影CT", reading: "ぞうえいしーてぃー", category: "procedure", boost_weight: 2.0 },
  { term: "エコー", category: "procedure", boost_weight: 1.5 },
  { term: "生検", reading: "せいけん", category: "procedure", boost_weight: 2.0 },
  { term: "病理", reading: "びょうり", category: "procedure", boost_weight: 1.5 },
  { term: "迅速病理", reading: "じんそくびょうり", category: "procedure", boost_weight: 2.0 },
  { term: "PET-CT", category: "procedure", boost_weight: 2.0 },
  // 周術期
  { term: "術前", reading: "じゅつぜん", category: "general", boost_weight: 1.0 },
  { term: "術後", reading: "じゅつご", category: "general", boost_weight: 1.0 },
  { term: "術中", reading: "じゅつちゅう", category: "general", boost_weight: 1.0 },
  { term: "周術期", reading: "しゅうじゅつき", category: "general", boost_weight: 1.5 },
  { term: "抜糸", reading: "ばっし", category: "procedure", boost_weight: 1.5 },
  { term: "消毒", reading: "しょうどく", category: "procedure", boost_weight: 1.0 },
  { term: "ガーゼ", category: "general", boost_weight: 1.0 },
  { term: "止血", reading: "しけつ", category: "procedure", boost_weight: 1.5 },
  { term: "バイポーラ", category: "procedure", boost_weight: 1.5 },
  { term: "術後感染", reading: "じゅつごかんせん", category: "symptom", boost_weight: 1.5 },
  { term: "SSI", category: "symptom", boost_weight: 2.0 },
  { term: "DVT予防", reading: "でぃーぶいてぃーよぼう", category: "procedure", boost_weight: 1.5 },
  { term: "抗凝固", reading: "こうぎょうこ", category: "drug", boost_weight: 1.5 },
  // 術式
  { term: "腹腔鏡", reading: "ふくくうきょう", category: "procedure", boost_weight: 2.0 },
  { term: "腹腔鏡下手術", reading: "ふくくうきょうかしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "開腹", reading: "かいふく", category: "procedure", boost_weight: 1.5 },
  { term: "開腹手術", reading: "かいふくしゅじゅつ", category: "procedure", boost_weight: 1.5 },
  { term: "ロボット支援", reading: "ろぼっとしえん", category: "procedure", boost_weight: 1.5 },
  { term: "ダヴィンチ", category: "procedure", boost_weight: 2.0 },
  // 疾患
  { term: "虫垂炎", reading: "ちゅうすいえん", category: "symptom", boost_weight: 2.0 },
  { term: "ヘルニア", category: "symptom", boost_weight: 2.0 },
  { term: "鼠径ヘルニア", reading: "そけいへるにあ", category: "symptom", boost_weight: 2.0 },
  { term: "胆嚢摘出", reading: "たんのうてきしゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "胆嚢炎", reading: "たんのうえん", category: "symptom", boost_weight: 2.0 },
  { term: "腸閉塞", reading: "ちょうへいそく", category: "symptom", boost_weight: 2.0 },
  { term: "イレウス", category: "symptom", boost_weight: 2.0 },
  { term: "腹膜炎", reading: "ふくまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "消化管穿孔", reading: "しょうかかんせんこう", category: "symptom", boost_weight: 2.0 },
  { term: "大腸癌", reading: "だいちょうがん", category: "symptom", boost_weight: 2.0 },
  { term: "胃癌", reading: "いがん", category: "symptom", boost_weight: 2.0 },
  { term: "乳癌", reading: "にゅうがん", category: "symptom", boost_weight: 2.0 },
  { term: "肺癌", reading: "はいがん", category: "symptom", boost_weight: 2.0 },
  { term: "甲状腺癌", reading: "こうじょうせんがん", category: "symptom", boost_weight: 2.0 },
  { term: "リンパ節", reading: "りんぱせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "転移", reading: "てんい", category: "symptom", boost_weight: 1.5 },
  { term: "良性", reading: "りょうせい", category: "general", boost_weight: 1.0 },
  { term: "悪性", reading: "あくせい", category: "general", boost_weight: 1.0 },
  { term: "腫瘍", reading: "しゅよう", category: "symptom", boost_weight: 1.5 },
  { term: "ステージ", category: "general", boost_weight: 1.0 },
  { term: "TNM分類", category: "general", boost_weight: 1.5 },
];

// ================================================================
// 整形外科
// ================================================================
const ORTHOPEDICS: VocabEntry[] = [
  // 検査
  { term: "MRI", category: "procedure", boost_weight: 2.0 },
  { term: "レントゲン", category: "procedure", boost_weight: 1.5 },
  { term: "X線", reading: "えっくすせん", category: "procedure", boost_weight: 1.5 },
  { term: "骨密度", reading: "こつみつど", category: "lab", boost_weight: 2.0 },
  { term: "DEXA", category: "procedure", boost_weight: 2.0 },
  { term: "骨シンチ", reading: "こつしんち", category: "procedure", boost_weight: 2.0 },
  { term: "関節造影", reading: "かんせつぞうえい", category: "procedure", boost_weight: 1.5 },
  // 疾患
  { term: "骨折", reading: "こっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "圧迫骨折", reading: "あっぱくこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "疲労骨折", reading: "ひろうこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "捻挫", reading: "ねんざ", category: "symptom", boost_weight: 1.5 },
  { term: "脱臼", reading: "だっきゅう", category: "symptom", boost_weight: 2.0 },
  { term: "靭帯損傷", reading: "じんたいそんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "半月板損傷", reading: "はんげつばんそんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "半月板", reading: "はんげつばん", category: "anatomy", boost_weight: 2.0 },
  { term: "椎間板ヘルニア", reading: "ついかんばんへるにあ", category: "symptom", boost_weight: 2.0 },
  { term: "脊柱管狭窄症", reading: "せきちゅうかんきょうさくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "すべり症", reading: "すべりしょう", category: "symptom", boost_weight: 1.5 },
  { term: "分離症", reading: "ぶんりしょう", category: "symptom", boost_weight: 1.5 },
  { term: "側弯症", reading: "そくわんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性膝関節症", reading: "へんけいせいしつかんせつしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性股関節症", reading: "へんけいせいこかんせつしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性脊椎症", reading: "へんけいせいせきついしょう", category: "symptom", boost_weight: 2.0 },
  { term: "腱鞘炎", reading: "けんしょうえん", category: "symptom", boost_weight: 2.0 },
  { term: "ばね指", reading: "ばねゆび", category: "symptom", boost_weight: 1.5 },
  { term: "手根管症候群", reading: "しゅこんかんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "肘部管症候群", reading: "ちゅうぶかんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "骨粗鬆症", reading: "こつそしょうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "五十肩", reading: "ごじゅうかた", category: "symptom", boost_weight: 1.5 },
  { term: "肩関節周囲炎", reading: "かたかんせつしゅういえん", category: "symptom", boost_weight: 2.0 },
  { term: "腱板断裂", reading: "けんばんだんれつ", category: "symptom", boost_weight: 2.0 },
  { term: "テニス肘", reading: "てにすひじ", category: "symptom", boost_weight: 1.5 },
  { term: "外側上顆炎", reading: "がいそくじょうかえん", category: "symptom", boost_weight: 2.0 },
  { term: "足底腱膜炎", reading: "そくていけんまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "坐骨神経痛", reading: "ざこつしんけいつう", category: "symptom", boost_weight: 2.0 },
  { term: "頸椎症", reading: "けいついしょう", category: "symptom", boost_weight: 2.0 },
  { term: "関節リウマチ", reading: "かんせつりうまち", category: "symptom", boost_weight: 2.0 },
  { term: "痛風性関節炎", reading: "つうふうせいかんせつえん", category: "symptom", boost_weight: 2.0 },
  { term: "偽痛風", reading: "ぎつうふう", category: "symptom", boost_weight: 2.0 },
  { term: "大腿骨頸部骨折", reading: "だいたいこつけいぶこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "橈骨遠位端骨折", reading: "とうこつえんいたんこっせつ", category: "symptom", boost_weight: 2.0 },
  // 処置
  { term: "関節鏡", reading: "かんせつきょう", category: "procedure", boost_weight: 2.0 },
  { term: "人工関節", reading: "じんこうかんせつ", category: "procedure", boost_weight: 2.0 },
  { term: "TKA", category: "procedure", boost_weight: 2.0 },
  { term: "THA", category: "procedure", boost_weight: 2.0 },
  { term: "骨接合術", reading: "こつせつごうじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "プレート固定", reading: "ぷれーとこてい", category: "procedure", boost_weight: 1.5 },
  { term: "髄内釘", reading: "ずいないてい", category: "procedure", boost_weight: 2.0 },
  { term: "ギプス", category: "procedure", boost_weight: 1.5 },
  { term: "シーネ", category: "procedure", boost_weight: 1.5 },
  { term: "装具", reading: "そうぐ", category: "procedure", boost_weight: 1.5 },
  { term: "リハビリ", category: "procedure", boost_weight: 1.5 },
  { term: "リハビリテーション", category: "procedure", boost_weight: 1.5 },
  { term: "理学療法", reading: "りがくりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "作業療法", reading: "さぎょうりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "関節注射", reading: "かんせつちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ヒアルロン酸注射", reading: "ひあるろんさんちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "トリガーポイント", category: "procedure", boost_weight: 1.5 },
  { term: "ブロック注射", reading: "ぶろっくちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "神経根ブロック", reading: "しんけいこんぶろっく", category: "procedure", boost_weight: 2.0 },
  { term: "硬膜外ブロック", reading: "こうまくがいぶろっく", category: "procedure", boost_weight: 2.0 },
  { term: "牽引", reading: "けんいん", category: "procedure", boost_weight: 1.5 },
  // 薬剤
  { term: "ロキソニン", category: "drug", boost_weight: 2.0 },
  { term: "ロキソプロフェン", category: "drug", boost_weight: 2.0 },
  { term: "セレコキシブ", category: "drug", boost_weight: 2.0 },
  { term: "セレコックス", category: "drug", boost_weight: 2.0 },
  { term: "NSAIDs", category: "drug", boost_weight: 2.0 },
  { term: "プレガバリン", category: "drug", boost_weight: 2.0 },
  { term: "リリカ", category: "drug", boost_weight: 2.0 },
  { term: "ミロガバリン", category: "drug", boost_weight: 2.0 },
  { term: "タリージェ", category: "drug", boost_weight: 2.0 },
  { term: "トラマドール", category: "drug", boost_weight: 2.0 },
  { term: "トラムセット", category: "drug", boost_weight: 2.0 },
  { term: "デュロテップ", category: "drug", boost_weight: 2.0 },
  { term: "ビスホスホネート", category: "drug", boost_weight: 2.0 },
  { term: "デノスマブ", category: "drug", boost_weight: 2.0 },
  { term: "プラリア", category: "drug", boost_weight: 2.0 },
  { term: "テリパラチド", category: "drug", boost_weight: 2.0 },
  { term: "フォルテオ", category: "drug", boost_weight: 2.0 },
  { term: "エルデカルシトール", category: "drug", boost_weight: 2.0 },
  { term: "エディロール", category: "drug", boost_weight: 2.0 },
  { term: "活性型ビタミンD", reading: "かっせいがたびたみんでぃー", category: "drug", boost_weight: 1.5 },
  { term: "ケナコルト", category: "drug", boost_weight: 2.0 },
  { term: "ステロイド注射", reading: "すてろいどちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "湿布", reading: "しっぷ", category: "drug", boost_weight: 1.0 },
  { term: "モーラステープ", category: "drug", boost_weight: 1.5 },
  { term: "ケトプロフェン", category: "drug", boost_weight: 1.5 },
  // 解剖
  { term: "頸椎", reading: "けいつい", category: "anatomy", boost_weight: 1.5 },
  { term: "胸椎", reading: "きょうつい", category: "anatomy", boost_weight: 1.5 },
  { term: "腰椎", reading: "ようつい", category: "anatomy", boost_weight: 1.5 },
  { term: "仙骨", reading: "せんこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "椎体", reading: "ついたい", category: "anatomy", boost_weight: 1.5 },
  { term: "椎間板", reading: "ついかんばん", category: "anatomy", boost_weight: 1.5 },
  { term: "脊髄", reading: "せきずい", category: "anatomy", boost_weight: 1.5 },
  { term: "馬尾", reading: "ばび", category: "anatomy", boost_weight: 2.0 },
  { term: "前十字靭帯", reading: "ぜんじゅうじじんたい", category: "anatomy", boost_weight: 2.0 },
  { term: "後十字靭帯", reading: "こうじゅうじじんたい", category: "anatomy", boost_weight: 2.0 },
  { term: "ACL", category: "anatomy", boost_weight: 2.0 },
  { term: "PCL", category: "anatomy", boost_weight: 2.0 },
  { term: "アキレス腱", reading: "あきれすけん", category: "anatomy", boost_weight: 1.5 },
  { term: "大腿骨", reading: "だいたいこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "脛骨", reading: "けいこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "腓骨", reading: "ひこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "橈骨", reading: "とうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "尺骨", reading: "しゃっこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "上腕骨", reading: "じょうわんこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "鎖骨", reading: "さこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "肩甲骨", reading: "けんこうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "骨盤", reading: "こつばん", category: "anatomy", boost_weight: 1.5 },
  { term: "肩関節", reading: "かたかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "肘関節", reading: "ひじかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "手関節", reading: "てかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "股関節", reading: "こかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "膝関節", reading: "しつかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "足関節", reading: "そくかんせつ", category: "anatomy", boost_weight: 1.5 },
];

// ================================================================
// 皮膚科
// ================================================================
const DERMATOLOGY: VocabEntry[] = [
  // 疾患
  { term: "アトピー性皮膚炎", reading: "あとぴーせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "湿疹", reading: "しっしん", category: "symptom", boost_weight: 1.5 },
  { term: "蕁麻疹", reading: "じんましん", category: "symptom", boost_weight: 2.0 },
  { term: "慢性蕁麻疹", reading: "まんせいじんましん", category: "symptom", boost_weight: 2.0 },
  { term: "帯状疱疹", reading: "たいじょうほうしん", category: "symptom", boost_weight: 2.0 },
  { term: "帯状疱疹後神経痛", reading: "たいじょうほうしんごしんけいつう", category: "symptom", boost_weight: 2.0 },
  { term: "白癬", reading: "はくせん", category: "symptom", boost_weight: 2.0 },
  { term: "水虫", reading: "みずむし", category: "symptom", boost_weight: 1.5 },
  { term: "爪白癬", reading: "つめはくせん", category: "symptom", boost_weight: 2.0 },
  { term: "カンジダ症", reading: "かんじだしょう", category: "symptom", boost_weight: 2.0 },
  { term: "乾癬", reading: "かんせん", category: "symptom", boost_weight: 2.0 },
  { term: "尋常性乾癬", reading: "じんじょうせいかんせん", category: "symptom", boost_weight: 2.0 },
  { term: "脂漏性皮膚炎", reading: "しろうせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "接触性皮膚炎", reading: "せっしょくせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "尋常性ざ瘡", reading: "じんじょうせいざそう", category: "symptom", boost_weight: 2.0 },
  { term: "酒さ", reading: "しゅさ", category: "symptom", boost_weight: 2.0 },
  { term: "円形脱毛症", reading: "えんけいだつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "粉瘤", reading: "ふんりゅう", category: "symptom", boost_weight: 2.0 },
  { term: "脂肪腫", reading: "しぼうしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "疣贅", reading: "ゆうぜい", category: "symptom", boost_weight: 2.0 },
  { term: "イボ", category: "symptom", boost_weight: 1.5 },
  { term: "ホクロ", category: "symptom", boost_weight: 1.5 },
  { term: "色素性母斑", reading: "しきそせいぼはん", category: "symptom", boost_weight: 2.0 },
  { term: "基底細胞癌", reading: "きていさいぼうがん", category: "symptom", boost_weight: 2.0 },
  { term: "悪性黒色腫", reading: "あくせいこくしょくしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "メラノーマ", category: "symptom", boost_weight: 2.0 },
  { term: "有棘細胞癌", reading: "ゆうきょくさいぼうがん", category: "symptom", boost_weight: 2.0 },
  { term: "ボーエン病", reading: "ぼーえんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "日光角化症", reading: "にっこうかくかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "多形滲出性紅斑", reading: "たけいしんしゅつせいこうはん", category: "symptom", boost_weight: 2.0 },
  { term: "薬疹", reading: "やくしん", category: "symptom", boost_weight: 2.0 },
  { term: "SJS", category: "symptom", boost_weight: 2.0 },
  { term: "天疱瘡", reading: "てんぽうそう", category: "symptom", boost_weight: 2.0 },
  { term: "類天疱瘡", reading: "るいてんぽうそう", category: "symptom", boost_weight: 2.0 },
  { term: "掌蹠膿疱症", reading: "しょうせきのうほうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "扁平苔癬", reading: "へんぺいたいせん", category: "symptom", boost_weight: 2.0 },
  { term: "紅斑", reading: "こうはん", category: "symptom", boost_weight: 1.5 },
  { term: "丘疹", reading: "きゅうしん", category: "symptom", boost_weight: 1.5 },
  { term: "水疱", reading: "すいほう", category: "symptom", boost_weight: 1.5 },
  { term: "膿疱", reading: "のうほう", category: "symptom", boost_weight: 1.5 },
  { term: "びらん", category: "symptom", boost_weight: 1.5 },
  { term: "潰瘍", reading: "かいよう", category: "symptom", boost_weight: 1.5 },
  { term: "鱗屑", reading: "りんせつ", category: "symptom", boost_weight: 1.5 },
  { term: "痂皮", reading: "かひ", category: "symptom", boost_weight: 1.5 },
  { term: "結節", reading: "けっせつ", category: "symptom", boost_weight: 1.5 },
  // 薬剤
  { term: "ステロイド外用", reading: "すてろいどがいよう", category: "drug", boost_weight: 2.0 },
  { term: "デルモベート", category: "drug", boost_weight: 2.0 },
  { term: "アンテベート", category: "drug", boost_weight: 2.0 },
  { term: "マイザー", category: "drug", boost_weight: 2.0 },
  { term: "リンデロン", category: "drug", boost_weight: 2.0 },
  { term: "ロコイド", category: "drug", boost_weight: 2.0 },
  { term: "キンダベート", category: "drug", boost_weight: 2.0 },
  { term: "プロトピック", category: "drug", boost_weight: 2.0 },
  { term: "タクロリムス", category: "drug", boost_weight: 2.0 },
  { term: "コレクチム", category: "drug", boost_weight: 2.0 },
  { term: "デルゴシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "モイゼルト", category: "drug", boost_weight: 2.0 },
  { term: "ジファミラスト", category: "drug", boost_weight: 2.0 },
  { term: "デュピクセント", category: "drug", boost_weight: 2.0 },
  { term: "デュピルマブ", category: "drug", boost_weight: 2.0 },
  { term: "ミチーガ", category: "drug", boost_weight: 2.0 },
  { term: "ネモリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "JAK阻害薬", reading: "じゃっくそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "オルミエント", category: "drug", boost_weight: 2.0 },
  { term: "バリシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "リンヴォック", category: "drug", boost_weight: 2.0 },
  { term: "ウパダシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "サイバインコ", category: "drug", boost_weight: 2.0 },
  { term: "アブロシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "ヒルドイド", category: "drug", boost_weight: 2.0 },
  { term: "ヘパリン類似物質", reading: "へぱりんるいじぶっしつ", category: "drug", boost_weight: 1.5 },
  { term: "保湿剤", reading: "ほしつざい", category: "drug", boost_weight: 1.0 },
  { term: "白色ワセリン", reading: "はくしょくわせりん", category: "drug", boost_weight: 1.0 },
  { term: "プロペト", category: "drug", boost_weight: 1.5 },
  { term: "抗ヒスタミン薬", reading: "こうひすたみんやく", category: "drug", boost_weight: 1.5 },
  { term: "アレグラ", category: "drug", boost_weight: 1.5 },
  { term: "ザイザル", category: "drug", boost_weight: 1.5 },
  { term: "クラリチン", category: "drug", boost_weight: 1.5 },
  { term: "ロラタジン", category: "drug", boost_weight: 1.5 },
  { term: "アシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "バラシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "アメナメビル", category: "drug", boost_weight: 2.0 },
  { term: "アメナリーフ", category: "drug", boost_weight: 2.0 },
  { term: "抗真菌薬", reading: "こうしんきんやく", category: "drug", boost_weight: 1.5 },
  { term: "テルビナフィン", category: "drug", boost_weight: 2.0 },
  { term: "ラミシール", category: "drug", boost_weight: 2.0 },
  { term: "イトラコナゾール", category: "drug", boost_weight: 2.0 },
  { term: "イトリゾール", category: "drug", boost_weight: 2.0 },
  { term: "ルコナック", category: "drug", boost_weight: 2.0 },
  { term: "クレナフィン", category: "drug", boost_weight: 2.0 },
  { term: "ディフェリン", category: "drug", boost_weight: 2.0 },
  { term: "アダパレン", category: "drug", boost_weight: 2.0 },
  { term: "ベピオ", category: "drug", boost_weight: 2.0 },
  { term: "過酸化ベンゾイル", reading: "かさんかべんぞいる", category: "drug", boost_weight: 2.0 },
  { term: "エピデュオ", category: "drug", boost_weight: 2.0 },
  { term: "デュアック", category: "drug", boost_weight: 2.0 },
  { term: "イソトレチノイン", category: "drug", boost_weight: 2.0 },
  { term: "オテズラ", category: "drug", boost_weight: 2.0 },
  { term: "アプレミラスト", category: "drug", boost_weight: 2.0 },
  // 処置
  { term: "光線療法", reading: "こうせんりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "ナローバンドUVB", category: "procedure", boost_weight: 2.0 },
  { term: "エキシマレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "PUVA", category: "procedure", boost_weight: 2.0 },
  { term: "液体窒素", reading: "えきたいちっそ", category: "procedure", boost_weight: 2.0 },
  { term: "凍結療法", reading: "とうけつりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "パッチテスト", category: "procedure", boost_weight: 1.5 },
  { term: "プリックテスト", category: "procedure", boost_weight: 1.5 },
  { term: "ダーモスコピー", category: "procedure", boost_weight: 2.0 },
  { term: "皮膚生検", reading: "ひふせいけん", category: "procedure", boost_weight: 2.0 },
  { term: "KOH検査", reading: "けーおーえいちけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "ウッド灯", reading: "うっどとう", category: "procedure", boost_weight: 1.5 },
  { term: "電気凝固", reading: "でんきぎょうこ", category: "procedure", boost_weight: 1.5 },
  { term: "切除術", reading: "せつじょじゅつ", category: "procedure", boost_weight: 1.5 },
];

// ================================================================
// エクスポート
// ================================================================
export const DEFAULT_VOCABULARY: Record<Specialty, VocabEntry[]> = {
  common: COMMON,
  beauty: BEAUTY,
  internal: INTERNAL,
  surgery: SURGERY,
  orthopedics: ORTHOPEDICS,
  dermatology: DERMATOLOGY,
};

/** 指定された診療科のデフォルト辞書を取得（共通 + 選択科の合算） */
export function getDefaultVocabulary(specialties: Specialty[]): VocabEntry[] {
  const result: VocabEntry[] = [...COMMON];
  const added = new Set(COMMON.map((v) => v.term));

  for (const sp of specialties) {
    if (sp === "common") continue;
    const entries = DEFAULT_VOCABULARY[sp];
    if (!entries) continue;
    for (const entry of entries) {
      if (!added.has(entry.term)) {
        result.push(entry);
        added.add(entry.term);
      }
    }
  }

  return result;
}

/** 全診療科の用語数サマリー */
export function getVocabularySummary(): Record<Specialty, number> {
  return Object.fromEntries(
    Object.entries(DEFAULT_VOCABULARY).map(([key, entries]) => [key, entries.length])
  ) as Record<Specialty, number>;
}
