// lib/openapi/registry.ts — OpenAPI ルート定義レジストリ
// 主要APIルートのOpenAPIメタデータを定義
import { z } from "zod";

/** APIルート定義 */
export interface RouteDefinition {
  path: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  summary: string;
  tags: string[];
  auth?: "admin" | "patient" | "platform" | "none";
  requestSchema?: z.ZodType;
  responseDescription?: string;
}

// ルート定義のインポートを遅延読み込みにする（スクリプト実行時のみ利用）
// スキーマは動的importで取得するため、ここではメタデータのみ定義

/** 主要APIルートのメタデータ定義 */
export const ROUTE_DEFINITIONS: RouteDefinition[] = [
  // === 患者向けAPI ===
  {
    path: "/api/reservations",
    method: "GET",
    summary: "予約枠情報取得",
    tags: ["予約"],
    auth: "patient",
    responseDescription: "利用可能な予約枠一覧",
  },
  {
    path: "/api/reservations",
    method: "POST",
    summary: "予約作成・変更・キャンセル",
    tags: ["予約"],
    auth: "patient",
    responseDescription: "予約操作結果",
  },
  {
    path: "/api/reorder/apply",
    method: "POST",
    summary: "再処方申請",
    tags: ["再処方"],
    auth: "patient",
    responseDescription: "申請結果",
  },
  {
    path: "/api/reorder/cancel",
    method: "POST",
    summary: "再処方キャンセル",
    tags: ["再処方"],
    auth: "patient",
    responseDescription: "キャンセル結果",
  },
  {
    path: "/api/checkout",
    method: "POST",
    summary: "決済処理",
    tags: ["決済"],
    auth: "patient",
    responseDescription: "決済結果",
  },
  {
    path: "/api/mypage/settings",
    method: "GET",
    summary: "マイページ設定取得",
    tags: ["マイページ"],
    auth: "patient",
    responseDescription: "マイページ設定",
  },
  {
    path: "/api/register/personal-info",
    method: "POST",
    summary: "個人情報登録",
    tags: ["患者登録"],
    auth: "patient",
    responseDescription: "登録結果",
  },
  {
    path: "/api/register/complete",
    method: "POST",
    summary: "登録完了（電話番号認証後）",
    tags: ["患者登録"],
    auth: "patient",
    responseDescription: "完了結果",
  },
  {
    path: "/api/intake",
    method: "POST",
    summary: "問診回答送信",
    tags: ["問診"],
    auth: "patient",
    responseDescription: "送信結果",
  },
  {
    path: "/api/verify/send",
    method: "POST",
    summary: "電話番号認証コード送信",
    tags: ["認証"],
    auth: "patient",
    responseDescription: "送信結果",
  },
  {
    path: "/api/verify/check",
    method: "POST",
    summary: "認証コード検証",
    tags: ["認証"],
    auth: "patient",
    responseDescription: "検証結果",
  },
  {
    path: "/api/health",
    method: "GET",
    summary: "ヘルスチェック",
    tags: ["システム"],
    auth: "none",
    responseDescription: "サーバー状態",
  },

  // === Dr向けAPI ===
  {
    path: "/api/doctor/reorders/approve",
    method: "POST",
    summary: "再処方承認",
    tags: ["Dr操作"],
    auth: "admin",
    responseDescription: "承認結果",
  },
  {
    path: "/api/doctor/reorders/reject",
    method: "POST",
    summary: "再処方却下",
    tags: ["Dr操作"],
    auth: "admin",
    responseDescription: "却下結果",
  },

  // === 管理画面API ===
  {
    path: "/api/admin/patients",
    method: "GET",
    summary: "患者一覧取得",
    tags: ["管理: 患者"],
    auth: "admin",
    responseDescription: "患者一覧",
  },
  {
    path: "/api/admin/patients/{id}",
    method: "GET",
    summary: "患者詳細取得",
    tags: ["管理: 患者"],
    auth: "admin",
    responseDescription: "患者詳細情報",
  },
  {
    path: "/api/admin/reorders",
    method: "GET",
    summary: "再処方一覧取得",
    tags: ["管理: 再処方"],
    auth: "admin",
    responseDescription: "再処方一覧",
  },
  {
    path: "/api/admin/products",
    method: "GET",
    summary: "商品一覧取得",
    tags: ["管理: 商品"],
    auth: "admin",
    responseDescription: "商品一覧",
  },
  {
    path: "/api/admin/products",
    method: "POST",
    summary: "商品作成",
    tags: ["管理: 商品"],
    auth: "admin",
    responseDescription: "作成結果",
  },
  {
    path: "/api/admin/inventory",
    method: "GET",
    summary: "在庫一覧取得",
    tags: ["管理: 在庫"],
    auth: "admin",
    responseDescription: "在庫情報",
  },
  {
    path: "/api/admin/shipping",
    method: "GET",
    summary: "配送一覧取得",
    tags: ["管理: 配送"],
    auth: "admin",
    responseDescription: "配送一覧",
  },
  {
    path: "/api/admin/shipping",
    method: "POST",
    summary: "配送登録",
    tags: ["管理: 配送"],
    auth: "admin",
    responseDescription: "配送登録結果",
  },
  {
    path: "/api/admin/doctors",
    method: "GET",
    summary: "医師一覧取得",
    tags: ["管理: スケジュール"],
    auth: "admin",
    responseDescription: "医師一覧",
  },
  {
    path: "/api/admin/doctors",
    method: "POST",
    summary: "医師登録・更新",
    tags: ["管理: スケジュール"],
    auth: "admin",
    responseDescription: "登録結果",
  },
  {
    path: "/api/admin/schedule",
    method: "GET",
    summary: "予約枠スケジュール取得",
    tags: ["管理: スケジュール"],
    auth: "admin",
    responseDescription: "スケジュール情報",
  },
  {
    path: "/api/admin/settings",
    method: "GET",
    summary: "テナント設定取得",
    tags: ["管理: 設定"],
    auth: "admin",
    responseDescription: "設定値一覧",
  },
  {
    path: "/api/admin/settings",
    method: "PUT",
    summary: "テナント設定更新",
    tags: ["管理: 設定"],
    auth: "admin",
    responseDescription: "更新結果",
  },
  {
    path: "/api/admin/tags",
    method: "GET",
    summary: "タグ一覧取得",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "タグ一覧",
  },
  {
    path: "/api/admin/tags",
    method: "POST",
    summary: "タグ作成",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "作成結果",
  },
  {
    path: "/api/admin/karte-templates",
    method: "GET",
    summary: "カルテテンプレート一覧",
    tags: ["管理: カルテ"],
    auth: "admin",
    responseDescription: "テンプレート一覧",
  },
  {
    path: "/api/admin/karte-templates",
    method: "POST",
    summary: "カルテテンプレート作成",
    tags: ["管理: カルテ"],
    auth: "admin",
    responseDescription: "作成結果",
  },
  {
    path: "/api/admin/refunds",
    method: "POST",
    summary: "返金処理",
    tags: ["管理: 決済"],
    auth: "admin",
    responseDescription: "返金結果",
  },
  {
    path: "/api/admin/line/rich-menus",
    method: "GET",
    summary: "リッチメニュー一覧",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "リッチメニュー一覧",
  },
  {
    path: "/api/admin/line/rich-menus",
    method: "POST",
    summary: "リッチメニュー作成",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "作成結果",
  },
  {
    path: "/api/admin/line/rich-menus/ai-generate",
    method: "POST",
    summary: "リッチメニュー画像AI生成",
    tags: ["管理: LINE", "AI"],
    auth: "admin",
    responseDescription: "生成されたSVG画像",
  },
  {
    path: "/api/admin/line/templates",
    method: "GET",
    summary: "LINEテンプレート一覧",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "テンプレート一覧",
  },
  {
    path: "/api/admin/line/broadcast",
    method: "POST",
    summary: "LINE一斉配信",
    tags: ["管理: LINE"],
    auth: "admin",
    responseDescription: "配信結果",
  },
  {
    path: "/api/admin/dashboard-stats",
    method: "GET",
    summary: "ダッシュボード統計",
    tags: ["管理: ダッシュボード"],
    auth: "admin",
    responseDescription: "統計データ",
  },
  {
    path: "/api/admin/dashboard-trends",
    method: "GET",
    summary: "ダッシュボードトレンド",
    tags: ["管理: ダッシュボード"],
    auth: "admin",
    responseDescription: "トレンドデータ",
  },

  // === Webhook ===
  {
    path: "/api/webhook",
    method: "POST",
    summary: "LINE Webhook受信",
    tags: ["Webhook"],
    auth: "none",
    responseDescription: "処理結果",
  },
  {
    path: "/api/square/webhook",
    method: "POST",
    summary: "Square Webhook受信",
    tags: ["Webhook"],
    auth: "none",
    responseDescription: "処理結果",
  },

  // === プラットフォームAPI ===
  {
    path: "/api/platform/login",
    method: "POST",
    summary: "プラットフォームログイン",
    tags: ["プラットフォーム"],
    auth: "none",
    responseDescription: "ログイン結果",
  },
  {
    path: "/api/platform/tenants",
    method: "GET",
    summary: "テナント一覧取得",
    tags: ["プラットフォーム"],
    auth: "platform",
    responseDescription: "テナント一覧",
  },
  {
    path: "/api/platform/tenants",
    method: "POST",
    summary: "テナント作成",
    tags: ["プラットフォーム"],
    auth: "platform",
    responseDescription: "作成結果",
  },
  {
    path: "/api/platform/billing/invoices",
    method: "GET",
    summary: "請求書一覧",
    tags: ["プラットフォーム: 請求"],
    auth: "platform",
    responseDescription: "請求書一覧",
  },
];
