/* コラム記事のメタデータ一覧 — インデックスページ・相互リンク・sitemapで共用 */
export const articles = [
  {
    slug: "clinic-line-case-studies",
    title: "クリニックのLINE公式アカウント活用事例5選 — 業務効率化と患者満足度向上の実践例",
    description: "LINE公式アカウントを活用してクリニック業務を効率化した5つの事例を紹介。予約管理・再診促進・問診自動化など、具体的な成果と導入のポイントを解説します。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "8分",
  },
  {
    slug: "lstep-vs-clinic-tool",
    title: "Lステップ・Liny vs クリニック専用ツール — LINE配信ツール徹底比較",
    description: "Lステップ・Linyなどの汎用LINE配信ツールとクリニック専用ツールの違いを徹底比較。機能・費用・運用負荷の観点から、クリニックに最適なツール選びを解説。",
    date: "2026-03-17",
    category: "ツール比較",
    readTime: "10分",
  },
  {
    slug: "clinic-dx-guide",
    title: "クリニックDX完全ガイド — LINE公式アカウントから始める業務デジタル化",
    description: "クリニックのDX（デジタルトランスフォーメーション）をLINE公式アカウントから始める方法を完全解説。予約・問診・会計・配送まで段階的にデジタル化するロードマップを紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "12分",
  },
  {
    slug: "line-reservation-no-show",
    title: "LINE予約管理で無断キャンセルを削減 — クリニックの予約運用改善ガイド",
    description: "LINEを活用した予約管理で無断キャンセル（ノーショー）を大幅削減する方法を解説。自動リマインド・簡単変更・キャンセル待ち管理の具体的な施策を紹介。",
    date: "2026-03-17",
    category: "業務改善",
    readTime: "7分",
  },
  {
    slug: "segment-delivery-repeat",
    title: "LINEセグメント配信でクリニックのリピート率を向上させる方法",
    description: "LINE公式アカウントのセグメント配信を活用して、クリニックの再診率・リピート率を向上させる具体的な方法を解説。配信シナリオやセグメント設計のノウハウを紹介。",
    date: "2026-03-17",
    category: "マーケティング",
    readTime: "9分",
  },
  {
    slug: "clinic-line-friends-growth",
    title: "クリニックのLINE友だち集め — 月100人増やす7つの施策",
    description: "クリニックのLINE公式アカウントの友だち数を効率的に増やす7つの施策を紹介。院内掲示・Web導線・初回特典など、すぐに実践できる集客テクニックを解説。",
    date: "2026-03-17",
    category: "マーケティング",
    readTime: "8分",
  },
  {
    slug: "electronic-medical-record-guide",
    title: "クリニックの電子カルテ選び方ガイド — LINE連携で業務効率化",
    description: "クリニック向け電子カルテの選び方を徹底解説。LINE公式アカウントとの連携で予約・問診・カルテ記録を一元管理し、業務効率を最大化する方法を紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "online-medical-line",
    title: "オンライン診療×LINE — 患者体験を最大化する運用術",
    description: "オンライン診療とLINE公式アカウントを組み合わせて患者体験を向上させる方法を解説。予約・問診・ビデオ通話・処方・決済までLINE起点で完結する運用術を紹介。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "rich-menu-design",
    title: "クリニックのLINEリッチメニュー設計 — 患者導線を最適化する5つのポイント",
    description: "クリニックのLINE公式アカウントにおけるリッチメニューの設計方法を解説。予約・問診・お知らせなど、患者が迷わず目的の機能にたどり着くUI設計のポイントを紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "7分",
  },
  {
    slug: "clinic-opening-line",
    title: "クリニック開業時のLINE公式アカウント活用 — 開業前から始める集患戦略",
    description: "クリニック開業前からLINE公式アカウントを活用して集患する方法を解説。開業準備期間中のLINE構築から初月の友だち獲得までのロードマップを紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "beauty-clinic-line",
    title: "美容クリニックのLINE活用術 — カウンセリング予約からアフターフォローまで",
    description: "美容クリニックに特化したLINE公式アカウントの活用方法を解説。カウンセリング予約・施術リマインド・アフターフォロー・リピート促進まで、一連の患者体験をLINEで最適化。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "line-block-rate-reduction",
    title: "クリニックのLINE配信で患者に嫌われない — ブロック率を下げる5つの鉄則",
    description: "LINE公式アカウントのブロック率を下げるための5つの鉄則を解説。配信頻度・内容・タイミングの最適化で、患者との長期的な関係を構築する方法を紹介。",
    date: "2026-03-17",
    category: "マーケティング",
    readTime: "7分",
  },
  {
    slug: "reservation-system-comparison",
    title: "クリニック予約システム比較10選 — LINE連携できるツールの選び方",
    description: "LINE連携に対応したクリニック向け予約システム10選を徹底比較。機能・価格・導入実績の観点から、最適な予約システムの選び方を解説。",
    date: "2026-03-17",
    category: "比較",
    readTime: "12分",
  },
  {
    slug: "dental-clinic-line",
    title: "歯科クリニックのLINE活用 — 定期検診リマインドで通院率を向上",
    description: "歯科クリニックに特化したLINE公式アカウントの活用方法を解説。定期検診リマインド・治療計画の共有・予約管理など、歯科特有の課題をLINEで解決する方法を紹介。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "8分",
  },
  {
    slug: "ai-auto-reply-guide",
    title: "クリニックのAI自動返信導入ガイド — 24時間対応で新患獲得を最大化",
    description: "クリニックのLINE公式アカウントにAI自動返信を導入する方法を解説。24時間の問い合わせ対応で新患獲得機会を逃さず、スタッフの負担も削減する運用方法を紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "9分",
  },
  {
    slug: "clinic-kpi-dashboard",
    title: "クリニック経営の数値管理 — LINEダッシュボードで見るべきKPI7選",
    description: "クリニック経営に必要な7つのKPIとその管理方法を解説。LINE公式アカウントのダッシュボードを活用して、予約数・リピート率・LTVなどをリアルタイムで把握する方法を紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "online-questionnaire-guide",
    title: "クリニックのオンライン問診導入ガイド — 待ち時間短縮と業務効率化を両立",
    description: "クリニックにオンライン問診を導入する方法を解説。LINE上での問診実施により待ち時間を短縮し、紙の問診票では得られない詳細データの活用方法を紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "8分",
  },
  {
    slug: "dermatology-clinic-line",
    title: "皮膚科クリニックのLINE活用 — 処方薬配送とフォローアップ自動化",
    description: "皮膚科クリニックに特化したLINE公式アカウントの活用方法を解説。処方薬のオンライン決済・配送管理からフォローアップメッセージの自動化まで、皮膚科特有の業務効率化を紹介。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "line-operation-outsource-vs-inhouse",
    title: "クリニックのLINE公式アカウント運用代行 vs 自社運用 — どちらが正解？",
    description: "LINE公式アカウントの運用代行と自社運用を徹底比較。費用・効果・柔軟性の観点から、クリニック規模別の最適な運用方法を解説。",
    date: "2026-03-17",
    category: "比較",
    readTime: "8分",
  },
  {
    slug: "medical-dx-success-stories",
    title: "医療DXの成功事例5選 — LINE起点でクリニック経営を変革した方法",
    description: "LINE公式アカウントを起点に医療DXを成功させた5つのクリニック事例を紹介。予約数150%増・無断キャンセル80%減・スタッフ残業ゼロなど、具体的な成果を解説。",
    date: "2026-03-17",
    category: "活用事例",
    readTime: "11分",
  },
  {
    slug: "clinic-management-success",
    title: "クリニック経営で成功するポイント — 倒産急増時代に生き残る戦略",
    description: "2024年の医療機関倒産件数は過去最多の64件。クリニック経営に必要な3つの業務と成功するクリニックの共通点、失敗要因を徹底解説。LINE活用による経営改善策も紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "clinic-crm-comparison",
    title: "クリニック向けCRM比較6選 — 患者管理を効率化するツールの選び方",
    description: "病院・クリニック向けCRMを6製品厳選比較。多機能型から地域医療連携特化型まで、選定基準・導入メリット・LINE連携の重要性を解説。",
    date: "2026-03-17",
    category: "比較",
    readTime: "9分",
  },
  {
    slug: "online-medical-cost",
    title: "オンライン診療の導入費用と運用コスト — 費用を抑える3つのコツ",
    description: "オンライン診療の導入にかかる初期費用・運用費用を項目別に解説。システム構築・ハードウェア・通信環境・セキュリティ対策の費用目安と、コストを抑える3つの方法を紹介。",
    date: "2026-03-17",
    category: "ガイド",
    readTime: "8分",
  },
  {
    slug: "busy-doctor-efficiency",
    title: "開業医が忙しい理由と業務効率化の方法 — DXで診療に集中する",
    description: "開業医の1日のスケジュールから忙しさの原因を分析。経営業務との兼務・DX対応・急患対応の3大要因と、LINE・電子カルテ・予約システムによる効率化方法を解説。",
    date: "2026-03-17",
    category: "業務改善",
    readTime: "9分",
  },
  {
    slug: "line-operation-guide",
    title: "クリニックのLINE公式アカウント運用完全ガイド｜友だち集めから配信・自動化まで",
    description: "LINE公式アカウントの基本設定から友だち集め・セグメント配信・リッチメニュー・AI自動返信・ブロック率対策まで、クリニックのLINE運用を体系的に解説する完全ガイド。",
    date: "2026-03-18",
    category: "ガイド",
    readTime: "15分",
  },
  {
    slug: "clinic-dx-complete-guide",
    title: "クリニックDX完全ガイド｜電子カルテ・予約・問診・決済のデジタル化手順",
    description: "電子カルテ・予約システム・オンライン問診・オンライン診療・KPIダッシュボードの5領域を体系的に解説。クリニックDXの全体設計図として活用できる完全ガイド。",
    date: "2026-03-18",
    category: "ガイド",
    readTime: "15分",
  },
] as const;
