/* コラム記事のメタデータ一覧 — インデックスページ・相互リンク・sitemapで共用 */

export interface Article {
  slug: string;
  title: string;
  description: string;
  date: string;
  updatedDate?: string;
  category: string;
  readTime: string;
  tags?: string[];
}

/* カテゴリ→タグの自動マッピング（個別タグ未設定時のフォールバック） */
const categoryTagMap: Record<string, string[]> = {
  活用事例: ["LINE公式アカウント", "クリニックDX", "導入事例"],
  ツール比較: ["ツール比較", "LINE配信ツール", "クリニックDX"],
  ガイド: ["LINE公式アカウント", "クリニックDX", "業務効率化"],
  業務改善: ["業務効率化", "クリニックDX", "予約管理"],
  マーケティング: ["LINE配信", "セグメント配信", "患者フォロー"],
  比較: ["ツール比較", "LINE公式アカウント", "クリニックDX"],
};

/** 記事のタグを取得（個別指定 > カテゴリ自動） */
export function getArticleTags(article: Article): string[] {
  return article.tags || categoryTagMap[article.category] || ["LINE公式アカウント", "クリニックDX"];
}

export const articles: Article[] = [
  {
    slug: "clinic-line-case-studies",
    title: "クリニックのLINE公式アカウント活用事例5選 — 業務効率化と患者満足度向上の実践例",
    description: "LINE公式アカウントを活用してクリニック業務を効率化した5つの事例を紹介。予約管理・再診促進・問診自動化など、具体的な成果と導入のポイントを解説します。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "8分",
  },
  {
    slug: "lstep-vs-clinic-tool",
    title: "Lステップ・Liny vs クリニック専用ツール — LINE配信ツール徹底比較",
    description: "Lステップ・Linyなどの汎用LINE配信ツールとクリニック専用ツールの違いを徹底比較。機能・費用・運用負荷の観点から、クリニックに最適なツール選びを解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ツール比較",
    readTime: "10分",
  },
  {
    slug: "clinic-dx-guide",
    title: "クリニックDX完全ガイド — LINE公式アカウントから始める業務デジタル化",
    description: "クリニックのDX（デジタルトランスフォーメーション）をLINE公式アカウントから始める方法を完全解説。予約・問診・会計・配送まで段階的にデジタル化するロードマップを紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "12分",
  },
  {
    slug: "line-reservation-no-show",
    title: "LINE予約管理で無断キャンセルを削減 — クリニックの予約運用改善ガイド",
    description: "LINEを活用した予約管理で無断キャンセル（ノーショー）を大幅削減する方法を解説。自動リマインド・簡単変更・キャンセル待ち管理の具体的な施策を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "業務改善",
    readTime: "7分",
  },
  {
    slug: "segment-delivery-repeat",
    title: "LINEセグメント配信でクリニックのリピート率を向上させる方法",
    description: "LINE公式アカウントのセグメント配信を活用して、クリニックの再診率・リピート率を向上させる具体的な方法を解説。配信シナリオやセグメント設計のノウハウを紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "マーケティング",
    readTime: "9分",
  },
  {
    slug: "clinic-line-friends-growth",
    title: "クリニックのLINE友だち集め — 月100人増やす7つの施策",
    description: "クリニックのLINE公式アカウントの友だち数を効率的に増やす7つの施策を紹介。院内掲示・Web導線・初回特典など、すぐに実践できる集客テクニックを解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "マーケティング",
    readTime: "8分",
  },
  {
    slug: "electronic-medical-record-guide",
    title: "クリニックの電子カルテ選び方ガイド — LINE連携で業務効率化",
    description: "クリニック向け電子カルテの選び方を徹底解説。LINE公式アカウントとの連携で予約・問診・カルテ記録を一元管理し、業務効率を最大化する方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "online-medical-line",
    title: "オンライン診療×LINE — 患者体験を最大化する運用術",
    description: "オンライン診療とLINE公式アカウントを組み合わせて患者体験を向上させる方法を解説。予約・問診・ビデオ通話・処方・決済までLINE起点で完結する運用術を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "rich-menu-design",
    title: "クリニックのLINEリッチメニュー設計 — 患者導線を最適化する5つのポイント",
    description: "クリニックのLINE公式アカウントにおけるリッチメニューの設計方法を解説。予約・問診・お知らせなど、患者が迷わず目的の機能にたどり着くUI設計のポイントを紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "7分",
  },
  {
    slug: "clinic-opening-line",
    title: "クリニック開業時のLINE公式アカウント活用 — 開業前から始める集患戦略",
    description: "クリニック開業前からLINE公式アカウントを活用して集患する方法を解説。開業準備期間中のLINE構築から初月の友だち獲得までのロードマップを紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "beauty-clinic-line",
    title: "美容クリニックのLINE活用術 — カウンセリング予約からアフターフォローまで",
    description: "美容クリニックに特化したLINE公式アカウントの活用方法を解説。カウンセリング予約・施術リマインド・アフターフォロー・リピート促進まで、一連の患者体験をLINEで最適化。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "line-block-rate-reduction",
    title: "クリニックのLINE配信で患者に嫌われない — ブロック率を下げる5つの鉄則",
    description: "LINE公式アカウントのブロック率を下げるための5つの鉄則を解説。配信頻度・内容・タイミングの最適化で、患者との長期的な関係を構築する方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "マーケティング",
    readTime: "7分",
  },
  {
    slug: "reservation-system-comparison",
    title: "クリニック予約システム比較10選 — LINE連携できるツールの選び方",
    description: "LINE連携に対応したクリニック向け予約システム10選を徹底比較。機能・価格・導入実績の観点から、最適な予約システムの選び方を解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "比較",
    readTime: "12分",
  },
  {
    slug: "dental-clinic-line",
    title: "歯科クリニックのLINE活用 — 定期検診リマインドで通院率を向上",
    description: "歯科クリニックに特化したLINE公式アカウントの活用方法を解説。定期検診リマインド・治療計画の共有・予約管理など、歯科特有の課題をLINEで解決する方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "8分",
  },
  {
    slug: "ai-auto-reply-guide",
    title: "クリニックのAI自動返信導入ガイド — 24時間対応で新患獲得を最大化",
    description: "クリニックのLINE公式アカウントにAI自動返信を導入する方法を解説。24時間の問い合わせ対応で新患獲得機会を逃さず、スタッフの負担も削減する運用方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "9分",
  },
  {
    slug: "clinic-kpi-dashboard",
    title: "クリニック経営の数値管理 — LINEダッシュボードで見るべきKPI7選",
    description: "クリニック経営に必要な7つのKPIとその管理方法を解説。LINE公式アカウントのダッシュボードを活用して、予約数・リピート率・LTVなどをリアルタイムで把握する方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "online-questionnaire-guide",
    title: "クリニックのオンライン問診導入ガイド — 待ち時間短縮と業務効率化を両立",
    description: "クリニックにオンライン問診を導入する方法を解説。LINE上での問診実施により待ち時間を短縮し、紙の問診票では得られない詳細データの活用方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "8分",
  },
  {
    slug: "dermatology-clinic-line",
    title: "皮膚科クリニックのLINE活用 — 処方薬配送とフォローアップ自動化",
    description: "皮膚科クリニックに特化したLINE公式アカウントの活用方法を解説。処方薬のオンライン決済・配送管理からフォローアップメッセージの自動化まで、皮膚科特有の業務効率化を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "9分",
  },
  {
    slug: "line-operation-outsource-vs-inhouse",
    title: "クリニックのLINE公式アカウント運用代行 vs 自社運用 — どちらが正解？",
    description: "LINE公式アカウントの運用代行と自社運用を徹底比較。費用・効果・柔軟性の観点から、クリニック規模別の最適な運用方法を解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "比較",
    readTime: "8分",
  },
  {
    slug: "medical-dx-success-stories",
    title: "医療DXの成功事例5選 — LINE起点でクリニック経営を変革した方法",
    description: "LINE公式アカウントを起点に医療DXを成功させた5つのクリニック事例を紹介。予約数150%増・無断キャンセル80%減・スタッフ残業ゼロなど、具体的な成果を解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "活用事例",
    readTime: "11分",
  },
  {
    slug: "clinic-management-success",
    title: "クリニック経営で成功するポイント — 倒産急増時代に生き残る戦略",
    description: "2024年の医療機関倒産件数は過去最多の64件。クリニック経営に必要な3つの業務と成功するクリニックの共通点、失敗要因を徹底解説。LINE活用による経営改善策も紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "10分",
  },
  {
    slug: "clinic-crm-comparison",
    title: "クリニック向けCRM比較6選 — 患者管理を効率化するツールの選び方",
    description: "病院・クリニック向けCRMを6製品厳選比較。多機能型から地域医療連携特化型まで、選定基準・導入メリット・LINE連携の重要性を解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "比較",
    readTime: "9分",
  },
  {
    slug: "online-medical-cost",
    title: "オンライン診療の導入費用と運用コスト — 費用を抑える3つのコツ",
    description: "オンライン診療の導入にかかる初期費用・運用費用を項目別に解説。システム構築・ハードウェア・通信環境・セキュリティ対策の費用目安と、コストを抑える3つの方法を紹介。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "8分",
  },
  {
    slug: "busy-doctor-efficiency",
    title: "開業医が忙しい理由と業務効率化の方法 — DXで診療に集中する",
    description: "開業医の1日のスケジュールから忙しさの原因を分析。経営業務との兼務・DX対応・急患対応の3大要因と、LINE・電子カルテ・予約システムによる効率化方法を解説。",
    date: "2026-03-17",
    updatedDate: "2026-03-18",
    category: "業務改善",
    readTime: "9分",
  },
  {
    slug: "line-operation-guide",
    title: "クリニックのLINE公式アカウント運用完全ガイド｜友だち集めから配信・自動化まで",
    description: "LINE公式アカウントの基本設定から友だち集め・セグメント配信・リッチメニュー・AI自動返信・ブロック率対策まで、クリニックのLINE運用を体系的に解説する完全ガイド。",
    date: "2026-03-18",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "15分",
  },
  {
    slug: "clinic-dx-complete-guide",
    title: "クリニックDX完全ガイド｜電子カルテ・予約・問診・決済のデジタル化手順",
    description: "電子カルテ・予約システム・オンライン問診・オンライン診療・KPIダッシュボードの5領域を体系的に解説。クリニックDXの全体設計図として活用できる完全ガイド。",
    date: "2026-03-18",
    updatedDate: "2026-03-18",
    category: "ガイド",
    readTime: "15分",
  },
  {
    slug: "clinic-line-tool-5-comparison",
    title: "クリニック向けLINEツール5社比較｜メディカルフォース・March・medibot・Lステップとの違い",
    description: "クリニック向けLINE活用ツール5社（Lオペ for CLINIC・メディカルフォース・March・medibot・Lステップ）を機能・費用・LINE連携度で徹底比較。自院に合うツールの選び方を解説。",
    date: "2026-03-18",
    updatedDate: "2026-03-18",
    category: "比較",
    readTime: "12分",
  },
  {
    slug: "pediatric-clinic-line",
    title: "小児科クリニックのLINE活用術 — 予防接種リマインドと成長記録の共有",
    description: "小児科クリニックに特化したLINE公式アカウントの活用方法を解説。予防接種スケジュール管理・成長記録の共有・保護者への自動フォローなど、小児科特有の業務をLINEで効率化。",
    date: "2026-03-20",
    category: "活用事例",
    readTime: "8分",
    tags: ["小児科", "LINE公式アカウント", "予防接種", "クリニックDX"],
  },
  {
    slug: "orthopedic-clinic-line",
    title: "整形外科のLINE活用 — リハビリ予約管理とフォローアップ自動化",
    description: "整形外科クリニックに特化したLINE公式アカウントの活用方法を解説。リハビリ予約の自動管理・通院リマインド・運動指導の配信など、整形外科特有の患者フォローをLINEで実現。",
    date: "2026-03-20",
    category: "活用事例",
    readTime: "8分",
    tags: ["整形外科", "LINE公式アカウント", "リハビリ", "クリニックDX"],
  },
  {
    slug: "internal-medicine-line",
    title: "内科クリニックのLINE活用 — 慢性疾患の定期通院管理と服薬フォロー",
    description: "内科クリニックに特化したLINE公式アカウントの活用方法を解説。慢性疾患の定期通院リマインド・服薬フォロー・検査結果の共有など、内科特有の継続的な患者管理をLINEで効率化。",
    date: "2026-03-20",
    category: "活用事例",
    readTime: "9分",
    tags: ["内科", "LINE公式アカウント", "慢性疾患", "服薬管理"],
  },
  {
    slug: "clinic-line-roi",
    title: "クリニックのLINE公式アカウント導入ROI — 費用対効果の計算方法と事例",
    description: "クリニックがLINE公式アカウントを導入した際のROI（投資対効果）の計算方法を解説。導入コスト・削減される業務時間・増加する売上を定量的に算出し、投資判断をサポート。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "10分",
    tags: ["ROI", "費用対効果", "LINE導入", "クリニック経営"],
  },
  {
    slug: "clinic-staff-training",
    title: "クリニックスタッフのLINE運用研修ガイド — ITが苦手でも使える教育方法",
    description: "ITリテラシーの低いスタッフでもLINE公式アカウントを使いこなせるようになる研修方法を解説。段階的な教育プログラム・マニュアル作成・よくあるつまずきポイントの対策を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "8分",
    tags: ["スタッフ研修", "IT教育", "LINE運用", "クリニックDX"],
  },
  {
    slug: "clinic-patient-ltv",
    title: "クリニックの患者LTV向上戦略 — LINEで生涯価値を最大化する方法",
    description: "クリニック経営における患者LTV（顧客生涯価値）の考え方と向上戦略を解説。LINE公式アカウントを活用したリピート促進・クロスセル・長期フォローの具体策を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "9分",
    tags: ["患者LTV", "リピート率", "LINE活用", "クリニック経営"],
  },
  {
    slug: "clinic-line-automation",
    title: "クリニックのLINE自動化完全ガイド — 手動業務をゼロにする設定方法",
    description: "クリニックのLINE公式アカウント運用を自動化する方法を完全解説。予約リマインド・フォローアップ・AI返信・セグメント配信の自動化設定手順と効果を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "11分",
    tags: ["LINE自動化", "業務効率化", "自動配信", "AI自動返信"],
  },
  {
    slug: "clinic-google-review",
    title: "クリニックのGoogle口コミ対策 — LINE連携で評価を向上させる方法",
    description: "クリニックのGoogle口コミ評価を向上させる方法を解説。LINE公式アカウントを活用した口コミ依頼の自動化・ネガティブレビュー対策・MEO（マップSEO）との連携戦略を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "8分",
    tags: ["Google口コミ", "MEO", "LINE活用", "集患"],
  },
  {
    slug: "clinic-appointment-optimization",
    title: "クリニックの予約枠最適化 — LINEデータ分析で稼働率を向上させる方法",
    description: "クリニックの予約枠を最適化して稼働率を向上させる方法を解説。LINE予約データの分析から最適な枠数・時間帯設定・キャンセル待ち管理まで、データドリブンな予約運用を紹介。",
    date: "2026-03-20",
    category: "業務改善",
    readTime: "9分",
    tags: ["予約最適化", "稼働率", "データ分析", "LINE予約"],
  },
  {
    slug: "clinic-patient-communication",
    title: "クリニックの患者コミュニケーション改善 — LINE活用の5つのポイント",
    description: "クリニックの患者コミュニケーションを改善する5つのポイントを解説。LINE公式アカウントを活用した情報提供・問い合わせ対応・フォローアップで患者満足度と信頼関係を向上。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "8分",
    tags: ["患者コミュニケーション", "LINE活用", "患者満足度", "信頼関係"],
  },
  {
    slug: "clinic-ai-reply-guide",
    title: "クリニックのAI返信活用ガイド — 問い合わせ対応を自動化して新患獲得を最大化",
    description: "クリニックのLINE公式アカウントにAI返信を導入する方法を解説。患者からの問い合わせをAIが自動で返信し、スタッフの修正を学習して精度が向上する仕組みと運用のポイントを紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "9分",
    tags: ["AI返信", "自動応答", "LINE自動化", "医療DX"],
  },
  {
    slug: "clinic-data-migration",
    title: "クリニックのデータ移行ガイド — 既存システムからの安全な乗り換え方法",
    description: "既存の予約システム・電子カルテ・CRMからのデータ移行方法を解説。患者データの安全な移行手順・注意点・移行後の検証方法まで、システム切り替え時のリスクを最小化する方法を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "8分",
    tags: ["データ移行", "システム切り替え", "電子カルテ", "クリニックDX"],
  },
  {
    slug: "clinic-multi-location",
    title: "多院展開クリニックのLINE一元管理 — 複数拠点を効率的に運用する方法",
    description: "複数拠点を持つクリニックグループのLINE公式アカウント運用方法を解説。拠点別の配信管理・統合ダッシュボード・スタッフ権限管理など、多院展開特有の課題をLINEで解決。",
    date: "2026-03-20",
    category: "活用事例",
    readTime: "9分",
    tags: ["多院展開", "LINE管理", "複数拠点", "クリニックグループ"],
  },
  {
    slug: "clinic-seasonal-campaign",
    title: "クリニックの季節別LINE配信戦略 — 花粉症・インフルエンザ・美容の集患術",
    description: "クリニックの季節ごとのLINE配信戦略を解説。花粉症・インフルエンザ・紫外線対策・年末年始など、季節イベントに合わせたセグメント配信で来院を促進する方法を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "9分",
    tags: ["季節配信", "花粉症", "インフルエンザ", "LINE配信"],
  },
  {
    slug: "clinic-payment-guide",
    title: "クリニックのオンライン決済導入ガイド — LINE連携で会計業務を効率化",
    description: "クリニックにオンライン決済を導入する方法を解説。LINE上での決済完結・Square/GMO連携・銀行振込の自動消込など、会計業務を大幅に効率化する方法を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "10分",
    tags: ["オンライン決済", "Square", "GMO", "LINE決済"],
  },
  {
    slug: "clinic-patient-retention",
    title: "クリニックの患者離脱を防ぐ — LINEフォローアップで継続通院を促進する方法",
    description: "クリニックの患者離脱を防止するLINEフォローアップ戦略を解説。離脱しやすいタイミングの特定・自動フォローメッセージ・再来院促進キャンペーンなど、継続通院を促す具体策を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "8分",
    tags: ["患者離脱防止", "フォローアップ", "再来院", "リピート率"],
  },
  {
    slug: "clinic-line-security",
    title: "クリニックのLINE運用セキュリティガイド — 個人情報保護と安全な運用方法",
    description: "クリニックがLINE公式アカウントを運用する際のセキュリティ対策を解説。個人情報保護法への対応・スタッフ権限管理・患者データの安全な取り扱い方法を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "9分",
    tags: ["セキュリティ", "個人情報保護", "LINE運用", "医療データ"],
  },
  {
    slug: "clinic-waiting-time",
    title: "クリニックの待ち時間対策 — LINE通知で患者ストレスを軽減する方法",
    description: "クリニックの待ち時間問題をLINE通知で解決する方法を解説。順番通知・混雑状況の可視化・時間帯別予約の最適化など、患者と医院双方のストレスを軽減する具体策を紹介。",
    date: "2026-03-20",
    category: "業務改善",
    readTime: "8分",
    tags: ["待ち時間", "LINE通知", "患者満足度", "業務効率化"],
  },
  {
    slug: "eye-clinic-line",
    title: "眼科クリニックのLINE活用術 — コンタクト処方・定期検診管理の効率化",
    description: "眼科クリニックに特化したLINE公式アカウントの活用方法を解説。コンタクトレンズ処方リマインド・定期検診管理・術後フォローなど、眼科特有の業務をLINEで効率化する方法を紹介。",
    date: "2026-03-20",
    category: "活用事例",
    readTime: "8分",
    tags: ["眼科", "LINE公式アカウント", "コンタクト処方", "定期検診"],
  },
  {
    slug: "clinic-nps-survey",
    title: "クリニックのNPS調査導入ガイド — LINE配信で患者満足度を可視化する方法",
    description: "クリニックにNPS（Net Promoter Score）調査を導入する方法を解説。LINE公式アカウントを活用した自動配信・スコア分析・改善アクションの立て方まで、患者満足度の可視化を紹介。",
    date: "2026-03-20",
    category: "ガイド",
    readTime: "8分",
    tags: ["NPS", "患者満足度", "LINE配信", "クリニック経営"],
  },
  {
    slug: "clinic-line-analytics",
    title: "クリニックのLINE配信効果測定 — 開封率・CV率の分析方法と改善策",
    description: "クリニックのLINE配信の効果測定方法を解説。開封率・クリック率・予約CV率の計測から、ABテストによる改善、ROI算出まで、データドリブンなLINE運用の実践方法を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "9分",
    tags: ["配信分析", "開封率", "CV率", "ABテスト"],
  },
  {
    slug: "clinic-referral-program",
    title: "クリニックの紹介制度をLINEで仕組み化 — 口コミ集患を自動化する方法",
    description: "クリニックの患者紹介制度をLINE公式アカウントで仕組み化する方法を解説。紹介カードのデジタル化・特典の自動付与・紹介元の追跡管理など、口コミ集患を自動化する具体策を紹介。",
    date: "2026-03-20",
    category: "マーケティング",
    readTime: "8分",
    tags: ["紹介制度", "口コミ", "集患", "LINE自動化"],
  },
];
