// lib/invoice-pdf.ts
// 請求書PDF生成ロジック
// jsPDFのサーバーサイド使用。日本語フォントはBase64埋め込みが巨大すぎるため、
// ASCII文字のみのシンプルな請求書を生成する。

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface InvoiceData {
  invoiceNumber: string;
  tenantName: string;
  tenantEmail: string;
  billingPeriodStart: string;
  billingPeriodEnd: string;
  amount: number;
  taxAmount: number;
  totalAmount: number;
  planName: string;
  status: string;
  issuedAt: string;
  paidAt: string | null;
  notes: string | null;
}

/**
 * 請求書PDFを生成してBufferとして返す
 * 日本語フォントなし（ASCII文字のみ）
 */
export function generateInvoicePDF(data: InvoiceData): Buffer {
  const doc = new jsPDF();

  // --- ヘッダー ---
  doc.setFontSize(24);
  doc.text("INVOICE", 105, 25, { align: "center" });

  // --- 発行元情報 ---
  doc.setFontSize(10);
  doc.text("L-ope for CLINIC", 15, 45);
  doc.text("Platform Management", 15, 51);

  // --- 請求書番号・日付 ---
  doc.setFontSize(10);
  doc.text(`Invoice No: ${data.invoiceNumber}`, 140, 45);
  doc.text(`Date: ${data.issuedAt}`, 140, 51);
  doc.text(`Status: ${data.status.toUpperCase()}`, 140, 57);

  // --- 請求先 ---
  doc.setFontSize(12);
  doc.text("Bill To:", 15, 70);
  doc.setFontSize(10);
  doc.text(data.tenantName, 15, 77);
  if (data.tenantEmail) {
    doc.text(data.tenantEmail, 15, 83);
  }

  // --- 請求期間 ---
  doc.text(
    `Billing Period: ${data.billingPeriodStart} - ${data.billingPeriodEnd}`,
    15,
    95,
  );

  // --- 明細テーブル ---
  autoTable(doc, {
    startY: 105,
    head: [["Description", "Amount"]],
    body: [
      [`${data.planName} Plan - Monthly Fee`, formatCurrency(data.amount)],
      ["Tax (10%)", formatCurrency(data.taxAmount)],
    ],
    foot: [["Total", formatCurrency(data.totalAmount)]],
    theme: "grid",
    headStyles: { fillColor: [245, 158, 11] },
    footStyles: { fillColor: [245, 158, 11], textColor: [255, 255, 255] },
  });

  // --- 支払日（入金済みの場合のみ表示） ---
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY || 150;

  if (data.paidAt) {
    doc.setFontSize(10);
    doc.text(`Paid At: ${data.paidAt}`, 15, finalY + 10);
  }

  // --- 備考 ---
  if (data.notes) {
    const notesY = data.paidAt ? finalY + 20 : finalY + 10;
    doc.setFontSize(9);
    doc.text(`Notes: ${data.notes}`, 15, notesY);
  }

  // --- フッター ---
  doc.setFontSize(8);
  doc.text("Generated by L-ope Platform", 105, 285, { align: "center" });

  return Buffer.from(doc.output("arraybuffer"));
}

/**
 * 金額をJPY表記にフォーマット
 */
function formatCurrency(amount: number): string {
  return `JPY ${amount.toLocaleString()}`;
}
