// lib/__tests__/invoice-pdf.test.ts — 請求書PDF生成テスト
import { describe, it, expect, vi, beforeEach } from "vitest";

// vi.hoistedでモック関数を先に定義
const { mockText, mockSetFontSize, mockOutput } = vi.hoisted(() => {
  const mockText = vi.fn();
  const mockSetFontSize = vi.fn();
  const mockOutput = vi.fn().mockReturnValue(new ArrayBuffer(100));
  return { mockText, mockSetFontSize, mockOutput };
});

vi.mock("jspdf", () => {
  return {
    jsPDF: class {
      text = mockText;
      setFontSize = mockSetFontSize;
      output = mockOutput;
      lastAutoTable = { finalY: 150 };
    },
  };
});

vi.mock("jspdf-autotable", () => ({
  default: vi.fn(),
}));

import { generateInvoicePDF, type InvoiceData } from "@/lib/invoice-pdf";

describe("invoice-pdf", () => {
  const sampleData: InvoiceData = {
    invoiceNumber: "INV-2026-001",
    tenantName: "Test Clinic",
    tenantEmail: "clinic@test.com",
    billingPeriodStart: "2026-02-01",
    billingPeriodEnd: "2026-02-28",
    amount: 50000,
    taxAmount: 5000,
    totalAmount: 55000,
    planName: "Standard",
    status: "paid",
    issuedAt: "2026-02-22",
    paidAt: "2026-02-22",
    notes: "Monthly subscription",
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("Bufferを返す", () => {
    const result = generateInvoicePDF(sampleData);
    expect(result).toBeInstanceOf(Buffer);
  });

  it("タイトルが設定される", () => {
    generateInvoicePDF(sampleData);
    expect(mockText).toHaveBeenCalledWith("INVOICE", 105, 25, { align: "center" });
  });

  it("請求先情報が含まれる", () => {
    generateInvoicePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls).toContain("Test Clinic");
    expect(textCalls).toContain("clinic@test.com");
  });

  it("支払日が表示される（入金済みの場合）", () => {
    generateInvoicePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls.some((t: string) => t.includes("Paid At"))).toBe(true);
  });

  it("未入金の場合は支払日が表示されない", () => {
    generateInvoicePDF({ ...sampleData, paidAt: null });
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls.some((t: string) => t.includes("Paid At"))).toBe(false);
  });

  it("備考が表示される", () => {
    generateInvoicePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls.some((t: string) => t.includes("Notes:"))).toBe(true);
  });

  it("備考なしの場合は備考行が表示されない", () => {
    generateInvoicePDF({ ...sampleData, notes: null });
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls.some((t: string) => t.includes("Notes:"))).toBe(false);
  });

  it("フッターが含まれる", () => {
    generateInvoicePDF(sampleData);
    const textCalls = mockText.mock.calls.map((c: any[]) => c[0]);
    expect(textCalls).toContain("Generated by L-ope Platform");
  });
});
