// lib/voice/vocabulary/beauty.ts — 美容（自由診療）医療辞書
import type { VocabEntry } from "./types";

/** 美容（自由診療） */
export const BEAUTY: VocabEntry[] = [
  // GLP-1 / ダイエット
  { term: "マンジャロ", category: "drug", boost_weight: 2.0 },
  { term: "チルゼパチド", category: "drug", boost_weight: 2.0 },
  { term: "オゼンピック", category: "drug", boost_weight: 2.0 },
  { term: "セマグルチド", category: "drug", boost_weight: 2.0 },
  { term: "リベルサス", category: "drug", boost_weight: 2.0 },
  { term: "サクセンダ", category: "drug", boost_weight: 2.0 },
  { term: "ウゴービ", category: "drug", boost_weight: 2.0 },
  { term: "ビクトーザ", category: "drug", boost_weight: 2.0 },
  { term: "リラグルチド", category: "drug", boost_weight: 2.0 },
  { term: "トルリシティ", category: "drug", boost_weight: 2.0 },
  { term: "デュラグルチド", category: "drug", boost_weight: 2.0 },
  { term: "GLP-1", category: "drug", boost_weight: 2.0 },
  { term: "GLP-1受容体作動薬", reading: "じーえるぴーわんじゅようたいさどうやく", category: "drug", boost_weight: 2.0 },
  { term: "GIP/GLP-1", category: "drug", boost_weight: 2.0 },
  { term: "インクレチン", category: "drug", boost_weight: 1.5 },
  // ダイエット関連
  { term: "メディカルダイエット", category: "procedure", boost_weight: 1.5 },
  { term: "食欲抑制", reading: "しょくよくよくせい", category: "general", boost_weight: 1.5 },
  { term: "基礎代謝", reading: "きそたいしゃ", category: "general", boost_weight: 1.0 },
  { term: "内臓脂肪", reading: "ないぞうしぼう", category: "general", boost_weight: 1.5 },
  { term: "肥満", reading: "ひまん", category: "symptom", boost_weight: 1.5 },
  { term: "肥満症", reading: "ひまんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "体脂肪率", reading: "たいしぼうりつ", category: "lab", boost_weight: 1.0 },
  { term: "ダイエット注射", reading: "だいえっとちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "痩身", reading: "そうしん", category: "procedure", boost_weight: 1.5 },
  { term: "脂肪溶解注射", reading: "しぼうようかいちゅうしゃ", category: "procedure", boost_weight: 2.0 },
  { term: "BNLS", category: "drug", boost_weight: 2.0 },
  { term: "カベリン", category: "drug", boost_weight: 2.0 },
  { term: "脂肪吸引", reading: "しぼうきゅういん", category: "procedure", boost_weight: 2.0 },
  { term: "クールスカルプティング", category: "procedure", boost_weight: 2.0 },
  { term: "エムスカルプト", category: "procedure", boost_weight: 2.0 },
  { term: "防風通聖散", reading: "ぼうふうつうしょうさん", category: "drug", boost_weight: 2.0 },
  { term: "ゼニカル", category: "drug", boost_weight: 2.0 },
  { term: "オルリスタット", category: "drug", boost_weight: 2.0 },
  { term: "リパーゼ阻害薬", reading: "りぱーぜそがいやく", category: "drug", boost_weight: 1.5 },
  { term: "サノレックス", category: "drug", boost_weight: 2.0 },
  { term: "マジンドール", category: "drug", boost_weight: 2.0 },
  // AGA / 薄毛
  { term: "フィナステリド", category: "drug", boost_weight: 2.0 },
  { term: "デュタステリド", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル", category: "drug", boost_weight: 2.0 },
  { term: "プロペシア", category: "drug", boost_weight: 2.0 },
  { term: "ザガーロ", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル内服", reading: "みのきしじるないふく", category: "drug", boost_weight: 2.0 },
  { term: "ミノキシジル外用", reading: "みのきしじるがいよう", category: "drug", boost_weight: 2.0 },
  { term: "ミノタブ", category: "drug", boost_weight: 1.5 },
  { term: "5α還元酵素阻害薬", reading: "ごあるふぁかんげんこうそそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "AGA", category: "symptom", boost_weight: 2.0 },
  { term: "FAGA", category: "symptom", boost_weight: 2.0 },
  { term: "男性型脱毛症", reading: "だんせいがただつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "女性型脱毛症", reading: "じょせいがただつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "薄毛", reading: "うすげ", category: "symptom", boost_weight: 1.5 },
  { term: "脱毛", reading: "だつもう", category: "symptom", boost_weight: 1.5 },
  { term: "抜け毛", reading: "ぬけげ", category: "symptom", boost_weight: 1.5 },
  { term: "頭頂部", reading: "とうちょうぶ", category: "anatomy", boost_weight: 1.0 },
  { term: "前頭部", reading: "ぜんとうぶ", category: "anatomy", boost_weight: 1.0 },
  { term: "M字", reading: "えむじ", category: "symptom", boost_weight: 1.5 },
  { term: "HARG療法", reading: "はーぐりょうほう", category: "procedure", boost_weight: 2.0 },
  { term: "メソセラピー", category: "procedure", boost_weight: 1.5 },
  { term: "育毛", reading: "いくもう", category: "general", boost_weight: 1.0 },
  { term: "発毛", reading: "はつもう", category: "general", boost_weight: 1.0 },
  { term: "スピロノラクトン", category: "drug", boost_weight: 2.0 },
  { term: "パントガール", category: "drug", boost_weight: 2.0 },
  // 美容注射・フィラー
  { term: "ボトックス", category: "drug", boost_weight: 2.0 },
  { term: "ボツリヌストキシン", category: "drug", boost_weight: 2.0 },
  { term: "ボツラックス", category: "drug", boost_weight: 2.0 },
  { term: "ゼオミン", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロン酸", reading: "ひあるろんさん", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロン酸注入", reading: "ひあるろんさんちゅうにゅう", category: "procedure", boost_weight: 2.0 },
  { term: "フィラー", category: "drug", boost_weight: 2.0 },
  { term: "ジュビダーム", category: "drug", boost_weight: 2.0 },
  { term: "ジュビダームビスタ", category: "drug", boost_weight: 2.0 },
  { term: "ボリューマ", category: "drug", boost_weight: 2.0 },
  { term: "ボルベラ", category: "drug", boost_weight: 2.0 },
  { term: "レスチレン", category: "drug", boost_weight: 2.0 },
  { term: "レスチレンリド", category: "drug", boost_weight: 2.0 },
  { term: "ベビーコラーゲン", category: "drug", boost_weight: 1.5 },
  { term: "レディエッセ", category: "drug", boost_weight: 2.0 },
  { term: "エランセ", category: "drug", boost_weight: 2.0 },
  { term: "ヒアルロニダーゼ", category: "drug", boost_weight: 2.0 },
  { term: "溶解注射", reading: "ようかいちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  // 美容注射・点滴
  { term: "白玉点滴", reading: "しらたまてんてき", category: "procedure", boost_weight: 1.5 },
  { term: "グルタチオン", category: "drug", boost_weight: 2.0 },
  { term: "高濃度ビタミンC点滴", reading: "こうのうどびたみんしーてんてき", category: "procedure", boost_weight: 2.0 },
  { term: "マイヤーズカクテル", category: "procedure", boost_weight: 1.5 },
  { term: "にんにく注射", reading: "にんにくちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "プラセンタ注射", reading: "ぷらせんたちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ラエンネック", category: "drug", boost_weight: 2.0 },
  { term: "メルスモン", category: "drug", boost_weight: 2.0 },
  { term: "NMN点滴", reading: "えぬえむえぬてんてき", category: "procedure", boost_weight: 2.0 },
  { term: "エクソソーム", category: "drug", boost_weight: 2.0 },
  { term: "PRP", category: "procedure", boost_weight: 2.0 },
  { term: "多血小板血漿", reading: "たけっしょうばんけっしょう", category: "procedure", boost_weight: 2.0 },
  { term: "幹細胞", reading: "かんさいぼう", category: "general", boost_weight: 1.5 },
  // レーザー・光治療
  { term: "水光注射", reading: "すいこうちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ダーマペン", category: "procedure", boost_weight: 1.5 },
  { term: "ダーマペン4", category: "procedure", boost_weight: 2.0 },
  { term: "ヴェルベットスキン", category: "procedure", boost_weight: 1.5 },
  { term: "ピーリング", category: "procedure", boost_weight: 1.5 },
  { term: "ケミカルピーリング", category: "procedure", boost_weight: 1.5 },
  { term: "サリチル酸ピーリング", reading: "さりちるさんぴーりんぐ", category: "procedure", boost_weight: 1.5 },
  { term: "マッサージピール", category: "procedure", boost_weight: 1.5 },
  { term: "コラーゲンピール", category: "procedure", boost_weight: 1.5 },
  { term: "ハイフ", category: "procedure", boost_weight: 2.0 },
  { term: "HIFU", category: "procedure", boost_weight: 2.0 },
  { term: "ウルセラ", category: "procedure", boost_weight: 2.0 },
  { term: "ソノクイーン", category: "procedure", boost_weight: 2.0 },
  { term: "ウルトラフォーマー", category: "procedure", boost_weight: 2.0 },
  { term: "フォトフェイシャル", category: "procedure", boost_weight: 1.5 },
  { term: "IPL", category: "procedure", boost_weight: 1.5 },
  { term: "レーザートーニング", category: "procedure", boost_weight: 1.5 },
  { term: "ピコレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "ピコトーニング", category: "procedure", boost_weight: 2.0 },
  { term: "ピコスポット", category: "procedure", boost_weight: 2.0 },
  { term: "ピコフラクショナル", category: "procedure", boost_weight: 2.0 },
  { term: "Qスイッチレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "YAGレーザー", reading: "やぐれーざー", category: "procedure", boost_weight: 2.0 },
  { term: "アレキサンドライトレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "CO2レーザー", category: "procedure", boost_weight: 2.0 },
  { term: "炭酸ガスレーザー", reading: "たんさんがすれーざー", category: "procedure", boost_weight: 2.0 },
  { term: "フラクショナルレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "ジェネシス", category: "procedure", boost_weight: 1.5 },
  { term: "ポテンツァ", category: "procedure", boost_weight: 2.0 },
  { term: "RF", category: "procedure", boost_weight: 1.5 },
  { term: "ラジオ波", reading: "らじおは", category: "procedure", boost_weight: 1.5 },
  { term: "サーマクール", category: "procedure", boost_weight: 2.0 },
  { term: "医療脱毛", reading: "いりょうだつもう", category: "procedure", boost_weight: 1.5 },
  { term: "蓄熱式脱毛", reading: "ちくねつしきだつもう", category: "procedure", boost_weight: 1.5 },
  { term: "ダイオードレーザー", category: "procedure", boost_weight: 2.0 },
  // 糸リフト・美容外科
  { term: "スレッドリフト", category: "procedure", boost_weight: 2.0 },
  { term: "糸リフト", reading: "いとりふと", category: "procedure", boost_weight: 2.0 },
  { term: "フェイスリフト", category: "procedure", boost_weight: 1.5 },
  { term: "ミントリフト", category: "procedure", boost_weight: 2.0 },
  { term: "テスリフト", category: "procedure", boost_weight: 2.0 },
  { term: "二重整形", reading: "ふたえせいけい", category: "procedure", boost_weight: 1.5 },
  { term: "埋没法", reading: "まいぼつほう", category: "procedure", boost_weight: 2.0 },
  { term: "切開法", reading: "せっかいほう", category: "procedure", boost_weight: 1.5 },
  { term: "目頭切開", reading: "めがしらせっかい", category: "procedure", boost_weight: 1.5 },
  { term: "目尻切開", reading: "めじりせっかい", category: "procedure", boost_weight: 1.5 },
  { term: "鼻整形", reading: "はなせいけい", category: "procedure", boost_weight: 1.5 },
  { term: "隆鼻術", reading: "りゅうびじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "鼻尖形成", reading: "びせんけいせい", category: "procedure", boost_weight: 2.0 },
  { term: "小鼻縮小", reading: "こばなしゅくしょう", category: "procedure", boost_weight: 1.5 },
  { term: "豊胸術", reading: "ほうきょうじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "脂肪注入", reading: "しぼうちゅうにゅう", category: "procedure", boost_weight: 1.5 },
  { term: "エラ削り", reading: "えらけずり", category: "procedure", boost_weight: 1.5 },
  { term: "顎形成", reading: "あごけいせい", category: "procedure", boost_weight: 1.5 },
  { term: "リップアートメイク", category: "procedure", boost_weight: 1.5 },
  { term: "アートメイク", category: "procedure", boost_weight: 1.5 },
  // 肌・症状
  { term: "シミ", category: "symptom", boost_weight: 1.5 },
  { term: "しわ", category: "symptom", boost_weight: 1.5 },
  { term: "たるみ", category: "symptom", boost_weight: 1.5 },
  { term: "ニキビ", category: "symptom", boost_weight: 1.5 },
  { term: "ニキビ跡", reading: "にきびあと", category: "symptom", boost_weight: 1.5 },
  { term: "毛穴", reading: "けあな", category: "symptom", boost_weight: 1.5 },
  { term: "肝斑", reading: "かんぱん", category: "symptom", boost_weight: 2.0 },
  { term: "色素沈着", reading: "しきそちんちゃく", category: "symptom", boost_weight: 1.5 },
  { term: "くすみ", category: "symptom", boost_weight: 1.5 },
  { term: "赤ら顔", reading: "あからがお", category: "symptom", boost_weight: 1.5 },
  { term: "毛細血管拡張", reading: "もうさいけっかんかくちょう", category: "symptom", boost_weight: 1.5 },
  { term: "クレーター", category: "symptom", boost_weight: 1.5 },
  { term: "肌荒れ", reading: "はだあれ", category: "symptom", boost_weight: 1.0 },
  { term: "乾燥肌", reading: "かんそうはだ", category: "symptom", boost_weight: 1.0 },
  { term: "敏感肌", reading: "びんかんはだ", category: "symptom", boost_weight: 1.0 },
  { term: "そばかす", category: "symptom", boost_weight: 1.5 },
  { term: "老人性色素斑", reading: "ろうじんせいしきそはん", category: "symptom", boost_weight: 2.0 },
  { term: "日光黒子", reading: "にっこうこくし", category: "symptom", boost_weight: 2.0 },
  { term: "ほうれい線", reading: "ほうれいせん", category: "anatomy", boost_weight: 1.5 },
  { term: "マリオネットライン", category: "anatomy", boost_weight: 1.5 },
  { term: "ゴルゴライン", category: "anatomy", boost_weight: 1.5 },
  { term: "法令線", reading: "ほうれいせん", category: "anatomy", boost_weight: 1.5 },
  { term: "目の下のたるみ", reading: "めのしたのたるみ", category: "symptom", boost_weight: 1.5 },
  { term: "クマ", category: "symptom", boost_weight: 1.5 },
  { term: "眼瞼下垂", reading: "がんけんかすい", category: "symptom", boost_weight: 2.0 },
  { term: "多汗症", reading: "たかんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "ワキガ", category: "symptom", boost_weight: 1.5 },
  { term: "腋臭症", reading: "えきしゅうしょう", category: "symptom", boost_weight: 2.0 },
  // GLP-1 副作用
  { term: "嘔気", reading: "おうき", category: "symptom", boost_weight: 1.5 },
  { term: "悪心", reading: "おしん", category: "symptom", boost_weight: 1.5 },
  { term: "嘔吐", reading: "おうと", category: "symptom", boost_weight: 1.5 },
  { term: "低血糖", reading: "ていけっとう", category: "symptom", boost_weight: 1.5 },
  { term: "下痢", reading: "げり", category: "symptom", boost_weight: 1.5 },
  { term: "便秘", reading: "べんぴ", category: "symptom", boost_weight: 1.5 },
  { term: "腹痛", reading: "ふくつう", category: "symptom", boost_weight: 1.5 },
  { term: "食欲不振", reading: "しょくよくふしん", category: "symptom", boost_weight: 1.5 },
  { term: "膵炎リスク", reading: "すいえんりすく", category: "symptom", boost_weight: 1.5 },
  { term: "注射部位反応", reading: "ちゅうしゃぶいはんのう", category: "symptom", boost_weight: 1.5 },
  { term: "胃腸障害", reading: "いちょうしょうがい", category: "symptom", boost_weight: 1.5 },
  // 美容皮膚科・スキンケア
  { term: "トレチノイン", category: "drug", boost_weight: 2.0 },
  { term: "レチノール", category: "drug", boost_weight: 1.5 },
  { term: "レチノイド", category: "drug", boost_weight: 1.5 },
  { term: "ハイドロキノン", category: "drug", boost_weight: 2.0 },
  { term: "ビタミンC誘導体", reading: "びたみんしーゆうどうたい", category: "drug", boost_weight: 1.5 },
  { term: "アスコルビン酸", reading: "あすこるびんさん", category: "drug", boost_weight: 1.5 },
  { term: "ナイアシンアミド", category: "drug", boost_weight: 1.5 },
  { term: "トラネキサム酸", reading: "とらねきさむさん", category: "drug", boost_weight: 2.0 },
  { term: "グリコール酸", reading: "ぐりこーるさん", category: "drug", boost_weight: 1.5 },
  { term: "アゼライン酸", reading: "あぜらいんさん", category: "drug", boost_weight: 1.5 },
  { term: "セラミド", category: "general", boost_weight: 1.0 },
  { term: "ペプチド", category: "general", boost_weight: 1.0 },
  { term: "成長因子", reading: "せいちょういんし", category: "general", boost_weight: 1.5 },
  { term: "EGF", category: "general", boost_weight: 1.5 },
  { term: "FGF", category: "general", boost_weight: 1.5 },
  { term: "エラスチン", category: "general", boost_weight: 1.5 },
  { term: "コラーゲン", category: "general", boost_weight: 1.5 },
  { term: "プラセンタ", category: "drug", boost_weight: 1.5 },
  { term: "ボトックスビスタ", category: "drug", boost_weight: 2.0 },
  { term: "アラガン", category: "general", boost_weight: 1.5 },
  // ED治療
  { term: "シルデナフィル", category: "drug", boost_weight: 2.0 },
  { term: "バイアグラ", category: "drug", boost_weight: 2.0 },
  { term: "タダラフィル", category: "drug", boost_weight: 2.0 },
  { term: "シアリス", category: "drug", boost_weight: 2.0 },
  { term: "バルデナフィル", category: "drug", boost_weight: 2.0 },
  { term: "レビトラ", category: "drug", boost_weight: 2.0 },
  { term: "ED", category: "symptom", boost_weight: 1.5 },
  { term: "勃起不全", reading: "ぼっきふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "PDE5阻害薬", reading: "ぴーでぃーいーふぁいぶそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "早漏", reading: "そうろう", category: "symptom", boost_weight: 1.5 },
  // ピル・婦人科
  { term: "低用量ピル", reading: "ていようりょうぴる", category: "drug", boost_weight: 2.0 },
  { term: "OC", category: "drug", boost_weight: 1.5 },
  { term: "LEP", category: "drug", boost_weight: 1.5 },
  { term: "マーベロン", category: "drug", boost_weight: 2.0 },
  { term: "トリキュラー", category: "drug", boost_weight: 2.0 },
  { term: "ファボワール", category: "drug", boost_weight: 2.0 },
  { term: "ラベルフィーユ", category: "drug", boost_weight: 2.0 },
  { term: "アンジュ", category: "drug", boost_weight: 2.0 },
  { term: "ヤーズ", category: "drug", boost_weight: 2.0 },
  { term: "ヤーズフレックス", category: "drug", boost_weight: 2.0 },
  { term: "フリウェル", category: "drug", boost_weight: 2.0 },
  { term: "ドロスピレノン", category: "drug", boost_weight: 2.0 },
  { term: "ルナベル", category: "drug", boost_weight: 2.0 },
  { term: "ジェミーナ", category: "drug", boost_weight: 2.0 },
  { term: "アフターピル", category: "drug", boost_weight: 2.0 },
  { term: "緊急避妊薬", reading: "きんきゅうひにんやく", category: "drug", boost_weight: 2.0 },
  { term: "ノルレボ", category: "drug", boost_weight: 2.0 },
  { term: "エラワン", category: "drug", boost_weight: 2.0 },
  { term: "月経困難症", reading: "げっけいこんなんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "PMS", category: "symptom", boost_weight: 2.0 },
  { term: "月経前症候群", reading: "げっけいぜんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "不正出血", reading: "ふせいしゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "生理痛", reading: "せいりつう", category: "symptom", boost_weight: 1.5 },
  { term: "子宮内膜症", reading: "しきゅうないまくしょう", category: "symptom", boost_weight: 2.0 },
  // 性感染症（オンライン診療で多い）
  { term: "性感染症", reading: "せいかんせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "STI", category: "symptom", boost_weight: 2.0 },
  { term: "STD", category: "symptom", boost_weight: 2.0 },
  { term: "クラミジア", category: "symptom", boost_weight: 2.0 },
  { term: "淋病", reading: "りんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "梅毒", reading: "ばいどく", category: "symptom", boost_weight: 2.0 },
  { term: "ヘルペス", category: "symptom", boost_weight: 2.0 },
  { term: "性器ヘルペス", reading: "せいきへるぺす", category: "symptom", boost_weight: 2.0 },
  { term: "尖圭コンジローマ", reading: "せんけいこんじろーま", category: "symptom", boost_weight: 2.0 },
  { term: "カンジダ", category: "symptom", boost_weight: 2.0 },
  { term: "バラシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "バルトレックス", category: "drug", boost_weight: 2.0 },
  // 美白・アンチエイジング
  { term: "美白", reading: "びはく", category: "general", boost_weight: 1.5 },
  { term: "アンチエイジング", category: "general", boost_weight: 1.5 },
  { term: "エイジングケア", category: "general", boost_weight: 1.0 },
  { term: "シナール", category: "drug", boost_weight: 1.5 },
  { term: "ユベラ", category: "drug", boost_weight: 1.5 },
  { term: "ハイチオール", category: "drug", boost_weight: 1.5 },
  { term: "Lシステイン", category: "drug", boost_weight: 1.5 },
  { term: "ビオチン", category: "drug", boost_weight: 1.5 },
  // まつげ
  { term: "まつ毛貧毛症", reading: "まつげひんもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "ビマトプロスト", category: "drug", boost_weight: 2.0 },
  { term: "グラッシュビスタ", category: "drug", boost_weight: 2.0 },
  { term: "ルミガン", category: "drug", boost_weight: 2.0 },
  // --- 拡充: 最新施術・新薬剤 ---
  { term: "シルファームX", category: "procedure", boost_weight: 2.0 },
  { term: "ジュベルック", category: "drug", boost_weight: 2.0 },
  { term: "リジュラン", category: "drug", boost_weight: 2.0 },
  { term: "リジュランi", category: "drug", boost_weight: 2.0 },
  { term: "スネコス", category: "drug", boost_weight: 2.0 },
  { term: "プロファイロ", category: "drug", boost_weight: 2.0 },
  { term: "ボライト", category: "drug", boost_weight: 2.0 },
  { term: "ジュビダームボライト", category: "drug", boost_weight: 2.0 },
  { term: "ウルトラセルQプラス", category: "procedure", boost_weight: 2.0 },
  { term: "ヴァンパイアフェイシャル", category: "procedure", boost_weight: 1.5 },
  { term: "肌再生", reading: "はださいせい", category: "procedure", boost_weight: 1.5 },
  { term: "リニアファーム", category: "procedure", boost_weight: 2.0 },
  { term: "マイクロボトックス", category: "procedure", boost_weight: 2.0 },
  { term: "スキンボトックス", category: "procedure", boost_weight: 2.0 },
  { term: "エムセラ", category: "procedure", boost_weight: 2.0 },
  { term: "スカルプシュア", category: "procedure", boost_weight: 2.0 },
  { term: "トゥルースカルプ", category: "procedure", boost_weight: 2.0 },
  { term: "カウンセリング", category: "general", boost_weight: 1.0 },
  { term: "症例写真", reading: "しょうれいしゃしん", category: "general", boost_weight: 1.0 },
  { term: "ダウンタイム", category: "general", boost_weight: 1.5 },
  { term: "ビフォーアフター", category: "general", boost_weight: 1.0 },
  { term: "モニター", category: "general", boost_weight: 1.0 },
  { term: "リフトアップ", category: "procedure", boost_weight: 1.5 },
  { term: "ハイドラフェイシャル", category: "procedure", boost_weight: 2.0 },
  { term: "イオン導入", reading: "いおんどうにゅう", category: "procedure", boost_weight: 1.5 },
  { term: "エレクトロポレーション", category: "procedure", boost_weight: 2.0 },
  { term: "フォトナ", category: "procedure", boost_weight: 2.0 },
  { term: "インティマレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "ロングパルスYAG", category: "procedure", boost_weight: 2.0 },
  { term: "美肌", reading: "びはだ", category: "general", boost_weight: 1.0 },
  { term: "小顔", reading: "こがお", category: "general", boost_weight: 1.0 },
  { term: "エラボトックス", category: "procedure", boost_weight: 2.0 },
  { term: "肩ボトックス", reading: "かたぼとっくす", category: "procedure", boost_weight: 2.0 },
  { term: "ガミースマイル", category: "symptom", boost_weight: 1.5 },
  { term: "涙袋形成", reading: "なみだぶくろけいせい", category: "procedure", boost_weight: 1.5 },
  { term: "クレヴィエル", category: "drug", boost_weight: 2.0 },
  { term: "テオシアル", category: "drug", boost_weight: 2.0 },
];
