// lib/voice/vocabulary/common.ts — 共通（全科）医療辞書
import type { VocabEntry } from "./types";

/** 共通（全科）— 全テナントに必ず適用 */
export const COMMON: VocabEntry[] = [
  // バイタル・基本
  { term: "バイタルサイン", category: "general", boost_weight: 1.5 },
  { term: "血圧", reading: "けつあつ", category: "lab", boost_weight: 1.5 },
  { term: "収縮期血圧", reading: "しゅうしゅくきけつあつ", category: "lab", boost_weight: 1.5 },
  { term: "拡張期血圧", reading: "かくちょうきけつあつ", category: "lab", boost_weight: 1.5 },
  { term: "脈拍", reading: "みゃくはく", category: "lab", boost_weight: 1.5 },
  { term: "心拍数", reading: "しんぱくすう", category: "lab", boost_weight: 1.5 },
  { term: "体温", reading: "たいおん", category: "lab", boost_weight: 1.5 },
  { term: "呼吸数", reading: "こきゅうすう", category: "lab", boost_weight: 1.5 },
  { term: "SpO2", category: "lab", boost_weight: 2.0 },
  { term: "BMI", category: "lab", boost_weight: 1.5 },
  { term: "体重", reading: "たいじゅう", category: "lab", boost_weight: 1.5 },
  { term: "身長", reading: "しんちょう", category: "lab", boost_weight: 1.0 },
  { term: "意識レベル", reading: "いしきれべる", category: "general", boost_weight: 1.5 },
  { term: "JCS", category: "general", boost_weight: 1.5 },
  { term: "GCS", category: "general", boost_weight: 1.5 },
  // 問診基本
  { term: "既往歴", reading: "きおうれき", category: "general", boost_weight: 1.5 },
  { term: "現病歴", reading: "げんびょうれき", category: "general", boost_weight: 1.5 },
  { term: "家族歴", reading: "かぞくれき", category: "general", boost_weight: 1.5 },
  { term: "社会歴", reading: "しゃかいれき", category: "general", boost_weight: 1.5 },
  { term: "服薬歴", reading: "ふくやくれき", category: "general", boost_weight: 1.5 },
  { term: "手術歴", reading: "しゅじゅつれき", category: "general", boost_weight: 1.5 },
  { term: "アレルギー", category: "general", boost_weight: 1.5 },
  { term: "薬物アレルギー", reading: "やくぶつあれるぎー", category: "general", boost_weight: 1.5 },
  { term: "食物アレルギー", reading: "しょくもつあれるぎー", category: "general", boost_weight: 1.5 },
  { term: "副作用", reading: "ふくさよう", category: "general", boost_weight: 1.5 },
  { term: "有害事象", reading: "ゆうがいじしょう", category: "general", boost_weight: 1.5 },
  { term: "禁忌", reading: "きんき", category: "general", boost_weight: 1.5 },
  { term: "併用禁忌", reading: "へいようきんき", category: "general", boost_weight: 1.5 },
  { term: "アナフィラキシー", category: "symptom", boost_weight: 2.0 },
  // 処方関連
  { term: "処方", reading: "しょほう", category: "general", boost_weight: 1.5 },
  { term: "処方箋", reading: "しょほうせん", category: "general", boost_weight: 1.5 },
  { term: "用量", reading: "ようりょう", category: "general", boost_weight: 1.5 },
  { term: "用法", reading: "ようほう", category: "general", boost_weight: 1.5 },
  { term: "増量", reading: "ぞうりょう", category: "general", boost_weight: 1.5 },
  { term: "減量", reading: "げんりょう", category: "general", boost_weight: 1.5 },
  { term: "投与", reading: "とうよ", category: "general", boost_weight: 1.5 },
  { term: "経口投与", reading: "けいこうとうよ", category: "general", boost_weight: 1.5 },
  { term: "皮下注射", reading: "ひかちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "筋肉注射", reading: "きんにくちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "静脈注射", reading: "じょうみゃくちゅうしゃ", category: "general", boost_weight: 1.5 },
  { term: "点滴", reading: "てんてき", category: "general", boost_weight: 1.5 },
  { term: "外用", reading: "がいよう", category: "general", boost_weight: 1.5 },
  { term: "頓服", reading: "とんぷく", category: "general", boost_weight: 1.5 },
  { term: "内服", reading: "ないふく", category: "general", boost_weight: 1.5 },
  { term: "服用", reading: "ふくよう", category: "general", boost_weight: 1.5 },
  { term: "後発品", reading: "こうはつひん", category: "general", boost_weight: 1.0 },
  { term: "ジェネリック", category: "general", boost_weight: 1.0 },
  { term: "先発品", reading: "せんぱつひん", category: "general", boost_weight: 1.0 },
  { term: "添付文書", reading: "てんぷぶんしょ", category: "general", boost_weight: 1.0 },
  { term: "適応", reading: "てきおう", category: "general", boost_weight: 1.0 },
  { term: "適応外", reading: "てきおうがい", category: "general", boost_weight: 1.5 },
  // 単位
  { term: "mg", category: "general", boost_weight: 1.0 },
  { term: "mL", category: "general", boost_weight: 1.0 },
  { term: "μg", category: "general", boost_weight: 1.0 },
  { term: "IU", category: "general", boost_weight: 1.0 },
  { term: "錠", reading: "じょう", category: "general", boost_weight: 1.0 },
  { term: "カプセル", category: "general", boost_weight: 1.0 },
  { term: "包", reading: "ほう", category: "general", boost_weight: 1.0 },
  { term: "アンプル", category: "general", boost_weight: 1.0 },
  { term: "バイアル", category: "general", boost_weight: 1.0 },
  // カルテ用語
  { term: "主訴", reading: "しゅそ", category: "general", boost_weight: 1.5 },
  { term: "所見", reading: "しょけん", category: "general", boost_weight: 1.5 },
  { term: "理学所見", reading: "りがくしょけん", category: "general", boost_weight: 1.5 },
  { term: "視診", reading: "ししん", category: "general", boost_weight: 1.5 },
  { term: "触診", reading: "しょくしん", category: "general", boost_weight: 1.5 },
  { term: "聴診", reading: "ちょうしん", category: "general", boost_weight: 1.5 },
  { term: "打診", reading: "だしん", category: "general", boost_weight: 1.5 },
  { term: "経過観察", reading: "けいかかんさつ", category: "general", boost_weight: 1.5 },
  { term: "再診", reading: "さいしん", category: "general", boost_weight: 1.5 },
  { term: "初診", reading: "しょしん", category: "general", boost_weight: 1.5 },
  { term: "紹介状", reading: "しょうかいじょう", category: "general", boost_weight: 1.5 },
  { term: "同意書", reading: "どういしょ", category: "general", boost_weight: 1.0 },
  { term: "インフォームドコンセント", category: "general", boost_weight: 1.5 },
  { term: "SOAP", category: "general", boost_weight: 1.5 },
  { term: "問診", reading: "もんしん", category: "general", boost_weight: 1.5 },
  { term: "診察", reading: "しんさつ", category: "general", boost_weight: 1.5 },
  { term: "診断", reading: "しんだん", category: "general", boost_weight: 1.5 },
  { term: "鑑別診断", reading: "かんべつしんだん", category: "general", boost_weight: 1.5 },
  { term: "予後", reading: "よご", category: "general", boost_weight: 1.5 },
  { term: "寛解", reading: "かんかい", category: "general", boost_weight: 1.5 },
  { term: "増悪", reading: "ぞうあく", category: "general", boost_weight: 1.5 },
  { term: "改善", reading: "かいぜん", category: "general", boost_weight: 1.0 },
  { term: "悪化", reading: "あっか", category: "general", boost_weight: 1.0 },
  { term: "安静", reading: "あんせい", category: "general", boost_weight: 1.0 },
  // 共通症状
  { term: "発熱", reading: "はつねつ", category: "symptom", boost_weight: 1.5 },
  { term: "倦怠感", reading: "けんたいかん", category: "symptom", boost_weight: 1.5 },
  { term: "頭痛", reading: "ずつう", category: "symptom", boost_weight: 1.5 },
  { term: "めまい", category: "symptom", boost_weight: 1.5 },
  { term: "浮腫", reading: "ふしゅ", category: "symptom", boost_weight: 1.5 },
  { term: "むくみ", category: "symptom", boost_weight: 1.5 },
  { term: "疼痛", reading: "とうつう", category: "symptom", boost_weight: 1.5 },
  { term: "痛み", reading: "いたみ", category: "symptom", boost_weight: 1.0 },
  { term: "しびれ", category: "symptom", boost_weight: 1.5 },
  { term: "かゆみ", category: "symptom", boost_weight: 1.5 },
  { term: "発疹", reading: "ほっしん", category: "symptom", boost_weight: 1.5 },
  { term: "出血", reading: "しゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "脱水", reading: "だっすい", category: "symptom", boost_weight: 1.5 },
  { term: "黄疸", reading: "おうだん", category: "symptom", boost_weight: 2.0 },
  { term: "チアノーゼ", category: "symptom", boost_weight: 2.0 },
  // オンライン診療
  { term: "オンライン診療", reading: "おんらいんしんりょう", category: "general", boost_weight: 1.5 },
  { term: "遠隔診療", reading: "えんかくしんりょう", category: "general", boost_weight: 1.5 },
  { term: "対面診療", reading: "たいめんしんりょう", category: "general", boost_weight: 1.0 },
  { term: "自費診療", reading: "じひしんりょう", category: "general", boost_weight: 1.5 },
  { term: "自由診療", reading: "じゆうしんりょう", category: "general", boost_weight: 1.5 },
  { term: "保険診療", reading: "ほけんしんりょう", category: "general", boost_weight: 1.0 },
  { term: "配送", reading: "はいそう", category: "general", boost_weight: 1.0 },
  { term: "服薬指導", reading: "ふくやくしどう", category: "general", boost_weight: 1.5 },
  // 共通薬剤
  { term: "アセトアミノフェン", category: "drug", boost_weight: 1.5 },
  { term: "カロナール", category: "drug", boost_weight: 1.5 },
  { term: "イブプロフェン", category: "drug", boost_weight: 1.5 },
  { term: "抗生物質", reading: "こうせいぶっしつ", category: "drug", boost_weight: 1.5 },
  { term: "抗菌薬", reading: "こうきんやく", category: "drug", boost_weight: 1.5 },
  // --- 拡充: 処方日数・コンプライアンス・紹介 ---
  { term: "処方日数", reading: "しょほうにっすう", category: "general", boost_weight: 1.5 },
  { term: "7日分", reading: "なのかぶん", category: "general", boost_weight: 1.0 },
  { term: "14日分", reading: "じゅうよっかぶん", category: "general", boost_weight: 1.0 },
  { term: "28日分", reading: "にじゅうはちにちぶん", category: "general", boost_weight: 1.0 },
  { term: "30日分", reading: "さんじゅうにちぶん", category: "general", boost_weight: 1.0 },
  { term: "56日分", reading: "ごじゅうろくにちぶん", category: "general", boost_weight: 1.0 },
  { term: "90日分", reading: "きゅうじゅうにちぶん", category: "general", boost_weight: 1.0 },
  { term: "コンプライアンス", category: "general", boost_weight: 1.5 },
  { term: "アドヒアランス", category: "general", boost_weight: 1.5 },
  { term: "服薬コンプライアンス", reading: "ふくやくこんぷらいあんす", category: "general", boost_weight: 1.5 },
  { term: "紹介", reading: "しょうかい", category: "general", boost_weight: 1.0 },
  { term: "逆紹介", reading: "ぎゃくしょうかい", category: "general", boost_weight: 1.5 },
  { term: "対診", reading: "たいしん", category: "general", boost_weight: 1.5 },
  { term: "セカンドオピニオン", category: "general", boost_weight: 1.5 },
  { term: "入院", reading: "にゅういん", category: "general", boost_weight: 1.0 },
  { term: "退院", reading: "たいいん", category: "general", boost_weight: 1.0 },
  { term: "通院", reading: "つういん", category: "general", boost_weight: 1.0 },
  { term: "外来", reading: "がいらい", category: "general", boost_weight: 1.0 },
  { term: "レセプト", category: "general", boost_weight: 1.5 },
  { term: "診療報酬", reading: "しんりょうほうしゅう", category: "general", boost_weight: 1.5 },
  { term: "医療費", reading: "いりょうひ", category: "general", boost_weight: 1.0 },
  { term: "紹介先", reading: "しょうかいさき", category: "general", boost_weight: 1.0 },
  { term: "かかりつけ医", reading: "かかりつけい", category: "general", boost_weight: 1.5 },
  { term: "多剤併用", reading: "たざいへいよう", category: "general", boost_weight: 1.5 },
  { term: "ポリファーマシー", category: "general", boost_weight: 1.5 },
  { term: "残薬", reading: "ざんやく", category: "general", boost_weight: 1.0 },
  { term: "Do処方", reading: "どぅーしょほう", category: "general", boost_weight: 1.5 },
  { term: "疑義照会", reading: "ぎぎしょうかい", category: "general", boost_weight: 1.5 },
  { term: "一包化", reading: "いっぽうか", category: "general", boost_weight: 1.5 },
  { term: "分包", reading: "ぶんぽう", category: "general", boost_weight: 1.0 },
  { term: "粉砕", reading: "ふんさい", category: "general", boost_weight: 1.0 },
  { term: "半錠", reading: "はんじょう", category: "general", boost_weight: 1.0 },
  { term: "クリニカルパス", category: "general", boost_weight: 1.5 },
  { term: "ムンテラ", category: "general", boost_weight: 1.5 },
  { term: "IC", category: "general", boost_weight: 1.0 },
  { term: "DNR", category: "general", boost_weight: 1.5 },
  { term: "看取り", reading: "みとり", category: "general", boost_weight: 1.5 },
  { term: "訪問診療", reading: "ほうもんしんりょう", category: "general", boost_weight: 1.5 },
  { term: "在宅医療", reading: "ざいたくいりょう", category: "general", boost_weight: 1.5 },
  { term: "往診", reading: "おうしん", category: "general", boost_weight: 1.5 },
];
