// lib/voice/vocabulary/dermatology.ts — 皮膚科医療辞書
import type { VocabEntry } from "./types";

/** 皮膚科 */
export const DERMATOLOGY: VocabEntry[] = [
  // 疾患
  { term: "アトピー性皮膚炎", reading: "あとぴーせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "湿疹", reading: "しっしん", category: "symptom", boost_weight: 1.5 },
  { term: "蕁麻疹", reading: "じんましん", category: "symptom", boost_weight: 2.0 },
  { term: "慢性蕁麻疹", reading: "まんせいじんましん", category: "symptom", boost_weight: 2.0 },
  { term: "帯状疱疹", reading: "たいじょうほうしん", category: "symptom", boost_weight: 2.0 },
  { term: "帯状疱疹後神経痛", reading: "たいじょうほうしんごしんけいつう", category: "symptom", boost_weight: 2.0 },
  { term: "白癬", reading: "はくせん", category: "symptom", boost_weight: 2.0 },
  { term: "水虫", reading: "みずむし", category: "symptom", boost_weight: 1.5 },
  { term: "爪白癬", reading: "つめはくせん", category: "symptom", boost_weight: 2.0 },
  { term: "カンジダ症", reading: "かんじだしょう", category: "symptom", boost_weight: 2.0 },
  { term: "乾癬", reading: "かんせん", category: "symptom", boost_weight: 2.0 },
  { term: "尋常性乾癬", reading: "じんじょうせいかんせん", category: "symptom", boost_weight: 2.0 },
  { term: "脂漏性皮膚炎", reading: "しろうせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "接触性皮膚炎", reading: "せっしょくせいひふえん", category: "symptom", boost_weight: 2.0 },
  { term: "尋常性ざ瘡", reading: "じんじょうせいざそう", category: "symptom", boost_weight: 2.0 },
  { term: "酒さ", reading: "しゅさ", category: "symptom", boost_weight: 2.0 },
  { term: "円形脱毛症", reading: "えんけいだつもうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "粉瘤", reading: "ふんりゅう", category: "symptom", boost_weight: 2.0 },
  { term: "脂肪腫", reading: "しぼうしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "疣贅", reading: "ゆうぜい", category: "symptom", boost_weight: 2.0 },
  { term: "イボ", category: "symptom", boost_weight: 1.5 },
  { term: "ホクロ", category: "symptom", boost_weight: 1.5 },
  { term: "色素性母斑", reading: "しきそせいぼはん", category: "symptom", boost_weight: 2.0 },
  { term: "基底細胞癌", reading: "きていさいぼうがん", category: "symptom", boost_weight: 2.0 },
  { term: "悪性黒色腫", reading: "あくせいこくしょくしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "メラノーマ", category: "symptom", boost_weight: 2.0 },
  { term: "有棘細胞癌", reading: "ゆうきょくさいぼうがん", category: "symptom", boost_weight: 2.0 },
  { term: "ボーエン病", reading: "ぼーえんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "日光角化症", reading: "にっこうかくかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "多形滲出性紅斑", reading: "たけいしんしゅつせいこうはん", category: "symptom", boost_weight: 2.0 },
  { term: "薬疹", reading: "やくしん", category: "symptom", boost_weight: 2.0 },
  { term: "SJS", category: "symptom", boost_weight: 2.0 },
  { term: "天疱瘡", reading: "てんぽうそう", category: "symptom", boost_weight: 2.0 },
  { term: "類天疱瘡", reading: "るいてんぽうそう", category: "symptom", boost_weight: 2.0 },
  { term: "掌蹠膿疱症", reading: "しょうせきのうほうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "扁平苔癬", reading: "へんぺいたいせん", category: "symptom", boost_weight: 2.0 },
  { term: "紅斑", reading: "こうはん", category: "symptom", boost_weight: 1.5 },
  { term: "丘疹", reading: "きゅうしん", category: "symptom", boost_weight: 1.5 },
  { term: "水疱", reading: "すいほう", category: "symptom", boost_weight: 1.5 },
  { term: "膿疱", reading: "のうほう", category: "symptom", boost_weight: 1.5 },
  { term: "びらん", category: "symptom", boost_weight: 1.5 },
  { term: "潰瘍", reading: "かいよう", category: "symptom", boost_weight: 1.5 },
  { term: "鱗屑", reading: "りんせつ", category: "symptom", boost_weight: 1.5 },
  { term: "痂皮", reading: "かひ", category: "symptom", boost_weight: 1.5 },
  { term: "結節", reading: "けっせつ", category: "symptom", boost_weight: 1.5 },
  // 薬剤
  { term: "ステロイド外用", reading: "すてろいどがいよう", category: "drug", boost_weight: 2.0 },
  { term: "デルモベート", category: "drug", boost_weight: 2.0 },
  { term: "アンテベート", category: "drug", boost_weight: 2.0 },
  { term: "マイザー", category: "drug", boost_weight: 2.0 },
  { term: "リンデロン", category: "drug", boost_weight: 2.0 },
  { term: "ロコイド", category: "drug", boost_weight: 2.0 },
  { term: "キンダベート", category: "drug", boost_weight: 2.0 },
  { term: "プロトピック", category: "drug", boost_weight: 2.0 },
  { term: "タクロリムス", category: "drug", boost_weight: 2.0 },
  { term: "コレクチム", category: "drug", boost_weight: 2.0 },
  { term: "デルゴシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "モイゼルト", category: "drug", boost_weight: 2.0 },
  { term: "ジファミラスト", category: "drug", boost_weight: 2.0 },
  { term: "デュピクセント", category: "drug", boost_weight: 2.0 },
  { term: "デュピルマブ", category: "drug", boost_weight: 2.0 },
  { term: "ミチーガ", category: "drug", boost_weight: 2.0 },
  { term: "ネモリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "JAK阻害薬", reading: "じゃっくそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "オルミエント", category: "drug", boost_weight: 2.0 },
  { term: "バリシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "リンヴォック", category: "drug", boost_weight: 2.0 },
  { term: "ウパダシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "サイバインコ", category: "drug", boost_weight: 2.0 },
  { term: "アブロシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "ヒルドイド", category: "drug", boost_weight: 2.0 },
  { term: "ヘパリン類似物質", reading: "へぱりんるいじぶっしつ", category: "drug", boost_weight: 1.5 },
  { term: "保湿剤", reading: "ほしつざい", category: "drug", boost_weight: 1.0 },
  { term: "白色ワセリン", reading: "はくしょくわせりん", category: "drug", boost_weight: 1.0 },
  { term: "プロペト", category: "drug", boost_weight: 1.5 },
  { term: "抗ヒスタミン薬", reading: "こうひすたみんやく", category: "drug", boost_weight: 1.5 },
  { term: "アレグラ", category: "drug", boost_weight: 1.5 },
  { term: "ザイザル", category: "drug", boost_weight: 1.5 },
  { term: "クラリチン", category: "drug", boost_weight: 1.5 },
  { term: "ロラタジン", category: "drug", boost_weight: 1.5 },
  { term: "アシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "バラシクロビル", category: "drug", boost_weight: 2.0 },
  { term: "アメナメビル", category: "drug", boost_weight: 2.0 },
  { term: "アメナリーフ", category: "drug", boost_weight: 2.0 },
  { term: "抗真菌薬", reading: "こうしんきんやく", category: "drug", boost_weight: 1.5 },
  { term: "テルビナフィン", category: "drug", boost_weight: 2.0 },
  { term: "ラミシール", category: "drug", boost_weight: 2.0 },
  { term: "イトラコナゾール", category: "drug", boost_weight: 2.0 },
  { term: "イトリゾール", category: "drug", boost_weight: 2.0 },
  { term: "ルコナック", category: "drug", boost_weight: 2.0 },
  { term: "クレナフィン", category: "drug", boost_weight: 2.0 },
  { term: "ディフェリン", category: "drug", boost_weight: 2.0 },
  { term: "アダパレン", category: "drug", boost_weight: 2.0 },
  { term: "ベピオ", category: "drug", boost_weight: 2.0 },
  { term: "過酸化ベンゾイル", reading: "かさんかべんぞいる", category: "drug", boost_weight: 2.0 },
  { term: "エピデュオ", category: "drug", boost_weight: 2.0 },
  { term: "デュアック", category: "drug", boost_weight: 2.0 },
  { term: "イソトレチノイン", category: "drug", boost_weight: 2.0 },
  { term: "オテズラ", category: "drug", boost_weight: 2.0 },
  { term: "アプレミラスト", category: "drug", boost_weight: 2.0 },
  // 処置
  { term: "光線療法", reading: "こうせんりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "ナローバンドUVB", category: "procedure", boost_weight: 2.0 },
  { term: "エキシマレーザー", category: "procedure", boost_weight: 2.0 },
  { term: "PUVA", category: "procedure", boost_weight: 2.0 },
  { term: "液体窒素", reading: "えきたいちっそ", category: "procedure", boost_weight: 2.0 },
  { term: "凍結療法", reading: "とうけつりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "パッチテスト", category: "procedure", boost_weight: 1.5 },
  { term: "プリックテスト", category: "procedure", boost_weight: 1.5 },
  { term: "ダーモスコピー", category: "procedure", boost_weight: 2.0 },
  { term: "皮膚生検", reading: "ひふせいけん", category: "procedure", boost_weight: 2.0 },
  { term: "KOH検査", reading: "けーおーえいちけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "ウッド灯", reading: "うっどとう", category: "procedure", boost_weight: 1.5 },
  { term: "電気凝固", reading: "でんきぎょうこ", category: "procedure", boost_weight: 1.5 },
  { term: "切除術", reading: "せつじょじゅつ", category: "procedure", boost_weight: 1.5 },
  // --- 拡充: 新生物学的製剤・乾癬治療薬 ---
  { term: "スキリージ", category: "drug", boost_weight: 2.0 },
  { term: "リサンキズマブ", category: "drug", boost_weight: 2.0 },
  { term: "トレムフィア", category: "drug", boost_weight: 2.0 },
  { term: "グセルクマブ", category: "drug", boost_weight: 2.0 },
  { term: "コセンティクス", category: "drug", boost_weight: 2.0 },
  { term: "セクキヌマブ", category: "drug", boost_weight: 2.0 },
  { term: "ルミセフ", category: "drug", boost_weight: 2.0 },
  { term: "ブロダルマブ", category: "drug", boost_weight: 2.0 },
  { term: "タルツ", category: "drug", boost_weight: 2.0 },
  { term: "イキセキズマブ", category: "drug", boost_weight: 2.0 },
  { term: "ビンゼレックス", category: "drug", boost_weight: 2.0 },
  { term: "ビメキズマブ", category: "drug", boost_weight: 2.0 },
  { term: "ステラーラ", category: "drug", boost_weight: 2.0 },
  { term: "ウステキヌマブ", category: "drug", boost_weight: 2.0 },
  { term: "ゾレア", category: "drug", boost_weight: 2.0 },
  { term: "オマリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "ソーティクツ", category: "drug", boost_weight: 2.0 },
  { term: "デュークラバシチニブ", category: "drug", boost_weight: 2.0 },
  { term: "リットフーロ", category: "drug", boost_weight: 2.0 },
  { term: "リトレシチニブ", category: "drug", boost_weight: 2.0 },
  // 皮膚科追加疾患
  { term: "汗疱", reading: "かんぽう", category: "symptom", boost_weight: 2.0 },
  { term: "異汗性湿疹", reading: "いかんせいしっしん", category: "symptom", boost_weight: 2.0 },
  { term: "貨幣状湿疹", reading: "かへいじょうしっしん", category: "symptom", boost_weight: 2.0 },
  { term: "手湿疹", reading: "てしっしん", category: "symptom", boost_weight: 1.5 },
  { term: "皮脂欠乏性湿疹", reading: "ひしけつぼうせいしっしん", category: "symptom", boost_weight: 2.0 },
  { term: "毛孔性苔癬", reading: "もうこうせいたいせん", category: "symptom", boost_weight: 2.0 },
  { term: "伝染性軟属腫", reading: "でんせんせいなんぞくしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "水いぼ", reading: "みずいぼ", category: "symptom", boost_weight: 1.5 },
  { term: "とびひ", category: "symptom", boost_weight: 1.5 },
  { term: "伝染性膿痂疹", reading: "でんせんせいのうかしん", category: "symptom", boost_weight: 2.0 },
  { term: "皮膚リンパ腫", reading: "ひふりんぱしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "菌状息肉症", reading: "きんじょうそくにくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "白斑", reading: "はくはん", category: "symptom", boost_weight: 2.0 },
  { term: "尋常性白斑", reading: "じんじょうせいはくはん", category: "symptom", boost_weight: 2.0 },
  { term: "EASI", category: "lab", boost_weight: 2.0 },
  { term: "SCORAD", category: "lab", boost_weight: 2.0 },
  { term: "PASI", category: "lab", boost_weight: 2.0 },
  { term: "IGA", category: "lab", boost_weight: 1.5 },
  { term: "TARC", category: "lab", boost_weight: 2.0 },
  { term: "IgE", category: "lab", boost_weight: 1.5 },
];
