// lib/voice/vocabulary/ent.ts — 耳鼻咽喉科医療辞書
import type { VocabEntry } from "./types";

/** 耳鼻咽喉科 */
export const ENT: VocabEntry[] = [
  // 耳疾患
  { term: "中耳炎", reading: "ちゅうじえん", category: "symptom", boost_weight: 2.0 },
  { term: "急性中耳炎", reading: "きゅうせいちゅうじえん", category: "symptom", boost_weight: 2.0 },
  { term: "慢性中耳炎", reading: "まんせいちゅうじえん", category: "symptom", boost_weight: 2.0 },
  { term: "滲出性中耳炎", reading: "しんしゅつせいちゅうじえん", category: "symptom", boost_weight: 2.0 },
  { term: "真珠腫性中耳炎", reading: "しんじゅしゅせいちゅうじえん", category: "symptom", boost_weight: 2.0 },
  { term: "外耳炎", reading: "がいじえん", category: "symptom", boost_weight: 1.5 },
  { term: "突発性難聴", reading: "とっぱつせいなんちょう", category: "symptom", boost_weight: 2.0 },
  { term: "感音性難聴", reading: "かんおんせいなんちょう", category: "symptom", boost_weight: 2.0 },
  { term: "伝音性難聴", reading: "でんおんせいなんちょう", category: "symptom", boost_weight: 2.0 },
  { term: "加齢性難聴", reading: "かれいせいなんちょう", category: "symptom", boost_weight: 2.0 },
  { term: "耳鳴り", reading: "みみなり", category: "symptom", boost_weight: 1.5 },
  { term: "耳鳴", reading: "じめい", category: "symptom", boost_weight: 1.5 },
  { term: "メニエール病", reading: "めにえーるびょう", category: "symptom", boost_weight: 2.0 },
  { term: "良性発作性頭位めまい症", reading: "りょうせいほっさせいとういめまいしょう", category: "symptom", boost_weight: 2.0 },
  { term: "BPPV", category: "symptom", boost_weight: 2.0 },
  { term: "前庭神経炎", reading: "ぜんていしんけいえん", category: "symptom", boost_weight: 2.0 },
  { term: "耳硬化症", reading: "じこうかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "顔面神経麻痺", reading: "がんめんしんけいまひ", category: "symptom", boost_weight: 2.0 },
  { term: "ベル麻痺", reading: "べるまひ", category: "symptom", boost_weight: 2.0 },
  { term: "ハント症候群", reading: "はんとしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "聴神経腫瘍", reading: "ちょうしんけいしゅよう", category: "symptom", boost_weight: 2.0 },
  // 鼻疾患
  { term: "副鼻腔炎", reading: "ふくびくうえん", category: "symptom", boost_weight: 2.0 },
  { term: "急性副鼻腔炎", reading: "きゅうせいふくびくうえん", category: "symptom", boost_weight: 2.0 },
  { term: "慢性副鼻腔炎", reading: "まんせいふくびくうえん", category: "symptom", boost_weight: 2.0 },
  { term: "蓄膿症", reading: "ちくのうしょう", category: "symptom", boost_weight: 1.5 },
  { term: "鼻茸", reading: "はなたけ", category: "symptom", boost_weight: 2.0 },
  { term: "鼻ポリープ", reading: "はなぽりーぷ", category: "symptom", boost_weight: 2.0 },
  { term: "好酸球性副鼻腔炎", reading: "こうさんきゅうせいふくびくうえん", category: "symptom", boost_weight: 2.0 },
  { term: "アレルギー性鼻炎", reading: "あれるぎーせいびえん", category: "symptom", boost_weight: 2.0 },
  { term: "花粉症", reading: "かふんしょう", category: "symptom", boost_weight: 1.5 },
  { term: "鼻中隔弯曲症", reading: "びちゅうかくわんきょくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "鼻出血", reading: "びしゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "鼻閉", reading: "びへい", category: "symptom", boost_weight: 1.5 },
  { term: "後鼻漏", reading: "こうびろう", category: "symptom", boost_weight: 2.0 },
  { term: "嗅覚障害", reading: "きゅうかくしょうがい", category: "symptom", boost_weight: 2.0 },
  // 咽喉頭疾患
  { term: "扁桃炎", reading: "へんとうえん", category: "symptom", boost_weight: 2.0 },
  { term: "急性扁桃炎", reading: "きゅうせいへんとうえん", category: "symptom", boost_weight: 2.0 },
  { term: "扁桃周囲膿瘍", reading: "へんとうしゅういのうよう", category: "symptom", boost_weight: 2.0 },
  { term: "咽頭炎", reading: "いんとうえん", category: "symptom", boost_weight: 1.5 },
  { term: "喉頭炎", reading: "こうとうえん", category: "symptom", boost_weight: 1.5 },
  { term: "声帯ポリープ", reading: "せいたいぽりーぷ", category: "symptom", boost_weight: 2.0 },
  { term: "声帯結節", reading: "せいたいけっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "喉頭癌", reading: "こうとうがん", category: "symptom", boost_weight: 2.0 },
  { term: "咽頭癌", reading: "いんとうがん", category: "symptom", boost_weight: 2.0 },
  { term: "上咽頭癌", reading: "じょういんとうがん", category: "symptom", boost_weight: 2.0 },
  { term: "中咽頭癌", reading: "ちゅういんとうがん", category: "symptom", boost_weight: 2.0 },
  { term: "下咽頭癌", reading: "かいんとうがん", category: "symptom", boost_weight: 2.0 },
  { term: "嗄声", reading: "させい", category: "symptom", boost_weight: 2.0 },
  { term: "反回神経麻痺", reading: "はんかいしんけいまひ", category: "symptom", boost_weight: 2.0 },
  { term: "睡眠時無呼吸症候群", reading: "すいみんじむこきゅうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "SAS", category: "symptom", boost_weight: 2.0 },
  { term: "アデノイド", category: "symptom", boost_weight: 1.5 },
  { term: "いびき", category: "symptom", boost_weight: 1.5 },
  { term: "唾液腺腫瘍", reading: "だえきせんしゅよう", category: "symptom", boost_weight: 2.0 },
  { term: "耳下腺腫瘍", reading: "じかせんしゅよう", category: "symptom", boost_weight: 2.0 },
  { term: "唾石", reading: "だせき", category: "symptom", boost_weight: 2.0 },
  // 薬剤
  { term: "ナゾネックス", category: "drug", boost_weight: 2.0 },
  { term: "モメタゾン", category: "drug", boost_weight: 2.0 },
  { term: "アラミスト", category: "drug", boost_weight: 2.0 },
  { term: "フルチカゾン", category: "drug", boost_weight: 2.0 },
  { term: "リンデロン点耳", reading: "りんでろんてんじ", category: "drug", boost_weight: 2.0 },
  { term: "タリビッド耳科用液", reading: "たりびっどじかようえき", category: "drug", boost_weight: 2.0 },
  { term: "オフロキサシン点耳", reading: "おふろきさしんてんじ", category: "drug", boost_weight: 2.0 },
  { term: "クラリスロマイシン", category: "drug", boost_weight: 2.0 },
  { term: "マクロライド少量長期療法", reading: "まくろらいどしょうりょうちょうきりょうほう", category: "drug", boost_weight: 2.0 },
  { term: "デュピクセント", category: "drug", boost_weight: 2.0 },
  { term: "ヌーカラ", category: "drug", boost_weight: 2.0 },
  { term: "メポリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "プレドニゾロン", category: "drug", boost_weight: 2.0 },
  { term: "ステロイド鼓室内注入", reading: "すてろいどこしつないちゅうにゅう", category: "procedure", boost_weight: 2.0 },
  { term: "メリスロン", category: "drug", boost_weight: 2.0 },
  { term: "ベタヒスチン", category: "drug", boost_weight: 2.0 },
  { term: "アデホスコーワ", category: "drug", boost_weight: 2.0 },
  { term: "イソバイド", category: "drug", boost_weight: 2.0 },
  { term: "イソソルビド", category: "drug", boost_weight: 2.0 },
  { term: "カルボシステイン", category: "drug", boost_weight: 2.0 },
  { term: "ムコダイン", category: "drug", boost_weight: 2.0 },
  // 検査
  { term: "純音聴力検査", reading: "じゅんおんちょうりょくけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "オージオメトリー", category: "procedure", boost_weight: 2.0 },
  { term: "ABR", category: "procedure", boost_weight: 2.0 },
  { term: "聴性脳幹反応", reading: "ちょうせいのうかんはんのう", category: "procedure", boost_weight: 2.0 },
  { term: "ティンパノメトリー", category: "procedure", boost_weight: 2.0 },
  { term: "鼻咽腔ファイバー", reading: "びいんくうふぁいばー", category: "procedure", boost_weight: 2.0 },
  { term: "喉頭ファイバー", reading: "こうとうふぁいばー", category: "procedure", boost_weight: 2.0 },
  { term: "電子スコープ", category: "procedure", boost_weight: 1.5 },
  { term: "副鼻腔CT", reading: "ふくびくうしーてぃー", category: "procedure", boost_weight: 2.0 },
  { term: "重心動揺検査", reading: "じゅうしんどうようけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "カロリックテスト", category: "procedure", boost_weight: 2.0 },
  { term: "ENG", category: "procedure", boost_weight: 2.0 },
  // 処置・手術
  { term: "ESS", category: "procedure", boost_weight: 2.0 },
  { term: "内視鏡下副鼻腔手術", reading: "ないしきょうかふくびくうしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "鼓膜チューブ留置", reading: "こまくちゅーぶりゅうち", category: "procedure", boost_weight: 2.0 },
  { term: "鼓膜切開", reading: "こまくせっかい", category: "procedure", boost_weight: 2.0 },
  { term: "扁桃摘出術", reading: "へんとうてきしゅつじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "アデノイド切除術", reading: "あでのいどせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "鼻中隔矯正術", reading: "びちゅうかくきょうせいじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "下鼻甲介手術", reading: "かびこうかいしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "レーザー下鼻甲介手術", reading: "れーざーかびこうかいしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "喉頭微細手術", reading: "こうとうびさいしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "Epley法", reading: "えぷりーほう", category: "procedure", boost_weight: 2.0 },
  { term: "耳管開放症", reading: "じかんかいほうしょう", category: "symptom", boost_weight: 2.0 },
  // 解剖
  { term: "鼓膜", reading: "こまく", category: "anatomy", boost_weight: 1.5 },
  { term: "内耳", reading: "ないじ", category: "anatomy", boost_weight: 1.5 },
  { term: "中耳", reading: "ちゅうじ", category: "anatomy", boost_weight: 1.5 },
  { term: "外耳", reading: "がいじ", category: "anatomy", boost_weight: 1.5 },
  { term: "耳小骨", reading: "じしょうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "蝸牛", reading: "かぎゅう", category: "anatomy", boost_weight: 2.0 },
  { term: "前庭", reading: "ぜんてい", category: "anatomy", boost_weight: 1.5 },
  { term: "半規管", reading: "はんきかん", category: "anatomy", boost_weight: 2.0 },
  { term: "副鼻腔", reading: "ふくびくう", category: "anatomy", boost_weight: 1.5 },
  { term: "上顎洞", reading: "じょうがくどう", category: "anatomy", boost_weight: 2.0 },
  { term: "篩骨洞", reading: "しこつどう", category: "anatomy", boost_weight: 2.0 },
  { term: "前頭洞", reading: "ぜんとうどう", category: "anatomy", boost_weight: 2.0 },
  { term: "蝶形骨洞", reading: "ちょうけいこつどう", category: "anatomy", boost_weight: 2.0 },
  { term: "声帯", reading: "せいたい", category: "anatomy", boost_weight: 1.5 },
  { term: "喉頭蓋", reading: "こうとうがい", category: "anatomy", boost_weight: 2.0 },
  { term: "咽頭", reading: "いんとう", category: "anatomy", boost_weight: 1.5 },
  { term: "喉頭", reading: "こうとう", category: "anatomy", boost_weight: 1.5 },
  { term: "扁桃", reading: "へんとう", category: "anatomy", boost_weight: 1.5 },
  { term: "耳管", reading: "じかん", category: "anatomy", boost_weight: 1.5 },
];
