// lib/voice/vocabulary/internal.ts — 内科医療辞書
import type { VocabEntry } from "./types";

/** 内科 */
export const INTERNAL: VocabEntry[] = [
  // 糖尿病
  { term: "糖尿病", reading: "とうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "1型糖尿病", reading: "いちがたとうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "2型糖尿病", reading: "にがたとうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "HbA1c", category: "lab", boost_weight: 2.0 },
  { term: "血糖値", reading: "けっとうち", category: "lab", boost_weight: 1.5 },
  { term: "空腹時血糖", reading: "くうふくじけっとう", category: "lab", boost_weight: 1.5 },
  { term: "食後血糖", reading: "しょくごけっとう", category: "lab", boost_weight: 1.5 },
  { term: "インスリン", category: "drug", boost_weight: 2.0 },
  { term: "インスリン抵抗性", reading: "いんすりんていこうせい", category: "symptom", boost_weight: 1.5 },
  { term: "メトホルミン", category: "drug", boost_weight: 2.0 },
  { term: "メトグルコ", category: "drug", boost_weight: 2.0 },
  { term: "SGLT2阻害薬", reading: "えすじーえるてぃーつーそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "フォシーガ", category: "drug", boost_weight: 2.0 },
  { term: "ジャディアンス", category: "drug", boost_weight: 2.0 },
  { term: "DPP-4阻害薬", reading: "でぃーぴーぴーよんそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "ジャヌビア", category: "drug", boost_weight: 2.0 },
  { term: "エクア", category: "drug", boost_weight: 2.0 },
  { term: "トラゼンタ", category: "drug", boost_weight: 2.0 },
  { term: "SU剤", reading: "えすゆーざい", category: "drug", boost_weight: 1.5 },
  { term: "グリメピリド", category: "drug", boost_weight: 2.0 },
  { term: "α-グルコシダーゼ阻害薬", category: "drug", boost_weight: 1.5 },
  { term: "ボグリボース", category: "drug", boost_weight: 2.0 },
  { term: "糖尿病性腎症", reading: "とうにょうびょうせいじんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "糖尿病性網膜症", reading: "とうにょうびょうせいもうまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "糖尿病性神経障害", reading: "とうにょうびょうせいしんけいしょうがい", category: "symptom", boost_weight: 2.0 },
  // 高血圧
  { term: "高血圧", reading: "こうけつあつ", category: "symptom", boost_weight: 2.0 },
  { term: "本態性高血圧", reading: "ほんたいせいこうけつあつ", category: "symptom", boost_weight: 2.0 },
  { term: "降圧薬", reading: "こうあつやく", category: "drug", boost_weight: 1.5 },
  { term: "ARB", category: "drug", boost_weight: 2.0 },
  { term: "ACE阻害薬", reading: "えーすそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "Ca拮抗薬", reading: "かるしうむきっこうやく", category: "drug", boost_weight: 2.0 },
  { term: "アムロジピン", category: "drug", boost_weight: 2.0 },
  { term: "ノルバスク", category: "drug", boost_weight: 2.0 },
  { term: "オルメサルタン", category: "drug", boost_weight: 2.0 },
  { term: "オルメテック", category: "drug", boost_weight: 2.0 },
  { term: "テルミサルタン", category: "drug", boost_weight: 2.0 },
  { term: "ミカルディス", category: "drug", boost_weight: 2.0 },
  { term: "バルサルタン", category: "drug", boost_weight: 2.0 },
  { term: "ニフェジピン", category: "drug", boost_weight: 2.0 },
  { term: "利尿薬", reading: "りにょうやく", category: "drug", boost_weight: 1.5 },
  { term: "β遮断薬", reading: "べーたしゃだんやく", category: "drug", boost_weight: 2.0 },
  { term: "ビソプロロール", category: "drug", boost_weight: 2.0 },
  // 脂質異常
  { term: "脂質異常症", reading: "ししついじょうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "高脂血症", reading: "こうしけっしょう", category: "symptom", boost_weight: 2.0 },
  { term: "LDLコレステロール", category: "lab", boost_weight: 2.0 },
  { term: "HDLコレステロール", category: "lab", boost_weight: 2.0 },
  { term: "中性脂肪", reading: "ちゅうせいしぼう", category: "lab", boost_weight: 1.5 },
  { term: "トリグリセリド", category: "lab", boost_weight: 1.5 },
  { term: "スタチン", category: "drug", boost_weight: 2.0 },
  { term: "ロスバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "クレストール", category: "drug", boost_weight: 2.0 },
  { term: "アトルバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "リピトール", category: "drug", boost_weight: 2.0 },
  { term: "プラバスタチン", category: "drug", boost_weight: 2.0 },
  { term: "フィブラート", category: "drug", boost_weight: 1.5 },
  { term: "エゼチミブ", category: "drug", boost_weight: 2.0 },
  { term: "ゼチーア", category: "drug", boost_weight: 2.0 },
  { term: "動脈硬化", reading: "どうみゃくこうか", category: "symptom", boost_weight: 1.5 },
  // 消化器
  { term: "逆流性食道炎", reading: "ぎゃくりゅうせいしょくどうえん", category: "symptom", boost_weight: 2.0 },
  { term: "胃潰瘍", reading: "いかいよう", category: "symptom", boost_weight: 2.0 },
  { term: "十二指腸潰瘍", reading: "じゅうにしちょうかいよう", category: "symptom", boost_weight: 2.0 },
  { term: "機能性ディスペプシア", category: "symptom", boost_weight: 2.0 },
  { term: "過敏性腸症候群", reading: "かびんせいちょうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "IBS", category: "symptom", boost_weight: 2.0 },
  { term: "潰瘍性大腸炎", reading: "かいようせいだいちょうえん", category: "symptom", boost_weight: 2.0 },
  { term: "クローン病", reading: "くろーんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "脂肪肝", reading: "しぼうかん", category: "symptom", boost_weight: 1.5 },
  { term: "肝硬変", reading: "かんこうへん", category: "symptom", boost_weight: 2.0 },
  { term: "肝炎", reading: "かんえん", category: "symptom", boost_weight: 1.5 },
  { term: "B型肝炎", reading: "びーがたかんえん", category: "symptom", boost_weight: 2.0 },
  { term: "C型肝炎", reading: "しーがたかんえん", category: "symptom", boost_weight: 2.0 },
  { term: "膵炎", reading: "すいえん", category: "symptom", boost_weight: 2.0 },
  { term: "胆石", reading: "たんせき", category: "symptom", boost_weight: 1.5 },
  { term: "PPI", category: "drug", boost_weight: 2.0 },
  { term: "ランソプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "タケプロン", category: "drug", boost_weight: 2.0 },
  { term: "エソメプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "ネキシウム", category: "drug", boost_weight: 2.0 },
  { term: "ラベプラゾール", category: "drug", boost_weight: 2.0 },
  { term: "パリエット", category: "drug", boost_weight: 2.0 },
  { term: "ボノプラザン", category: "drug", boost_weight: 2.0 },
  { term: "タケキャブ", category: "drug", boost_weight: 2.0 },
  { term: "H2ブロッカー", category: "drug", boost_weight: 1.5 },
  { term: "ファモチジン", category: "drug", boost_weight: 2.0 },
  { term: "ヘリコバクターピロリ", category: "symptom", boost_weight: 2.0 },
  { term: "ピロリ菌", reading: "ぴろりきん", category: "symptom", boost_weight: 1.5 },
  { term: "除菌", reading: "じょきん", category: "procedure", boost_weight: 1.5 },
  { term: "胃カメラ", reading: "いかめら", category: "procedure", boost_weight: 1.5 },
  { term: "上部消化管内視鏡", reading: "じょうぶしょうかかんないしきょう", category: "procedure", boost_weight: 2.0 },
  { term: "大腸カメラ", reading: "だいちょうかめら", category: "procedure", boost_weight: 1.5 },
  { term: "下部消化管内視鏡", reading: "かぶしょうかかんないしきょう", category: "procedure", boost_weight: 2.0 },
  { term: "腹部エコー", reading: "ふくぶえこー", category: "procedure", boost_weight: 1.5 },
  // 呼吸器
  { term: "喘息", reading: "ぜんそく", category: "symptom", boost_weight: 2.0 },
  { term: "気管支喘息", reading: "きかんしぜんそく", category: "symptom", boost_weight: 2.0 },
  { term: "COPD", category: "symptom", boost_weight: 2.0 },
  { term: "慢性閉塞性肺疾患", reading: "まんせいへいそくせいはいしっかん", category: "symptom", boost_weight: 2.0 },
  { term: "肺炎", reading: "はいえん", category: "symptom", boost_weight: 2.0 },
  { term: "間質性肺炎", reading: "かんしつせいはいえん", category: "symptom", boost_weight: 2.0 },
  { term: "気管支炎", reading: "きかんしえん", category: "symptom", boost_weight: 1.5 },
  { term: "肺気腫", reading: "はいきしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "睡眠時無呼吸症候群", reading: "すいみんじむこきゅうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "SAS", category: "symptom", boost_weight: 2.0 },
  { term: "CPAP", category: "procedure", boost_weight: 2.0 },
  { term: "吸入薬", reading: "きゅうにゅうやく", category: "drug", boost_weight: 1.5 },
  { term: "ICS", category: "drug", boost_weight: 1.5 },
  { term: "LABA", category: "drug", boost_weight: 1.5 },
  { term: "LAMA", category: "drug", boost_weight: 1.5 },
  { term: "モンテルカスト", category: "drug", boost_weight: 2.0 },
  { term: "シングレア", category: "drug", boost_weight: 2.0 },
  { term: "テオフィリン", category: "drug", boost_weight: 2.0 },
  // 循環器
  { term: "心電図", reading: "しんでんず", category: "procedure", boost_weight: 1.5 },
  { term: "心エコー", reading: "しんえこー", category: "procedure", boost_weight: 1.5 },
  { term: "ホルター心電図", reading: "ほるたーしんでんず", category: "procedure", boost_weight: 2.0 },
  { term: "心房細動", reading: "しんぼうさいどう", category: "symptom", boost_weight: 2.0 },
  { term: "Af", category: "symptom", boost_weight: 2.0 },
  { term: "不整脈", reading: "ふせいみゃく", category: "symptom", boost_weight: 1.5 },
  { term: "心不全", reading: "しんふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "狭心症", reading: "きょうしんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "心筋梗塞", reading: "しんきんこうそく", category: "symptom", boost_weight: 2.0 },
  { term: "弁膜症", reading: "べんまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "大動脈瘤", reading: "だいどうみゃくりゅう", category: "symptom", boost_weight: 2.0 },
  { term: "深部静脈血栓症", reading: "しんぶじょうみゃくけっせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "DVT", category: "symptom", boost_weight: 2.0 },
  { term: "肺塞栓", reading: "はいそくせん", category: "symptom", boost_weight: 2.0 },
  { term: "ワーファリン", category: "drug", boost_weight: 2.0 },
  { term: "DOAC", category: "drug", boost_weight: 2.0 },
  { term: "エドキサバン", category: "drug", boost_weight: 2.0 },
  { term: "リクシアナ", category: "drug", boost_weight: 2.0 },
  { term: "アピキサバン", category: "drug", boost_weight: 2.0 },
  { term: "エリキュース", category: "drug", boost_weight: 2.0 },
  { term: "リバーロキサバン", category: "drug", boost_weight: 2.0 },
  { term: "イグザレルト", category: "drug", boost_weight: 2.0 },
  { term: "BNP", category: "lab", boost_weight: 2.0 },
  { term: "NT-proBNP", category: "lab", boost_weight: 2.0 },
  { term: "トロポニン", category: "lab", boost_weight: 2.0 },
  { term: "Dダイマー", category: "lab", boost_weight: 2.0 },
  // 腎臓
  { term: "慢性腎臓病", reading: "まんせいじんぞうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "CKD", category: "symptom", boost_weight: 2.0 },
  { term: "腎不全", reading: "じんふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "透析", reading: "とうせき", category: "procedure", boost_weight: 2.0 },
  { term: "ネフローゼ症候群", category: "symptom", boost_weight: 2.0 },
  { term: "蛋白尿", reading: "たんぱくにょう", category: "lab", boost_weight: 1.5 },
  { term: "血尿", reading: "けつにょう", category: "lab", boost_weight: 1.5 },
  // 内分泌
  { term: "甲状腺", reading: "こうじょうせん", category: "anatomy", boost_weight: 1.5 },
  { term: "甲状腺機能亢進症", reading: "こうじょうせんきのうこうしんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "バセドウ病", reading: "ばせどうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "甲状腺機能低下症", reading: "こうじょうせんきのうていかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "橋本病", reading: "はしもとびょう", category: "symptom", boost_weight: 2.0 },
  { term: "チラーヂン", category: "drug", boost_weight: 2.0 },
  { term: "レボチロキシン", category: "drug", boost_weight: 2.0 },
  { term: "痛風", reading: "つうふう", category: "symptom", boost_weight: 2.0 },
  { term: "高尿酸血症", reading: "こうにょうさんけっしょう", category: "symptom", boost_weight: 2.0 },
  { term: "フェブキソスタット", category: "drug", boost_weight: 2.0 },
  { term: "フェブリク", category: "drug", boost_weight: 2.0 },
  { term: "アロプリノール", category: "drug", boost_weight: 2.0 },
  { term: "コルヒチン", category: "drug", boost_weight: 2.0 },
  // 感染症
  { term: "インフルエンザ", category: "symptom", boost_weight: 1.5 },
  { term: "タミフル", category: "drug", boost_weight: 2.0 },
  { term: "オセルタミビル", category: "drug", boost_weight: 2.0 },
  { term: "新型コロナ", reading: "しんがたころな", category: "symptom", boost_weight: 1.5 },
  { term: "COVID-19", category: "symptom", boost_weight: 1.5 },
  { term: "ラゲブリオ", category: "drug", boost_weight: 2.0 },
  { term: "ゾコーバ", category: "drug", boost_weight: 2.0 },
  { term: "ワクチン", category: "drug", boost_weight: 1.0 },
  { term: "尿路感染症", reading: "にょうろかんせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "膀胱炎", reading: "ぼうこうえん", category: "symptom", boost_weight: 1.5 },
  { term: "腎盂腎炎", reading: "じんうじんえん", category: "symptom", boost_weight: 2.0 },
  // 抗菌薬
  { term: "アモキシシリン", category: "drug", boost_weight: 2.0 },
  { term: "サワシリン", category: "drug", boost_weight: 2.0 },
  { term: "クラリスロマイシン", category: "drug", boost_weight: 2.0 },
  { term: "クラリス", category: "drug", boost_weight: 2.0 },
  { term: "アジスロマイシン", category: "drug", boost_weight: 2.0 },
  { term: "ジスロマック", category: "drug", boost_weight: 2.0 },
  { term: "セフカペンピボキシル", category: "drug", boost_weight: 2.0 },
  { term: "フロモックス", category: "drug", boost_weight: 2.0 },
  { term: "レボフロキサシン", category: "drug", boost_weight: 2.0 },
  { term: "クラビット", category: "drug", boost_weight: 2.0 },
  // 神経
  { term: "脳梗塞", reading: "のうこうそく", category: "symptom", boost_weight: 2.0 },
  { term: "脳出血", reading: "のうしゅっけつ", category: "symptom", boost_weight: 2.0 },
  { term: "くも膜下出血", reading: "くもまくかしゅっけつ", category: "symptom", boost_weight: 2.0 },
  { term: "パーキンソン病", category: "symptom", boost_weight: 2.0 },
  { term: "てんかん", category: "symptom", boost_weight: 2.0 },
  { term: "認知症", reading: "にんちしょう", category: "symptom", boost_weight: 2.0 },
  { term: "アルツハイマー", category: "symptom", boost_weight: 2.0 },
  { term: "片頭痛", reading: "へんずつう", category: "symptom", boost_weight: 1.5 },
  { term: "トリプタン", category: "drug", boost_weight: 2.0 },
  // アレルギー
  { term: "花粉症", reading: "かふんしょう", category: "symptom", boost_weight: 1.5 },
  { term: "アレルギー性鼻炎", reading: "あれるぎーせいびえん", category: "symptom", boost_weight: 2.0 },
  { term: "抗アレルギー薬", reading: "こうあれるぎーやく", category: "drug", boost_weight: 1.5 },
  { term: "フェキソフェナジン", category: "drug", boost_weight: 2.0 },
  { term: "ビラノア", category: "drug", boost_weight: 2.0 },
  { term: "デザレックス", category: "drug", boost_weight: 2.0 },
  { term: "ルパフィン", category: "drug", boost_weight: 2.0 },
  { term: "モンテルカスト", category: "drug", boost_weight: 2.0 },
  // 精神科（オンライン診療で多い）
  { term: "不眠症", reading: "ふみんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "不眠", reading: "ふみん", category: "symptom", boost_weight: 1.5 },
  { term: "睡眠障害", reading: "すいみんしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "うつ病", reading: "うつびょう", category: "symptom", boost_weight: 2.0 },
  { term: "適応障害", reading: "てきおうしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "不安障害", reading: "ふあんしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "パニック障害", reading: "ぱにっくしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "SSRI", category: "drug", boost_weight: 2.0 },
  { term: "SNRI", category: "drug", boost_weight: 2.0 },
  { term: "レクサプロ", category: "drug", boost_weight: 2.0 },
  { term: "エスシタロプラム", category: "drug", boost_weight: 2.0 },
  { term: "サインバルタ", category: "drug", boost_weight: 2.0 },
  { term: "デュロキセチン", category: "drug", boost_weight: 2.0 },
  { term: "ベンゾジアゼピン", category: "drug", boost_weight: 2.0 },
  { term: "デパス", category: "drug", boost_weight: 2.0 },
  { term: "エチゾラム", category: "drug", boost_weight: 2.0 },
  { term: "マイスリー", category: "drug", boost_weight: 2.0 },
  { term: "ゾルピデム", category: "drug", boost_weight: 2.0 },
  { term: "ルネスタ", category: "drug", boost_weight: 2.0 },
  { term: "デエビゴ", category: "drug", boost_weight: 2.0 },
  { term: "レンボレキサント", category: "drug", boost_weight: 2.0 },
  { term: "ベルソムラ", category: "drug", boost_weight: 2.0 },
  { term: "スボレキサント", category: "drug", boost_weight: 2.0 },
  // 検査値
  { term: "AST", category: "lab", boost_weight: 1.5 },
  { term: "ALT", category: "lab", boost_weight: 1.5 },
  { term: "γ-GTP", category: "lab", boost_weight: 1.5 },
  { term: "ALP", category: "lab", boost_weight: 1.5 },
  { term: "LDH", category: "lab", boost_weight: 1.5 },
  { term: "総ビリルビン", reading: "そうびりるびん", category: "lab", boost_weight: 1.5 },
  { term: "アルブミン", category: "lab", boost_weight: 1.5 },
  { term: "総蛋白", reading: "そうたんぱく", category: "lab", boost_weight: 1.5 },
  { term: "クレアチニン", category: "lab", boost_weight: 1.5 },
  { term: "eGFR", category: "lab", boost_weight: 2.0 },
  { term: "BUN", category: "lab", boost_weight: 1.5 },
  { term: "CRP", category: "lab", boost_weight: 1.5 },
  { term: "赤沈", reading: "せきちん", category: "lab", boost_weight: 1.5 },
  { term: "白血球", reading: "はっけっきゅう", category: "lab", boost_weight: 1.5 },
  { term: "赤血球", reading: "せっけっきゅう", category: "lab", boost_weight: 1.5 },
  { term: "ヘモグロビン", category: "lab", boost_weight: 1.5 },
  { term: "ヘマトクリット", category: "lab", boost_weight: 1.5 },
  { term: "血小板", reading: "けっしょうばん", category: "lab", boost_weight: 1.5 },
  { term: "MCV", category: "lab", boost_weight: 1.5 },
  { term: "MCH", category: "lab", boost_weight: 1.5 },
  { term: "好中球", reading: "こうちゅうきゅう", category: "lab", boost_weight: 1.5 },
  { term: "リンパ球", reading: "りんぱきゅう", category: "lab", boost_weight: 1.5 },
  { term: "尿酸", reading: "にょうさん", category: "lab", boost_weight: 1.5 },
  { term: "TSH", category: "lab", boost_weight: 2.0 },
  { term: "FT3", category: "lab", boost_weight: 1.5 },
  { term: "FT4", category: "lab", boost_weight: 1.5 },
  { term: "Na", category: "lab", boost_weight: 1.0 },
  { term: "K", category: "lab", boost_weight: 1.0 },
  { term: "Cl", category: "lab", boost_weight: 1.0 },
  { term: "Ca", category: "lab", boost_weight: 1.0 },
  { term: "Fe", category: "lab", boost_weight: 1.0 },
  { term: "フェリチン", category: "lab", boost_weight: 1.5 },
  { term: "TIBC", category: "lab", boost_weight: 1.5 },
  { term: "血清鉄", reading: "けっせいてつ", category: "lab", boost_weight: 1.5 },
  { term: "PT-INR", category: "lab", boost_weight: 2.0 },
  { term: "APTT", category: "lab", boost_weight: 1.5 },
  { term: "フィブリノーゲン", category: "lab", boost_weight: 1.5 },
  { term: "HBs抗原", reading: "えいちびーえすこうげん", category: "lab", boost_weight: 2.0 },
  { term: "HCV抗体", reading: "えいちしーぶいこうたい", category: "lab", boost_weight: 2.0 },
  { term: "CEA", category: "lab", boost_weight: 1.5 },
  { term: "CA19-9", category: "lab", boost_weight: 1.5 },
  { term: "PSA", category: "lab", boost_weight: 2.0 },
  { term: "AFP", category: "lab", boost_weight: 1.5 },
  { term: "尿検査", reading: "にょうけんさ", category: "procedure", boost_weight: 1.0 },
  { term: "血液検査", reading: "けつえきけんさ", category: "procedure", boost_weight: 1.0 },
  { term: "生化学検査", reading: "せいかがくけんさ", category: "procedure", boost_weight: 1.5 },
  { term: "血液ガス", reading: "けつえきがす", category: "procedure", boost_weight: 1.5 },
  // 貧血
  { term: "貧血", reading: "ひんけつ", category: "symptom", boost_weight: 1.5 },
  { term: "鉄欠乏性貧血", reading: "てつけつぼうせいひんけつ", category: "symptom", boost_weight: 2.0 },
  { term: "鉄剤", reading: "てつざい", category: "drug", boost_weight: 1.5 },
  { term: "フェロミア", category: "drug", boost_weight: 2.0 },
  // --- 拡充: 膠原病系・血液疾患 ---
  { term: "全身性エリテマトーデス", reading: "ぜんしんせいえりてまとーです", category: "symptom", boost_weight: 2.0 },
  { term: "SLE", category: "symptom", boost_weight: 2.0 },
  { term: "関節リウマチ", reading: "かんせつりうまち", category: "symptom", boost_weight: 2.0 },
  { term: "リウマチ", category: "symptom", boost_weight: 2.0 },
  { term: "メトトレキサート", category: "drug", boost_weight: 2.0 },
  { term: "リウマトレックス", category: "drug", boost_weight: 2.0 },
  { term: "シェーグレン症候群", reading: "しぇーぐれんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "多発性筋炎", reading: "たはつせいきんえん", category: "symptom", boost_weight: 2.0 },
  { term: "皮膚筋炎", reading: "ひふきんえん", category: "symptom", boost_weight: 2.0 },
  { term: "強皮症", reading: "きょうひしょう", category: "symptom", boost_weight: 2.0 },
  { term: "血管炎", reading: "けっかんえん", category: "symptom", boost_weight: 2.0 },
  { term: "ANCA関連血管炎", category: "symptom", boost_weight: 2.0 },
  { term: "抗核抗体", reading: "こうかくこうたい", category: "lab", boost_weight: 2.0 },
  { term: "ANA", category: "lab", boost_weight: 2.0 },
  { term: "抗ds-DNA抗体", category: "lab", boost_weight: 2.0 },
  { term: "補体", reading: "ほたい", category: "lab", boost_weight: 1.5 },
  { term: "CH50", category: "lab", boost_weight: 1.5 },
  { term: "プレドニゾロン", category: "drug", boost_weight: 2.0 },
  { term: "プレドニン", category: "drug", boost_weight: 2.0 },
  { term: "ステロイドパルス", category: "procedure", boost_weight: 2.0 },
  { term: "免疫抑制剤", reading: "めんえきよくせいざい", category: "drug", boost_weight: 2.0 },
  { term: "アザチオプリン", category: "drug", boost_weight: 2.0 },
  { term: "イムラン", category: "drug", boost_weight: 2.0 },
  { term: "生物学的製剤", reading: "せいぶつがくてきせいざい", category: "drug", boost_weight: 2.0 },
  { term: "エタネルセプト", category: "drug", boost_weight: 2.0 },
  { term: "アダリムマブ", category: "drug", boost_weight: 2.0 },
  { term: "ヒュミラ", category: "drug", boost_weight: 2.0 },
  { term: "トシリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "アクテムラ", category: "drug", boost_weight: 2.0 },
  // 血液疾患
  { term: "白血病", reading: "はっけつびょう", category: "symptom", boost_weight: 2.0 },
  { term: "悪性リンパ腫", reading: "あくせいりんぱしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "多発性骨髄腫", reading: "たはつせいこつずいしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "骨髄異形成症候群", reading: "こつずいいけいせいしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "MDS", category: "symptom", boost_weight: 2.0 },
  { term: "DIC", category: "symptom", boost_weight: 2.0 },
  { term: "播種性血管内凝固", reading: "はしゅせいけっかんないぎょうこ", category: "symptom", boost_weight: 2.0 },
  { term: "ITP", category: "symptom", boost_weight: 2.0 },
  { term: "特発性血小板減少性紫斑病", reading: "とくはつせいけっしょうばんげんしょうせいしはんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "溶血性貧血", reading: "ようけつせいひんけつ", category: "symptom", boost_weight: 2.0 },
  { term: "再生不良性貧血", reading: "さいせいふりょうせいひんけつ", category: "symptom", boost_weight: 2.0 },
  { term: "骨髄穿刺", reading: "こつずいせんし", category: "procedure", boost_weight: 2.0 },
  { term: "マルク", category: "procedure", boost_weight: 2.0 },
  // 抗不整脈薬追加
  { term: "アミオダロン", category: "drug", boost_weight: 2.0 },
  { term: "ジゴキシン", category: "drug", boost_weight: 2.0 },
  { term: "ベラパミル", category: "drug", boost_weight: 2.0 },
  // 利尿薬追加
  { term: "フロセミド", category: "drug", boost_weight: 2.0 },
  { term: "ラシックス", category: "drug", boost_weight: 2.0 },
  { term: "スピロノラクトン", category: "drug", boost_weight: 2.0 },
  { term: "トルバプタン", category: "drug", boost_weight: 2.0 },
  { term: "サムスカ", category: "drug", boost_weight: 2.0 },
  // 抗血小板薬
  { term: "アスピリン", category: "drug", boost_weight: 2.0 },
  { term: "クロピドグレル", category: "drug", boost_weight: 2.0 },
  { term: "プラビックス", category: "drug", boost_weight: 2.0 },
  { term: "DAPT", category: "drug", boost_weight: 2.0 },
];
