// lib/voice/vocabulary/ob-gyn.ts — 産婦人科医療辞書
import type { VocabEntry } from "./types";

/** 産婦人科 */
export const OB_GYN: VocabEntry[] = [
  // 婦人科疾患
  { term: "子宮筋腫", reading: "しきゅうきんしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "子宮内膜症", reading: "しきゅうないまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "子宮腺筋症", reading: "しきゅうせんきんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "子宮内膜ポリープ", reading: "しきゅうないまくぽりーぷ", category: "symptom", boost_weight: 2.0 },
  { term: "子宮頸癌", reading: "しきゅうけいがん", category: "symptom", boost_weight: 2.0 },
  { term: "子宮体癌", reading: "しきゅうたいがん", category: "symptom", boost_weight: 2.0 },
  { term: "卵巣癌", reading: "らんそうがん", category: "symptom", boost_weight: 2.0 },
  { term: "卵巣嚢腫", reading: "らんそうのうしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "卵巣チョコレート嚢胞", reading: "らんそうちょこれーとのうほう", category: "symptom", boost_weight: 2.0 },
  { term: "子宮脱", reading: "しきゅうだつ", category: "symptom", boost_weight: 2.0 },
  { term: "骨盤臓器脱", reading: "こつばんぞうきだつ", category: "symptom", boost_weight: 2.0 },
  { term: "月経困難症", reading: "げっけいこんなんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "月経不順", reading: "げっけいふじゅん", category: "symptom", boost_weight: 1.5 },
  { term: "無月経", reading: "むげっけい", category: "symptom", boost_weight: 2.0 },
  { term: "過多月経", reading: "かたげっけい", category: "symptom", boost_weight: 2.0 },
  { term: "不正出血", reading: "ふせいしゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "PMS", category: "symptom", boost_weight: 2.0 },
  { term: "月経前症候群", reading: "げっけいぜんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "PMDD", category: "symptom", boost_weight: 2.0 },
  { term: "更年期障害", reading: "こうねんきしょうがい", category: "symptom", boost_weight: 2.0 },
  { term: "ホットフラッシュ", category: "symptom", boost_weight: 1.5 },
  { term: "多嚢胞性卵巣症候群", reading: "たのうほうせいらんそうしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "PCOS", category: "symptom", boost_weight: 2.0 },
  { term: "不妊症", reading: "ふにんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "不妊", reading: "ふにん", category: "symptom", boost_weight: 1.5 },
  { term: "子宮外妊娠", reading: "しきゅうがいにんしん", category: "symptom", boost_weight: 2.0 },
  { term: "異所性妊娠", reading: "いしょせいにんしん", category: "symptom", boost_weight: 2.0 },
  { term: "子宮頸部異形成", reading: "しきゅうけいぶいけいせい", category: "symptom", boost_weight: 2.0 },
  { term: "CIN", category: "symptom", boost_weight: 2.0 },
  { term: "HPV", category: "symptom", boost_weight: 2.0 },
  { term: "ヒトパピローマウイルス", category: "symptom", boost_weight: 2.0 },
  { term: "膣炎", reading: "ちつえん", category: "symptom", boost_weight: 1.5 },
  { term: "細菌性膣症", reading: "さいきんせいちつしょう", category: "symptom", boost_weight: 2.0 },
  { term: "カンジダ膣炎", reading: "かんじだちつえん", category: "symptom", boost_weight: 2.0 },
  // 産科
  { term: "妊娠", reading: "にんしん", category: "general", boost_weight: 1.5 },
  { term: "妊娠高血圧症候群", reading: "にんしんこうけつあつしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "HDP", category: "symptom", boost_weight: 2.0 },
  { term: "子癇", reading: "しかん", category: "symptom", boost_weight: 2.0 },
  { term: "妊娠糖尿病", reading: "にんしんとうにょうびょう", category: "symptom", boost_weight: 2.0 },
  { term: "GDM", category: "symptom", boost_weight: 2.0 },
  { term: "前置胎盤", reading: "ぜんちたいばん", category: "symptom", boost_weight: 2.0 },
  { term: "常位胎盤早期剥離", reading: "じょういたいばんそうきはくり", category: "symptom", boost_weight: 2.0 },
  { term: "切迫早産", reading: "せっぱくそうざん", category: "symptom", boost_weight: 2.0 },
  { term: "切迫流産", reading: "せっぱくりゅうざん", category: "symptom", boost_weight: 2.0 },
  { term: "流産", reading: "りゅうざん", category: "symptom", boost_weight: 2.0 },
  { term: "稽留流産", reading: "けいりゅうりゅうざん", category: "symptom", boost_weight: 2.0 },
  { term: "不育症", reading: "ふいくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "胎児発育不全", reading: "たいじはついくふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "FGR", category: "symptom", boost_weight: 2.0 },
  { term: "羊水過多", reading: "ようすいかた", category: "symptom", boost_weight: 2.0 },
  { term: "羊水過少", reading: "ようすいかしょう", category: "symptom", boost_weight: 2.0 },
  { term: "前期破水", reading: "ぜんきはすい", category: "symptom", boost_weight: 2.0 },
  { term: "PROM", category: "symptom", boost_weight: 2.0 },
  { term: "つわり", category: "symptom", boost_weight: 1.5 },
  { term: "妊娠悪阻", reading: "にんしんおそ", category: "symptom", boost_weight: 2.0 },
  { term: "胞状奇胎", reading: "ほうじょうきたい", category: "symptom", boost_weight: 2.0 },
  { term: "産後出血", reading: "さんごしゅっけつ", category: "symptom", boost_weight: 2.0 },
  // 薬剤
  { term: "ディナゲスト", category: "drug", boost_weight: 2.0 },
  { term: "ジエノゲスト", category: "drug", boost_weight: 2.0 },
  { term: "GnRHアゴニスト", category: "drug", boost_weight: 2.0 },
  { term: "リュープリン", category: "drug", boost_weight: 2.0 },
  { term: "GnRHアンタゴニスト", category: "drug", boost_weight: 2.0 },
  { term: "レルミナ", category: "drug", boost_weight: 2.0 },
  { term: "レルゴリクス", category: "drug", boost_weight: 2.0 },
  { term: "低用量ピル", reading: "ていようりょうぴる", category: "drug", boost_weight: 2.0 },
  { term: "ヤーズ", category: "drug", boost_weight: 2.0 },
  { term: "ルナベル", category: "drug", boost_weight: 2.0 },
  { term: "ジェミーナ", category: "drug", boost_weight: 2.0 },
  { term: "フリウェル", category: "drug", boost_weight: 2.0 },
  { term: "ミレーナ", category: "drug", boost_weight: 2.0 },
  { term: "レボノルゲストレル", category: "drug", boost_weight: 2.0 },
  { term: "IUS", category: "drug", boost_weight: 2.0 },
  { term: "IUD", category: "drug", boost_weight: 2.0 },
  { term: "HRT", category: "drug", boost_weight: 2.0 },
  { term: "ホルモン補充療法", reading: "ほるもんほじゅうりょうほう", category: "drug", boost_weight: 2.0 },
  { term: "エストロゲン", category: "drug", boost_weight: 2.0 },
  { term: "プロゲステロン", category: "drug", boost_weight: 2.0 },
  { term: "プレマリン", category: "drug", boost_weight: 2.0 },
  { term: "結合型エストロゲン", reading: "けつごうがたえすとろげん", category: "drug", boost_weight: 2.0 },
  { term: "デュファストン", category: "drug", boost_weight: 2.0 },
  { term: "ジドロゲステロン", category: "drug", boost_weight: 2.0 },
  { term: "エフメノ", category: "drug", boost_weight: 2.0 },
  { term: "天然型プロゲステロン", reading: "てんねんがたぷろげすてろん", category: "drug", boost_weight: 2.0 },
  { term: "ウリプリスタル", category: "drug", boost_weight: 2.0 },
  { term: "クロミフェン", category: "drug", boost_weight: 2.0 },
  { term: "クロミッド", category: "drug", boost_weight: 2.0 },
  { term: "レトロゾール", category: "drug", boost_weight: 2.0 },
  { term: "hMG", category: "drug", boost_weight: 2.0 },
  { term: "hCG", category: "drug", boost_weight: 2.0 },
  { term: "ウテメリン", category: "drug", boost_weight: 2.0 },
  { term: "リトドリン", category: "drug", boost_weight: 2.0 },
  { term: "マグセント", category: "drug", boost_weight: 2.0 },
  { term: "硫酸マグネシウム", reading: "りゅうさんまぐねしうむ", category: "drug", boost_weight: 2.0 },
  { term: "オキシトシン", category: "drug", boost_weight: 2.0 },
  // 検査
  { term: "子宮頸部細胞診", reading: "しきゅうけいぶさいぼうしん", category: "procedure", boost_weight: 2.0 },
  { term: "パップスメア", category: "procedure", boost_weight: 2.0 },
  { term: "コルポスコピー", category: "procedure", boost_weight: 2.0 },
  { term: "経膣エコー", reading: "けいちつえこー", category: "procedure", boost_weight: 2.0 },
  { term: "子宮鏡", reading: "しきゅうきょう", category: "procedure", boost_weight: 2.0 },
  { term: "卵管造影", reading: "らんかんぞうえい", category: "procedure", boost_weight: 2.0 },
  { term: "HSG", category: "procedure", boost_weight: 2.0 },
  { term: "NST", category: "procedure", boost_weight: 2.0 },
  { term: "胎児心拍モニタリング", reading: "たいじしんぱくもにたりんぐ", category: "procedure", boost_weight: 2.0 },
  { term: "超音波検査", reading: "ちょうおんぱけんさ", category: "procedure", boost_weight: 1.5 },
  { term: "4Dエコー", category: "procedure", boost_weight: 1.5 },
  { term: "NIPT", category: "procedure", boost_weight: 2.0 },
  { term: "新型出生前診断", reading: "しんがたしゅっせいぜんしんだん", category: "procedure", boost_weight: 2.0 },
  { term: "羊水検査", reading: "ようすいけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "絨毛検査", reading: "じゅうもうけんさ", category: "procedure", boost_weight: 2.0 },
  { term: "CA125", category: "lab", boost_weight: 2.0 },
  { term: "SCC", category: "lab", boost_weight: 2.0 },
  { term: "hCG", category: "lab", boost_weight: 2.0 },
  { term: "E2", category: "lab", boost_weight: 1.5 },
  { term: "FSH", category: "lab", boost_weight: 2.0 },
  { term: "LH", category: "lab", boost_weight: 2.0 },
  { term: "AMH", category: "lab", boost_weight: 2.0 },
  { term: "プロラクチン", category: "lab", boost_weight: 2.0 },
  // 処置・手術
  { term: "帝王切開", reading: "ていおうせっかい", category: "procedure", boost_weight: 2.0 },
  { term: "経膣分娩", reading: "けいちつぶんべん", category: "procedure", boost_weight: 2.0 },
  { term: "吸引分娩", reading: "きゅういんぶんべん", category: "procedure", boost_weight: 2.0 },
  { term: "鉗子分娩", reading: "かんしぶんべん", category: "procedure", boost_weight: 2.0 },
  { term: "会陰切開", reading: "えいんせっかい", category: "procedure", boost_weight: 2.0 },
  { term: "無痛分娩", reading: "むつうぶんべん", category: "procedure", boost_weight: 2.0 },
  { term: "子宮全摘出術", reading: "しきゅうぜんてきしゅつじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "腹腔鏡下子宮全摘出術", reading: "ふくくうきょうかしきゅうぜんてきしゅつじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "TLH", category: "procedure", boost_weight: 2.0 },
  { term: "子宮筋腫核出術", reading: "しきゅうきんしゅかくしゅつじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "LEEP", category: "procedure", boost_weight: 2.0 },
  { term: "円錐切除術", reading: "えんすいせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "子宮内膜掻爬", reading: "しきゅうないまくそうは", category: "procedure", boost_weight: 2.0 },
  { term: "体外受精", reading: "たいがいじゅせい", category: "procedure", boost_weight: 2.0 },
  { term: "IVF", category: "procedure", boost_weight: 2.0 },
  { term: "顕微授精", reading: "けんびじゅせい", category: "procedure", boost_weight: 2.0 },
  { term: "ICSI", category: "procedure", boost_weight: 2.0 },
  { term: "人工授精", reading: "じんこうじゅせい", category: "procedure", boost_weight: 2.0 },
  { term: "AIH", category: "procedure", boost_weight: 2.0 },
  { term: "胚移植", reading: "はいいしょく", category: "procedure", boost_weight: 2.0 },
  { term: "凍結胚移植", reading: "とうけつはいいしょく", category: "procedure", boost_weight: 2.0 },
  { term: "UAE", category: "procedure", boost_weight: 2.0 },
  { term: "子宮動脈塞栓術", reading: "しきゅうどうみゃくそくせんじゅつ", category: "procedure", boost_weight: 2.0 },
  // 解剖
  { term: "子宮", reading: "しきゅう", category: "anatomy", boost_weight: 1.5 },
  { term: "子宮頸部", reading: "しきゅうけいぶ", category: "anatomy", boost_weight: 1.5 },
  { term: "子宮体部", reading: "しきゅうたいぶ", category: "anatomy", boost_weight: 1.5 },
  { term: "子宮内膜", reading: "しきゅうないまく", category: "anatomy", boost_weight: 1.5 },
  { term: "子宮筋層", reading: "しきゅうきんそう", category: "anatomy", boost_weight: 1.5 },
  { term: "卵巣", reading: "らんそう", category: "anatomy", boost_weight: 1.5 },
  { term: "卵管", reading: "らんかん", category: "anatomy", boost_weight: 1.5 },
  { term: "膣", reading: "ちつ", category: "anatomy", boost_weight: 1.5 },
  { term: "外陰", reading: "がいいん", category: "anatomy", boost_weight: 1.5 },
  { term: "会陰", reading: "えいん", category: "anatomy", boost_weight: 1.5 },
  { term: "胎盤", reading: "たいばん", category: "anatomy", boost_weight: 1.5 },
  { term: "臍帯", reading: "さいたい", category: "anatomy", boost_weight: 1.5 },
  { term: "羊水", reading: "ようすい", category: "anatomy", boost_weight: 1.5 },
  { term: "骨盤底", reading: "こつばんてい", category: "anatomy", boost_weight: 1.5 },
];
