// lib/voice/vocabulary/ophthalmology.ts — 眼科医療辞書
import type { VocabEntry } from "./types";

/** 眼科 */
export const OPHTHALMOLOGY: VocabEntry[] = [
  // 疾患
  { term: "白内障", reading: "はくないしょう", category: "symptom", boost_weight: 2.0 },
  { term: "緑内障", reading: "りょくないしょう", category: "symptom", boost_weight: 2.0 },
  { term: "開放隅角緑内障", reading: "かいほうぐうかくりょくないしょう", category: "symptom", boost_weight: 2.0 },
  { term: "閉塞隅角緑内障", reading: "へいそくぐうかくりょくないしょう", category: "symptom", boost_weight: 2.0 },
  { term: "正常眼圧緑内障", reading: "せいじょうがんあつりょくないしょう", category: "symptom", boost_weight: 2.0 },
  { term: "加齢黄斑変性", reading: "かれいおうはんへんせい", category: "symptom", boost_weight: 2.0 },
  { term: "AMD", category: "symptom", boost_weight: 2.0 },
  { term: "滲出型", reading: "しんしゅつがた", category: "symptom", boost_weight: 1.5 },
  { term: "萎縮型", reading: "いしゅくがた", category: "symptom", boost_weight: 1.5 },
  { term: "糖尿病性網膜症", reading: "とうにょうびょうせいもうまくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "糖尿病黄斑浮腫", reading: "とうにょうびょうおうはんふしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "DME", category: "symptom", boost_weight: 2.0 },
  { term: "網膜剥離", reading: "もうまくはくり", category: "symptom", boost_weight: 2.0 },
  { term: "裂孔原性網膜剥離", reading: "れっこうげんせいもうまくはくり", category: "symptom", boost_weight: 2.0 },
  { term: "網膜静脈閉塞症", reading: "もうまくじょうみゃくへいそくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "RVO", category: "symptom", boost_weight: 2.0 },
  { term: "網膜中心静脈閉塞症", reading: "もうまくちゅうしんじょうみゃくへいそくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "CRVO", category: "symptom", boost_weight: 2.0 },
  { term: "網膜静脈分枝閉塞症", reading: "もうまくじょうみゃくぶんしへいそくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "BRVO", category: "symptom", boost_weight: 2.0 },
  { term: "黄斑円孔", reading: "おうはんえんこう", category: "symptom", boost_weight: 2.0 },
  { term: "黄斑前膜", reading: "おうはんぜんまく", category: "symptom", boost_weight: 2.0 },
  { term: "ぶどう膜炎", reading: "ぶどうまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "虹彩炎", reading: "こうさいえん", category: "symptom", boost_weight: 2.0 },
  { term: "結膜炎", reading: "けつまくえん", category: "symptom", boost_weight: 1.5 },
  { term: "アレルギー性結膜炎", reading: "あれるぎーせいけつまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "春季カタル", reading: "しゅんきかたる", category: "symptom", boost_weight: 2.0 },
  { term: "角膜炎", reading: "かくまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "角膜潰瘍", reading: "かくまくかいよう", category: "symptom", boost_weight: 2.0 },
  { term: "ドライアイ", category: "symptom", boost_weight: 1.5 },
  { term: "麦粒腫", reading: "ばくりゅうしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "ものもらい", category: "symptom", boost_weight: 1.5 },
  { term: "霰粒腫", reading: "さんりゅうしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "飛蚊症", reading: "ひぶんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "硝子体出血", reading: "しょうしたいしゅっけつ", category: "symptom", boost_weight: 2.0 },
  { term: "硝子体混濁", reading: "しょうしたいこんだく", category: "symptom", boost_weight: 2.0 },
  { term: "翼状片", reading: "よくじょうへん", category: "symptom", boost_weight: 2.0 },
  { term: "眼瞼下垂", reading: "がんけんかすい", category: "symptom", boost_weight: 2.0 },
  { term: "近視", reading: "きんし", category: "symptom", boost_weight: 1.5 },
  { term: "遠視", reading: "えんし", category: "symptom", boost_weight: 1.5 },
  { term: "乱視", reading: "らんし", category: "symptom", boost_weight: 1.5 },
  { term: "老視", reading: "ろうし", category: "symptom", boost_weight: 1.5 },
  { term: "斜視", reading: "しゃし", category: "symptom", boost_weight: 2.0 },
  { term: "弱視", reading: "じゃくし", category: "symptom", boost_weight: 2.0 },
  { term: "円錐角膜", reading: "えんすいかくまく", category: "symptom", boost_weight: 2.0 },
  { term: "網膜色素変性", reading: "もうまくしきそへんせい", category: "symptom", boost_weight: 2.0 },
  // 薬剤
  { term: "キサラタン", category: "drug", boost_weight: 2.0 },
  { term: "ラタノプロスト", category: "drug", boost_weight: 2.0 },
  { term: "タプロス", category: "drug", boost_weight: 2.0 },
  { term: "タフルプロスト", category: "drug", boost_weight: 2.0 },
  { term: "トラバタンズ", category: "drug", boost_weight: 2.0 },
  { term: "トラボプロスト", category: "drug", boost_weight: 2.0 },
  { term: "ルミガン", category: "drug", boost_weight: 2.0 },
  { term: "ビマトプロスト", category: "drug", boost_weight: 2.0 },
  { term: "チモロール", category: "drug", boost_weight: 2.0 },
  { term: "チモプトール", category: "drug", boost_weight: 2.0 },
  { term: "エイゾプト", category: "drug", boost_weight: 2.0 },
  { term: "ブリンゾラミド", category: "drug", boost_weight: 2.0 },
  { term: "トルソプト", category: "drug", boost_weight: 2.0 },
  { term: "ドルゾラミド", category: "drug", boost_weight: 2.0 },
  { term: "アイファガン", category: "drug", boost_weight: 2.0 },
  { term: "ブリモニジン", category: "drug", boost_weight: 2.0 },
  { term: "グラナテック", category: "drug", boost_weight: 2.0 },
  { term: "リパスジル", category: "drug", boost_weight: 2.0 },
  { term: "エイベリス", category: "drug", boost_weight: 2.0 },
  { term: "オミデネパグ", category: "drug", boost_weight: 2.0 },
  { term: "アイリーア", category: "drug", boost_weight: 2.0 },
  { term: "アフリベルセプト", category: "drug", boost_weight: 2.0 },
  { term: "ルセンティス", category: "drug", boost_weight: 2.0 },
  { term: "ラニビズマブ", category: "drug", boost_weight: 2.0 },
  { term: "バビースモ", category: "drug", boost_weight: 2.0 },
  { term: "ファリシマブ", category: "drug", boost_weight: 2.0 },
  { term: "ベオビュ", category: "drug", boost_weight: 2.0 },
  { term: "ブロルシズマブ", category: "drug", boost_weight: 2.0 },
  { term: "抗VEGF薬", reading: "こうぶいいーじーえふやく", category: "drug", boost_weight: 2.0 },
  { term: "VEGF", category: "lab", boost_weight: 1.5 },
  { term: "ジクアス", category: "drug", boost_weight: 2.0 },
  { term: "ジクアホソル", category: "drug", boost_weight: 2.0 },
  { term: "ムコスタ点眼", reading: "むこすたてんがん", category: "drug", boost_weight: 2.0 },
  { term: "レバミピド", category: "drug", boost_weight: 2.0 },
  { term: "ヒアレイン", category: "drug", boost_weight: 2.0 },
  { term: "散瞳薬", reading: "さんどうやく", category: "drug", boost_weight: 1.5 },
  { term: "ミドリンP", category: "drug", boost_weight: 2.0 },
  { term: "縮瞳薬", reading: "しゅくどうやく", category: "drug", boost_weight: 1.5 },
  // 検査
  { term: "OCT", category: "procedure", boost_weight: 2.0 },
  { term: "光干渉断層計", reading: "ひかりかんしょうだんそうけい", category: "procedure", boost_weight: 2.0 },
  { term: "眼底検査", reading: "がんていけんさ", category: "procedure", boost_weight: 1.5 },
  { term: "蛍光眼底造影", reading: "けいこうがんていぞうえい", category: "procedure", boost_weight: 2.0 },
  { term: "FA", category: "procedure", boost_weight: 1.5 },
  { term: "ICG造影", reading: "あいしーじーぞうえい", category: "procedure", boost_weight: 2.0 },
  { term: "視野検査", reading: "しやけんさ", category: "procedure", boost_weight: 1.5 },
  { term: "ハンフリー視野計", reading: "はんふりーしやけい", category: "procedure", boost_weight: 2.0 },
  { term: "ゴールドマン視野計", reading: "ごーるどまんしやけい", category: "procedure", boost_weight: 2.0 },
  { term: "眼圧", reading: "がんあつ", category: "lab", boost_weight: 2.0 },
  { term: "眼圧測定", reading: "がんあつそくてい", category: "procedure", boost_weight: 1.5 },
  { term: "細隙灯", reading: "さいげきとう", category: "procedure", boost_weight: 2.0 },
  { term: "スリットランプ", category: "procedure", boost_weight: 2.0 },
  { term: "前房", reading: "ぜんぼう", category: "anatomy", boost_weight: 1.5 },
  { term: "角膜内皮細胞", reading: "かくまくないひさいぼう", category: "anatomy", boost_weight: 2.0 },
  { term: "視力検査", reading: "しりょくけんさ", category: "procedure", boost_weight: 1.0 },
  { term: "矯正視力", reading: "きょうせいしりょく", category: "lab", boost_weight: 1.5 },
  // 処置・手術
  { term: "白内障手術", reading: "はくないしょうしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "超音波乳化吸引術", reading: "ちょうおんぱにゅうかきゅういんじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "PEA", category: "procedure", boost_weight: 2.0 },
  { term: "IOL", category: "procedure", boost_weight: 2.0 },
  { term: "眼内レンズ", reading: "がんないれんず", category: "procedure", boost_weight: 2.0 },
  { term: "多焦点眼内レンズ", reading: "たしょうてんがんないれんず", category: "procedure", boost_weight: 2.0 },
  { term: "硝子体手術", reading: "しょうしたいしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "硝子体切除術", reading: "しょうしたいせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "レーザー光凝固", reading: "れーざーひかりぎょうこ", category: "procedure", boost_weight: 2.0 },
  { term: "汎網膜光凝固", reading: "はんもうまくひかりぎょうこ", category: "procedure", boost_weight: 2.0 },
  { term: "SLT", category: "procedure", boost_weight: 2.0 },
  { term: "線維柱帯切除術", reading: "せんいちゅうたいせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "トラベクレクトミー", category: "procedure", boost_weight: 2.0 },
  { term: "線維柱帯切開術", reading: "せんいちゅうたいせっかいじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "iStent", category: "procedure", boost_weight: 2.0 },
  { term: "MIGS", category: "procedure", boost_weight: 2.0 },
  { term: "硝子体注射", reading: "しょうしたいちゅうしゃ", category: "procedure", boost_weight: 2.0 },
  { term: "IVT", category: "procedure", boost_weight: 2.0 },
  { term: "LASIK", category: "procedure", boost_weight: 2.0 },
  { term: "ICL", category: "procedure", boost_weight: 2.0 },
  // 解剖
  { term: "網膜", reading: "もうまく", category: "anatomy", boost_weight: 1.5 },
  { term: "硝子体", reading: "しょうしたい", category: "anatomy", boost_weight: 1.5 },
  { term: "水晶体", reading: "すいしょうたい", category: "anatomy", boost_weight: 1.5 },
  { term: "角膜", reading: "かくまく", category: "anatomy", boost_weight: 1.5 },
  { term: "虹彩", reading: "こうさい", category: "anatomy", boost_weight: 1.5 },
  { term: "毛様体", reading: "もうようたい", category: "anatomy", boost_weight: 1.5 },
  { term: "視神経", reading: "ししんけい", category: "anatomy", boost_weight: 1.5 },
  { term: "視神経乳頭", reading: "ししんけいにゅうとう", category: "anatomy", boost_weight: 2.0 },
  { term: "黄斑", reading: "おうはん", category: "anatomy", boost_weight: 2.0 },
  { term: "中心窩", reading: "ちゅうしんか", category: "anatomy", boost_weight: 2.0 },
  { term: "隅角", reading: "ぐうかく", category: "anatomy", boost_weight: 2.0 },
  { term: "結膜", reading: "けつまく", category: "anatomy", boost_weight: 1.5 },
  { term: "涙腺", reading: "るいせん", category: "anatomy", boost_weight: 1.5 },
  { term: "涙道", reading: "るいどう", category: "anatomy", boost_weight: 1.5 },
];
