// lib/voice/vocabulary/orthopedics.ts — 整形外科医療辞書
import type { VocabEntry } from "./types";

/** 整形外科 */
export const ORTHOPEDICS: VocabEntry[] = [
  // 検査
  { term: "MRI", category: "procedure", boost_weight: 2.0 },
  { term: "レントゲン", category: "procedure", boost_weight: 1.5 },
  { term: "X線", reading: "えっくすせん", category: "procedure", boost_weight: 1.5 },
  { term: "骨密度", reading: "こつみつど", category: "lab", boost_weight: 2.0 },
  { term: "DEXA", category: "procedure", boost_weight: 2.0 },
  { term: "骨シンチ", reading: "こつしんち", category: "procedure", boost_weight: 2.0 },
  { term: "関節造影", reading: "かんせつぞうえい", category: "procedure", boost_weight: 1.5 },
  // 疾患
  { term: "骨折", reading: "こっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "圧迫骨折", reading: "あっぱくこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "疲労骨折", reading: "ひろうこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "捻挫", reading: "ねんざ", category: "symptom", boost_weight: 1.5 },
  { term: "脱臼", reading: "だっきゅう", category: "symptom", boost_weight: 2.0 },
  { term: "靭帯損傷", reading: "じんたいそんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "半月板損傷", reading: "はんげつばんそんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "半月板", reading: "はんげつばん", category: "anatomy", boost_weight: 2.0 },
  { term: "椎間板ヘルニア", reading: "ついかんばんへるにあ", category: "symptom", boost_weight: 2.0 },
  { term: "脊柱管狭窄症", reading: "せきちゅうかんきょうさくしょう", category: "symptom", boost_weight: 2.0 },
  { term: "すべり症", reading: "すべりしょう", category: "symptom", boost_weight: 1.5 },
  { term: "分離症", reading: "ぶんりしょう", category: "symptom", boost_weight: 1.5 },
  { term: "側弯症", reading: "そくわんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性膝関節症", reading: "へんけいせいしつかんせつしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性股関節症", reading: "へんけいせいこかんせつしょう", category: "symptom", boost_weight: 2.0 },
  { term: "変形性脊椎症", reading: "へんけいせいせきついしょう", category: "symptom", boost_weight: 2.0 },
  { term: "腱鞘炎", reading: "けんしょうえん", category: "symptom", boost_weight: 2.0 },
  { term: "ばね指", reading: "ばねゆび", category: "symptom", boost_weight: 1.5 },
  { term: "手根管症候群", reading: "しゅこんかんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "肘部管症候群", reading: "ちゅうぶかんしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "骨粗鬆症", reading: "こつそしょうしょう", category: "symptom", boost_weight: 2.0 },
  { term: "五十肩", reading: "ごじゅうかた", category: "symptom", boost_weight: 1.5 },
  { term: "肩関節周囲炎", reading: "かたかんせつしゅういえん", category: "symptom", boost_weight: 2.0 },
  { term: "腱板断裂", reading: "けんばんだんれつ", category: "symptom", boost_weight: 2.0 },
  { term: "テニス肘", reading: "てにすひじ", category: "symptom", boost_weight: 1.5 },
  { term: "外側上顆炎", reading: "がいそくじょうかえん", category: "symptom", boost_weight: 2.0 },
  { term: "足底腱膜炎", reading: "そくていけんまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "坐骨神経痛", reading: "ざこつしんけいつう", category: "symptom", boost_weight: 2.0 },
  { term: "頸椎症", reading: "けいついしょう", category: "symptom", boost_weight: 2.0 },
  { term: "関節リウマチ", reading: "かんせつりうまち", category: "symptom", boost_weight: 2.0 },
  { term: "痛風性関節炎", reading: "つうふうせいかんせつえん", category: "symptom", boost_weight: 2.0 },
  { term: "偽痛風", reading: "ぎつうふう", category: "symptom", boost_weight: 2.0 },
  { term: "大腿骨頸部骨折", reading: "だいたいこつけいぶこっせつ", category: "symptom", boost_weight: 2.0 },
  { term: "橈骨遠位端骨折", reading: "とうこつえんいたんこっせつ", category: "symptom", boost_weight: 2.0 },
  // 処置
  { term: "関節鏡", reading: "かんせつきょう", category: "procedure", boost_weight: 2.0 },
  { term: "人工関節", reading: "じんこうかんせつ", category: "procedure", boost_weight: 2.0 },
  { term: "TKA", category: "procedure", boost_weight: 2.0 },
  { term: "THA", category: "procedure", boost_weight: 2.0 },
  { term: "骨接合術", reading: "こつせつごうじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "プレート固定", reading: "ぷれーとこてい", category: "procedure", boost_weight: 1.5 },
  { term: "髄内釘", reading: "ずいないてい", category: "procedure", boost_weight: 2.0 },
  { term: "ギプス", category: "procedure", boost_weight: 1.5 },
  { term: "シーネ", category: "procedure", boost_weight: 1.5 },
  { term: "装具", reading: "そうぐ", category: "procedure", boost_weight: 1.5 },
  { term: "リハビリ", category: "procedure", boost_weight: 1.5 },
  { term: "リハビリテーション", category: "procedure", boost_weight: 1.5 },
  { term: "理学療法", reading: "りがくりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "作業療法", reading: "さぎょうりょうほう", category: "procedure", boost_weight: 1.5 },
  { term: "関節注射", reading: "かんせつちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "ヒアルロン酸注射", reading: "ひあるろんさんちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "トリガーポイント", category: "procedure", boost_weight: 1.5 },
  { term: "ブロック注射", reading: "ぶろっくちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "神経根ブロック", reading: "しんけいこんぶろっく", category: "procedure", boost_weight: 2.0 },
  { term: "硬膜外ブロック", reading: "こうまくがいぶろっく", category: "procedure", boost_weight: 2.0 },
  { term: "牽引", reading: "けんいん", category: "procedure", boost_weight: 1.5 },
  // 薬剤
  { term: "ロキソニン", category: "drug", boost_weight: 2.0 },
  { term: "ロキソプロフェン", category: "drug", boost_weight: 2.0 },
  { term: "セレコキシブ", category: "drug", boost_weight: 2.0 },
  { term: "セレコックス", category: "drug", boost_weight: 2.0 },
  { term: "NSAIDs", category: "drug", boost_weight: 2.0 },
  { term: "プレガバリン", category: "drug", boost_weight: 2.0 },
  { term: "リリカ", category: "drug", boost_weight: 2.0 },
  { term: "ミロガバリン", category: "drug", boost_weight: 2.0 },
  { term: "タリージェ", category: "drug", boost_weight: 2.0 },
  { term: "トラマドール", category: "drug", boost_weight: 2.0 },
  { term: "トラムセット", category: "drug", boost_weight: 2.0 },
  { term: "デュロテップ", category: "drug", boost_weight: 2.0 },
  { term: "ビスホスホネート", category: "drug", boost_weight: 2.0 },
  { term: "デノスマブ", category: "drug", boost_weight: 2.0 },
  { term: "プラリア", category: "drug", boost_weight: 2.0 },
  { term: "テリパラチド", category: "drug", boost_weight: 2.0 },
  { term: "フォルテオ", category: "drug", boost_weight: 2.0 },
  { term: "エルデカルシトール", category: "drug", boost_weight: 2.0 },
  { term: "エディロール", category: "drug", boost_weight: 2.0 },
  { term: "活性型ビタミンD", reading: "かっせいがたびたみんでぃー", category: "drug", boost_weight: 1.5 },
  { term: "ケナコルト", category: "drug", boost_weight: 2.0 },
  { term: "ステロイド注射", reading: "すてろいどちゅうしゃ", category: "procedure", boost_weight: 1.5 },
  { term: "湿布", reading: "しっぷ", category: "drug", boost_weight: 1.0 },
  { term: "モーラステープ", category: "drug", boost_weight: 1.5 },
  { term: "ケトプロフェン", category: "drug", boost_weight: 1.5 },
  // 解剖
  { term: "頸椎", reading: "けいつい", category: "anatomy", boost_weight: 1.5 },
  { term: "胸椎", reading: "きょうつい", category: "anatomy", boost_weight: 1.5 },
  { term: "腰椎", reading: "ようつい", category: "anatomy", boost_weight: 1.5 },
  { term: "仙骨", reading: "せんこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "椎体", reading: "ついたい", category: "anatomy", boost_weight: 1.5 },
  { term: "椎間板", reading: "ついかんばん", category: "anatomy", boost_weight: 1.5 },
  { term: "脊髄", reading: "せきずい", category: "anatomy", boost_weight: 1.5 },
  { term: "馬尾", reading: "ばび", category: "anatomy", boost_weight: 2.0 },
  { term: "前十字靭帯", reading: "ぜんじゅうじじんたい", category: "anatomy", boost_weight: 2.0 },
  { term: "後十字靭帯", reading: "こうじゅうじじんたい", category: "anatomy", boost_weight: 2.0 },
  { term: "ACL", category: "anatomy", boost_weight: 2.0 },
  { term: "PCL", category: "anatomy", boost_weight: 2.0 },
  { term: "アキレス腱", reading: "あきれすけん", category: "anatomy", boost_weight: 1.5 },
  { term: "大腿骨", reading: "だいたいこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "脛骨", reading: "けいこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "腓骨", reading: "ひこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "橈骨", reading: "とうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "尺骨", reading: "しゃっこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "上腕骨", reading: "じょうわんこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "鎖骨", reading: "さこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "肩甲骨", reading: "けんこうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "骨盤", reading: "こつばん", category: "anatomy", boost_weight: 1.5 },
  { term: "肩関節", reading: "かたかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "肘関節", reading: "ひじかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "手関節", reading: "てかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "股関節", reading: "こかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "膝関節", reading: "しつかんせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "足関節", reading: "そくかんせつ", category: "anatomy", boost_weight: 1.5 },
  // --- 拡充: スポーツ医学 ---
  { term: "ACL再建術", reading: "えーしーえるさいけんじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "腱板修復術", reading: "けんばんしゅうふくじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "肩腱板", reading: "かたけんばん", category: "anatomy", boost_weight: 1.5 },
  { term: "棘上筋", reading: "きょくじょうきん", category: "anatomy", boost_weight: 1.5 },
  { term: "棘下筋", reading: "きょくかきん", category: "anatomy", boost_weight: 1.5 },
  { term: "SLAP損傷", category: "symptom", boost_weight: 2.0 },
  { term: "バンカート損傷", category: "symptom", boost_weight: 2.0 },
  { term: "ヒルサックス損傷", category: "symptom", boost_weight: 2.0 },
  { term: "ジャンパー膝", reading: "じゃんぱーひざ", category: "symptom", boost_weight: 1.5 },
  { term: "オスグッド病", reading: "おすぐっどびょう", category: "symptom", boost_weight: 2.0 },
  { term: "シンスプリント", category: "symptom", boost_weight: 1.5 },
  { term: "腸脛靭帯炎", reading: "ちょうけいじんたいえん", category: "symptom", boost_weight: 2.0 },
  { term: "ランナー膝", reading: "らんなーひざ", category: "symptom", boost_weight: 1.5 },
  { term: "外反母趾", reading: "がいはんぼし", category: "symptom", boost_weight: 2.0 },
  { term: "モートン病", reading: "もーとんびょう", category: "symptom", boost_weight: 2.0 },
  { term: "距骨", reading: "きょこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "踵骨", reading: "しょうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "中足骨", reading: "ちゅうそくこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "舟状骨", reading: "しゅうじょうこつ", category: "anatomy", boost_weight: 1.5 },
  { term: "脊椎固定術", reading: "せきついこていじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "椎弓形成術", reading: "ついきゅうけいせいじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "PLIF", category: "procedure", boost_weight: 2.0 },
  { term: "TLIF", category: "procedure", boost_weight: 2.0 },
  { term: "BKP", category: "procedure", boost_weight: 2.0 },
  { term: "経皮的椎体形成術", reading: "けいひてきついたいけいせいじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "PRP療法", reading: "ぴーあーるぴーりょうほう", category: "procedure", boost_weight: 2.0 },
  { term: "体外衝撃波", reading: "たいがいしょうげきは", category: "procedure", boost_weight: 2.0 },
  { term: "テーピング", category: "procedure", boost_weight: 1.0 },
  { term: "アスレティックリハビリテーション", category: "procedure", boost_weight: 1.5 },
  { term: "可動域訓練", reading: "かどういきくんれん", category: "procedure", boost_weight: 1.5 },
  { term: "ROM", category: "procedure", boost_weight: 1.5 },
  { term: "MMT", category: "procedure", boost_weight: 1.5 },
  { term: "筋力低下", reading: "きんりょくていか", category: "symptom", boost_weight: 1.5 },
  { term: "関節拘縮", reading: "かんせつこうしゅく", category: "symptom", boost_weight: 2.0 },
  { term: "廃用症候群", reading: "はいようしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "ロモソズマブ", category: "drug", boost_weight: 2.0 },
  { term: "イベニティ", category: "drug", boost_weight: 2.0 },
];
