// lib/voice/vocabulary/surgery.ts — 外科医療辞書
import type { VocabEntry } from "./types";

/** 外科 */
export const SURGERY: VocabEntry[] = [
  // 基本手技
  { term: "縫合", reading: "ほうごう", category: "procedure", boost_weight: 2.0 },
  { term: "切開", reading: "せっかい", category: "procedure", boost_weight: 1.5 },
  { term: "切除", reading: "せつじょ", category: "procedure", boost_weight: 1.5 },
  { term: "郭清", reading: "かくせい", category: "procedure", boost_weight: 2.0 },
  { term: "吻合", reading: "ふんごう", category: "procedure", boost_weight: 2.0 },
  { term: "ドレーン", category: "procedure", boost_weight: 2.0 },
  { term: "デブリードマン", category: "procedure", boost_weight: 2.0 },
  { term: "ドレナージ", category: "procedure", boost_weight: 2.0 },
  { term: "穿刺", reading: "せんし", category: "procedure", boost_weight: 2.0 },
  { term: "クランプ", category: "procedure", boost_weight: 1.5 },
  { term: "結紮", reading: "けっさつ", category: "procedure", boost_weight: 2.0 },
  // 麻酔
  { term: "局所麻酔", reading: "きょくしょますい", category: "procedure", boost_weight: 1.5 },
  { term: "全身麻酔", reading: "ぜんしんますい", category: "procedure", boost_weight: 1.5 },
  { term: "腰椎麻酔", reading: "ようついますい", category: "procedure", boost_weight: 1.5 },
  { term: "硬膜外麻酔", reading: "こうまくがいますい", category: "procedure", boost_weight: 2.0 },
  { term: "静脈麻酔", reading: "じょうみゃくますい", category: "procedure", boost_weight: 1.5 },
  { term: "伝達麻酔", reading: "でんたつますい", category: "procedure", boost_weight: 1.5 },
  { term: "挿管", reading: "そうかん", category: "procedure", boost_weight: 1.5 },
  { term: "気管挿管", reading: "きかんそうかん", category: "procedure", boost_weight: 2.0 },
  { term: "キシロカイン", category: "drug", boost_weight: 2.0 },
  { term: "リドカイン", category: "drug", boost_weight: 2.0 },
  { term: "プロポフォール", category: "drug", boost_weight: 2.0 },
  { term: "セボフルラン", category: "drug", boost_weight: 2.0 },
  // 創傷
  { term: "創部", reading: "そうぶ", category: "anatomy", boost_weight: 1.5 },
  { term: "創傷", reading: "そうしょう", category: "symptom", boost_weight: 1.5 },
  { term: "瘢痕", reading: "はんこん", category: "symptom", boost_weight: 2.0 },
  { term: "ケロイド", category: "symptom", boost_weight: 2.0 },
  { term: "膿瘍", reading: "のうよう", category: "symptom", boost_weight: 2.0 },
  { term: "蜂窩織炎", reading: "ほうかしきえん", category: "symptom", boost_weight: 2.0 },
  { term: "壊疽", reading: "えそ", category: "symptom", boost_weight: 2.0 },
  { term: "褥瘡", reading: "じょくそう", category: "symptom", boost_weight: 2.0 },
  { term: "肉芽", reading: "にくげ", category: "symptom", boost_weight: 1.5 },
  // 検査
  { term: "CT", category: "procedure", boost_weight: 1.5 },
  { term: "造影CT", reading: "ぞうえいしーてぃー", category: "procedure", boost_weight: 2.0 },
  { term: "エコー", category: "procedure", boost_weight: 1.5 },
  { term: "生検", reading: "せいけん", category: "procedure", boost_weight: 2.0 },
  { term: "病理", reading: "びょうり", category: "procedure", boost_weight: 1.5 },
  { term: "迅速病理", reading: "じんそくびょうり", category: "procedure", boost_weight: 2.0 },
  { term: "PET-CT", category: "procedure", boost_weight: 2.0 },
  // 周術期
  { term: "術前", reading: "じゅつぜん", category: "general", boost_weight: 1.0 },
  { term: "術後", reading: "じゅつご", category: "general", boost_weight: 1.0 },
  { term: "術中", reading: "じゅつちゅう", category: "general", boost_weight: 1.0 },
  { term: "周術期", reading: "しゅうじゅつき", category: "general", boost_weight: 1.5 },
  { term: "抜糸", reading: "ばっし", category: "procedure", boost_weight: 1.5 },
  { term: "消毒", reading: "しょうどく", category: "procedure", boost_weight: 1.0 },
  { term: "ガーゼ", category: "general", boost_weight: 1.0 },
  { term: "止血", reading: "しけつ", category: "procedure", boost_weight: 1.5 },
  { term: "バイポーラ", category: "procedure", boost_weight: 1.5 },
  { term: "術後感染", reading: "じゅつごかんせん", category: "symptom", boost_weight: 1.5 },
  { term: "SSI", category: "symptom", boost_weight: 2.0 },
  { term: "DVT予防", reading: "でぃーぶいてぃーよぼう", category: "procedure", boost_weight: 1.5 },
  { term: "抗凝固", reading: "こうぎょうこ", category: "drug", boost_weight: 1.5 },
  // 術式
  { term: "腹腔鏡", reading: "ふくくうきょう", category: "procedure", boost_weight: 2.0 },
  { term: "腹腔鏡下手術", reading: "ふくくうきょうかしゅじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "開腹", reading: "かいふく", category: "procedure", boost_weight: 1.5 },
  { term: "開腹手術", reading: "かいふくしゅじゅつ", category: "procedure", boost_weight: 1.5 },
  { term: "ロボット支援", reading: "ろぼっとしえん", category: "procedure", boost_weight: 1.5 },
  { term: "ダヴィンチ", category: "procedure", boost_weight: 2.0 },
  // 疾患
  { term: "虫垂炎", reading: "ちゅうすいえん", category: "symptom", boost_weight: 2.0 },
  { term: "ヘルニア", category: "symptom", boost_weight: 2.0 },
  { term: "鼠径ヘルニア", reading: "そけいへるにあ", category: "symptom", boost_weight: 2.0 },
  { term: "胆嚢摘出", reading: "たんのうてきしゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "胆嚢炎", reading: "たんのうえん", category: "symptom", boost_weight: 2.0 },
  { term: "腸閉塞", reading: "ちょうへいそく", category: "symptom", boost_weight: 2.0 },
  { term: "イレウス", category: "symptom", boost_weight: 2.0 },
  { term: "腹膜炎", reading: "ふくまくえん", category: "symptom", boost_weight: 2.0 },
  { term: "消化管穿孔", reading: "しょうかかんせんこう", category: "symptom", boost_weight: 2.0 },
  { term: "大腸癌", reading: "だいちょうがん", category: "symptom", boost_weight: 2.0 },
  { term: "胃癌", reading: "いがん", category: "symptom", boost_weight: 2.0 },
  { term: "乳癌", reading: "にゅうがん", category: "symptom", boost_weight: 2.0 },
  { term: "肺癌", reading: "はいがん", category: "symptom", boost_weight: 2.0 },
  { term: "甲状腺癌", reading: "こうじょうせんがん", category: "symptom", boost_weight: 2.0 },
  { term: "リンパ節", reading: "りんぱせつ", category: "anatomy", boost_weight: 1.5 },
  { term: "転移", reading: "てんい", category: "symptom", boost_weight: 1.5 },
  { term: "良性", reading: "りょうせい", category: "general", boost_weight: 1.0 },
  { term: "悪性", reading: "あくせい", category: "general", boost_weight: 1.0 },
  { term: "腫瘍", reading: "しゅよう", category: "symptom", boost_weight: 1.5 },
  { term: "ステージ", category: "general", boost_weight: 1.0 },
  { term: "TNM分類", category: "general", boost_weight: 1.5 },
  // --- 拡充: 最新術式・術後ケア ---
  { term: "胸腔鏡", reading: "きょうくうきょう", category: "procedure", boost_weight: 2.0 },
  { term: "VATS", category: "procedure", boost_weight: 2.0 },
  { term: "単孔式", reading: "たんこうしき", category: "procedure", boost_weight: 2.0 },
  { term: "NOTES", category: "procedure", boost_weight: 2.0 },
  { term: "経自然孔", reading: "けいしぜんこう", category: "procedure", boost_weight: 1.5 },
  { term: "ステープラー", category: "procedure", boost_weight: 1.5 },
  { term: "自動縫合器", reading: "じどうほうごうき", category: "procedure", boost_weight: 1.5 },
  { term: "エネルギーデバイス", category: "procedure", boost_weight: 1.5 },
  { term: "超音波凝固切開装置", reading: "ちょうおんぱぎょうこせっかいそうち", category: "procedure", boost_weight: 2.0 },
  { term: "ハーモニック", category: "procedure", boost_weight: 2.0 },
  { term: "リガシュア", category: "procedure", boost_weight: 2.0 },
  { term: "サンドイッチ法", category: "procedure", boost_weight: 1.5 },
  { term: "メッシュ修復", reading: "めっしゅしゅうふく", category: "procedure", boost_weight: 1.5 },
  { term: "TAPP", category: "procedure", boost_weight: 2.0 },
  { term: "TEP", category: "procedure", boost_weight: 2.0 },
  // 術後管理
  { term: "術後出血", reading: "じゅつごしゅっけつ", category: "symptom", boost_weight: 1.5 },
  { term: "縫合不全", reading: "ほうごうふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "離開", reading: "りかい", category: "symptom", boost_weight: 1.5 },
  { term: "膿瘍ドレナージ", reading: "のうようどれなーじ", category: "procedure", boost_weight: 2.0 },
  { term: "癒着", reading: "ゆちゃく", category: "symptom", boost_weight: 1.5 },
  { term: "術後疼痛管理", reading: "じゅつごとうつうかんり", category: "procedure", boost_weight: 1.5 },
  { term: "PCA", category: "procedure", boost_weight: 2.0 },
  { term: "早期離床", reading: "そうきりしょう", category: "procedure", boost_weight: 1.5 },
  { term: "ERAS", category: "procedure", boost_weight: 2.0 },
  { term: "経腸栄養", reading: "けいちょうえいよう", category: "procedure", boost_weight: 1.5 },
  { term: "TPN", category: "procedure", boost_weight: 2.0 },
  { term: "中心静脈栄養", reading: "ちゅうしんじょうみゃくえいよう", category: "procedure", boost_weight: 2.0 },
  { term: "CVカテーテル", category: "procedure", boost_weight: 2.0 },
  { term: "PICC", category: "procedure", boost_weight: 2.0 },
  // 化学療法
  { term: "化学療法", reading: "かがくりょうほう", category: "procedure", boost_weight: 2.0 },
  { term: "ケモ", category: "procedure", boost_weight: 1.5 },
  { term: "レジメン", category: "general", boost_weight: 1.5 },
  { term: "抗がん剤", reading: "こうがんざい", category: "drug", boost_weight: 2.0 },
  { term: "分子標的薬", reading: "ぶんしひょうてきやく", category: "drug", boost_weight: 2.0 },
  { term: "免疫チェックポイント阻害薬", reading: "めんえきちぇっくぽいんとそがいやく", category: "drug", boost_weight: 2.0 },
  { term: "オプジーボ", category: "drug", boost_weight: 2.0 },
  { term: "ニボルマブ", category: "drug", boost_weight: 2.0 },
  { term: "キイトルーダ", category: "drug", boost_weight: 2.0 },
  { term: "ペムブロリズマブ", category: "drug", boost_weight: 2.0 },
  { term: "放射線治療", reading: "ほうしゃせんちりょう", category: "procedure", boost_weight: 2.0 },
  { term: "センチネルリンパ節", category: "anatomy", boost_weight: 2.0 },
  { term: "センチネルリンパ節生検", reading: "せんちねるりんぱせつせいけん", category: "procedure", boost_weight: 2.0 },
  { term: "術中迅速", reading: "じゅつちゅうじんそく", category: "procedure", boost_weight: 1.5 },
];
