// lib/voice/vocabulary/urology.ts — 泌尿器科医療辞書
import type { VocabEntry } from "./types";

/** 泌尿器科 */
export const UROLOGY: VocabEntry[] = [
  // 疾患
  { term: "前立腺肥大症", reading: "ぜんりつせんひだいしょう", category: "symptom", boost_weight: 2.0 },
  { term: "BPH", category: "symptom", boost_weight: 2.0 },
  { term: "前立腺癌", reading: "ぜんりつせんがん", category: "symptom", boost_weight: 2.0 },
  { term: "膀胱癌", reading: "ぼうこうがん", category: "symptom", boost_weight: 2.0 },
  { term: "腎癌", reading: "じんがん", category: "symptom", boost_weight: 2.0 },
  { term: "腎細胞癌", reading: "じんさいぼうがん", category: "symptom", boost_weight: 2.0 },
  { term: "精巣腫瘍", reading: "せいそうしゅよう", category: "symptom", boost_weight: 2.0 },
  { term: "尿路上皮癌", reading: "にょうろじょうひがん", category: "symptom", boost_weight: 2.0 },
  { term: "腎盂癌", reading: "じんうがん", category: "symptom", boost_weight: 2.0 },
  { term: "尿管癌", reading: "にょうかんがん", category: "symptom", boost_weight: 2.0 },
  { term: "過活動膀胱", reading: "かかつどうぼうこう", category: "symptom", boost_weight: 2.0 },
  { term: "OAB", category: "symptom", boost_weight: 2.0 },
  { term: "尿失禁", reading: "にょうしっきん", category: "symptom", boost_weight: 2.0 },
  { term: "腹圧性尿失禁", reading: "ふくあつせいにょうしっきん", category: "symptom", boost_weight: 2.0 },
  { term: "切迫性尿失禁", reading: "せっぱくせいにょうしっきん", category: "symptom", boost_weight: 2.0 },
  { term: "頻尿", reading: "ひんにょう", category: "symptom", boost_weight: 1.5 },
  { term: "夜間頻尿", reading: "やかんひんにょう", category: "symptom", boost_weight: 2.0 },
  { term: "排尿困難", reading: "はいにょうこんなん", category: "symptom", boost_weight: 1.5 },
  { term: "残尿感", reading: "ざんにょうかん", category: "symptom", boost_weight: 1.5 },
  { term: "尿閉", reading: "にょうへい", category: "symptom", boost_weight: 2.0 },
  { term: "尿路感染症", reading: "にょうろかんせんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "膀胱炎", reading: "ぼうこうえん", category: "symptom", boost_weight: 1.5 },
  { term: "腎盂腎炎", reading: "じんうじんえん", category: "symptom", boost_weight: 2.0 },
  { term: "前立腺炎", reading: "ぜんりつせんえん", category: "symptom", boost_weight: 2.0 },
  { term: "精巣上体炎", reading: "せいそうじょうたいえん", category: "symptom", boost_weight: 2.0 },
  { term: "尿路結石", reading: "にょうろけっせき", category: "symptom", boost_weight: 2.0 },
  { term: "腎結石", reading: "じんけっせき", category: "symptom", boost_weight: 2.0 },
  { term: "尿管結石", reading: "にょうかんけっせき", category: "symptom", boost_weight: 2.0 },
  { term: "膀胱結石", reading: "ぼうこうけっせき", category: "symptom", boost_weight: 2.0 },
  { term: "水腎症", reading: "すいじんしょう", category: "symptom", boost_weight: 2.0 },
  { term: "陰嚢水腫", reading: "いんのうすいしゅ", category: "symptom", boost_weight: 2.0 },
  { term: "精索静脈瘤", reading: "せいさくじょうみゃくりゅう", category: "symptom", boost_weight: 2.0 },
  { term: "包茎", reading: "ほうけい", category: "symptom", boost_weight: 1.5 },
  { term: "亀頭包皮炎", reading: "きとうほうひえん", category: "symptom", boost_weight: 2.0 },
  { term: "神経因性膀胱", reading: "しんけいいんせいぼうこう", category: "symptom", boost_weight: 2.0 },
  { term: "間質性膀胱炎", reading: "かんしつせいぼうこうえん", category: "symptom", boost_weight: 2.0 },
  { term: "男性不妊", reading: "だんせいふにん", category: "symptom", boost_weight: 2.0 },
  { term: "勃起不全", reading: "ぼっきふぜん", category: "symptom", boost_weight: 2.0 },
  { term: "ED", category: "symptom", boost_weight: 1.5 },
  { term: "LOH症候群", reading: "ろーしょうこうぐん", category: "symptom", boost_weight: 2.0 },
  { term: "男性更年期障害", reading: "だんせいこうねんきしょうがい", category: "symptom", boost_weight: 2.0 },
  // 薬剤
  { term: "タムスロシン", category: "drug", boost_weight: 2.0 },
  { term: "ハルナール", category: "drug", boost_weight: 2.0 },
  { term: "シロドシン", category: "drug", boost_weight: 2.0 },
  { term: "ユリーフ", category: "drug", boost_weight: 2.0 },
  { term: "ナフトピジル", category: "drug", boost_weight: 2.0 },
  { term: "フリバス", category: "drug", boost_weight: 2.0 },
  { term: "デュタステリド", category: "drug", boost_weight: 2.0 },
  { term: "アボルブ", category: "drug", boost_weight: 2.0 },
  { term: "ザルティア", category: "drug", boost_weight: 2.0 },
  { term: "タダラフィル", category: "drug", boost_weight: 2.0 },
  { term: "ベタニス", category: "drug", boost_weight: 2.0 },
  { term: "ミラベグロン", category: "drug", boost_weight: 2.0 },
  { term: "ベオーバ", category: "drug", boost_weight: 2.0 },
  { term: "ビベグロン", category: "drug", boost_weight: 2.0 },
  { term: "ベシケア", category: "drug", boost_weight: 2.0 },
  { term: "ソリフェナシン", category: "drug", boost_weight: 2.0 },
  { term: "トビエース", category: "drug", boost_weight: 2.0 },
  { term: "フェソテロジン", category: "drug", boost_weight: 2.0 },
  { term: "ウリトス", category: "drug", boost_weight: 2.0 },
  { term: "イミダフェナシン", category: "drug", boost_weight: 2.0 },
  { term: "エンザルタミド", category: "drug", boost_weight: 2.0 },
  { term: "イクスタンジ", category: "drug", boost_weight: 2.0 },
  { term: "アビラテロン", category: "drug", boost_weight: 2.0 },
  { term: "ザイティガ", category: "drug", boost_weight: 2.0 },
  { term: "リュープリン", category: "drug", boost_weight: 2.0 },
  { term: "リュープロレリン", category: "drug", boost_weight: 2.0 },
  { term: "ゴナックス", category: "drug", boost_weight: 2.0 },
  { term: "デガレリクス", category: "drug", boost_weight: 2.0 },
  { term: "ビカルタミド", category: "drug", boost_weight: 2.0 },
  { term: "カソデックス", category: "drug", boost_weight: 2.0 },
  // 検査
  { term: "PSA", category: "lab", boost_weight: 2.0 },
  { term: "前立腺特異抗原", reading: "ぜんりつせんとくいこうげん", category: "lab", boost_weight: 2.0 },
  { term: "残尿測定", reading: "ざんにょうそくてい", category: "procedure", boost_weight: 1.5 },
  { term: "尿流量測定", reading: "にょうりゅうりょうそくてい", category: "procedure", boost_weight: 2.0 },
  { term: "ウロフロメトリー", category: "procedure", boost_weight: 2.0 },
  { term: "膀胱鏡", reading: "ぼうこうきょう", category: "procedure", boost_weight: 2.0 },
  { term: "尿路造影", reading: "にょうろぞうえい", category: "procedure", boost_weight: 2.0 },
  { term: "IVP", category: "procedure", boost_weight: 2.0 },
  { term: "腎エコー", reading: "じんえこー", category: "procedure", boost_weight: 1.5 },
  { term: "経直腸エコー", reading: "けいちょくちょうえこー", category: "procedure", boost_weight: 2.0 },
  { term: "TRUS", category: "procedure", boost_weight: 2.0 },
  { term: "前立腺生検", reading: "ぜんりつせんせいけん", category: "procedure", boost_weight: 2.0 },
  { term: "尿細胞診", reading: "にょうさいぼうしん", category: "procedure", boost_weight: 2.0 },
  { term: "尿道圧測定", reading: "にょうどうあつそくてい", category: "procedure", boost_weight: 2.0 },
  { term: "パッドテスト", category: "procedure", boost_weight: 1.5 },
  { term: "IPSS", category: "lab", boost_weight: 2.0 },
  { term: "OABSS", category: "lab", boost_weight: 2.0 },
  // 処置・手術
  { term: "TURP", category: "procedure", boost_weight: 2.0 },
  { term: "経尿道的前立腺切除術", reading: "けいにょうどうてきぜんりつせんせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "HoLEP", category: "procedure", boost_weight: 2.0 },
  { term: "TURBT", category: "procedure", boost_weight: 2.0 },
  { term: "経尿道的膀胱腫瘍切除術", reading: "けいにょうどうてきぼうこうしゅようせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "前立腺全摘", reading: "ぜんりつせんぜんてき", category: "procedure", boost_weight: 2.0 },
  { term: "腎摘出術", reading: "じんてきしゅつじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "腎部分切除術", reading: "じんぶぶんせつじょじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "膀胱全摘", reading: "ぼうこうぜんてき", category: "procedure", boost_weight: 2.0 },
  { term: "ESWL", category: "procedure", boost_weight: 2.0 },
  { term: "体外衝撃波砕石術", reading: "たいがいしょうげきはさいせきじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "TUL", category: "procedure", boost_weight: 2.0 },
  { term: "経尿道的尿管砕石術", reading: "けいにょうどうてきにょうかんさいせきじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "PNL", category: "procedure", boost_weight: 2.0 },
  { term: "経皮的腎砕石術", reading: "けいひてきじんさいせきじゅつ", category: "procedure", boost_weight: 2.0 },
  { term: "BCG膀胱内注入", reading: "びーしーじーぼうこうないちゅうにゅう", category: "procedure", boost_weight: 2.0 },
  { term: "尿道カテーテル", reading: "にょうどうかてーてる", category: "procedure", boost_weight: 1.5 },
  { term: "間歇的自己導尿", reading: "かんけつてきじこどうにょう", category: "procedure", boost_weight: 2.0 },
  { term: "CIC", category: "procedure", boost_weight: 2.0 },
  { term: "TVT", category: "procedure", boost_weight: 2.0 },
  { term: "TOT", category: "procedure", boost_weight: 2.0 },
  // 解剖
  { term: "前立腺", reading: "ぜんりつせん", category: "anatomy", boost_weight: 1.5 },
  { term: "膀胱", reading: "ぼうこう", category: "anatomy", boost_weight: 1.5 },
  { term: "尿道", reading: "にょうどう", category: "anatomy", boost_weight: 1.5 },
  { term: "尿管", reading: "にょうかん", category: "anatomy", boost_weight: 1.5 },
  { term: "腎臓", reading: "じんぞう", category: "anatomy", boost_weight: 1.5 },
  { term: "腎盂", reading: "じんう", category: "anatomy", boost_weight: 1.5 },
  { term: "精巣", reading: "せいそう", category: "anatomy", boost_weight: 1.5 },
  { term: "精管", reading: "せいかん", category: "anatomy", boost_weight: 1.5 },
  { term: "副腎", reading: "ふくじん", category: "anatomy", boost_weight: 1.5 },
  { term: "陰茎", reading: "いんけい", category: "anatomy", boost_weight: 1.5 },
  { term: "陰嚢", reading: "いんのう", category: "anatomy", boost_weight: 1.5 },
  { term: "骨盤底筋", reading: "こつばんていきん", category: "anatomy", boost_weight: 1.5 },
];
